// src/renderer/components/generation/DynamicForm.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Icon } from '@iconify/vue'
import { schemaToFormFields, getDefaultValues, type FormFieldConfig } from '@/lib/schema-to-form'
import FormField from './FormField.vue'
import type { CanonicalEndpointDef } from '@/types'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = withDefaults(
  defineProps<{
    endpoint: CanonicalEndpointDef
    values: Record<string, unknown>
    validationErrors?: Record<string, string>
    disabled?: boolean
  }>(),
  { disabled: false, validationErrors: () => ({}) }
)

const emit = defineEmits<{
  change: [key: string, value: unknown]
  setDefaults: [defaults: Record<string, unknown>]
  fieldsChange: [fields: FormFieldConfig[]]
}>()

// ---------------------------------------------------------------------------
// Fields derived from endpoint schema
// ---------------------------------------------------------------------------

const fields = computed<FormFieldConfig[]>(() => {
  const schema = props.endpoint.requestSchema
  if (!schema?.properties) return []
  return schemaToFormFields(schema.properties, schema.required || [], schema.order)
})

const visibleFields = computed(() => fields.value.filter((f) => !f.hidden))
const advancedFields = computed(() => fields.value.filter((f) => f.hidden))

// ---------------------------------------------------------------------------
// Initialize defaults when endpoint changes
// ---------------------------------------------------------------------------

const initializedKey = ref<string | null>(null)
const advancedOpen = ref(false)

watch(
  () => [fields.value, props.endpoint.endpointKey] as const,
  ([currentFields, key]) => {
    emit('fieldsChange', currentFields)

    const hasExistingValues = Object.keys(props.values).some((k) => {
      const v = props.values[k]
      return v !== undefined && v !== '' && !(Array.isArray(v) && v.length === 0)
    })

    if (initializedKey.value !== key && !hasExistingValues) {
      emit('setDefaults', getDefaultValues(currentFields))
    }
    initializedKey.value = key
  },
  { immediate: true }
)

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

function handleChange(key: string, value: unknown): void {
  emit('change', key, value)
}
</script>

<template>
  <div v-if="fields.length === 0" class="py-8 text-center text-sm text-muted">
    No configurable parameters for this model.
  </div>

  <div v-else class="space-y-4">
    <!-- Visible fields -->
    <FormField
      v-for="field in visibleFields"
      :key="field.name"
      :field="field"
      :model-value="values[field.name]"
      :disabled="disabled"
      :error="validationErrors[field.name]"
      @update:model-value="(v) => handleChange(field.name, v)"
    />

    <!-- Advanced (hidden) fields — collapsible -->
    <div v-if="advancedFields.length > 0">
      <button
        type="button"
        :disabled="disabled"
        class="flex w-full items-center gap-1.5 py-1 text-xs text-muted transition-colors hover:text-surface-0"
        @click="advancedOpen = !advancedOpen"
      >
        <Icon
          icon="lucide:chevron-right"
          class="size-3.5 transition-transform duration-200"
          :class="{ 'rotate-90': advancedOpen }"
        />
        Advanced
      </button>

      <div v-show="advancedOpen" class="space-y-4 pt-2">
        <FormField
          v-for="field in advancedFields"
          :key="field.name"
          :field="field"
          :model-value="values[field.name]"
          :disabled="disabled"
          :error="validationErrors[field.name]"
          @update:model-value="(v) => handleChange(field.name, v)"
        />
      </div>
    </div>
  </div>
</template>

// src/renderer/components/generation/DynamicForm.tsx
import * as React from 'react'
import { useMemo, useEffect, useRef } from 'react'
import { ChevronRight } from 'lucide-react'
import type { CanonicalEndpointDef } from '@/types'
import { schemaToFormFields, getDefaultValues, type FormFieldConfig } from '@/lib/schema-to-form'
import { FormField } from './FormField'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { cn } from '@/lib/utils'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface DynamicFormProps {
  endpoint: CanonicalEndpointDef
  values: Record<string, unknown>
  validationErrors?: Record<string, string>
  onChange: (key: string, value: unknown) => void
  onSetDefaults: (defaults: Record<string, unknown>) => void
  onFieldsChange?: (fields: FormFieldConfig[]) => void
  disabled?: boolean
}

// ---------------------------------------------------------------------------
// DynamicForm
// ---------------------------------------------------------------------------

export function DynamicForm({
  endpoint,
  values,
  validationErrors = {},
  onChange,
  onSetDefaults,
  onFieldsChange,
  disabled = false
}: DynamicFormProps): React.JSX.Element {
  const initializedRef = useRef<string | null>(null)

  // Build field configs from the endpoint schema
  const fields = useMemo<FormFieldConfig[]>(() => {
    const schema = endpoint.requestSchema
    if (!schema?.properties) return []
    return schemaToFormFields(schema.properties, schema.required || [], schema.order)
  }, [endpoint])

  // Split into visible and hidden (advanced) fields
  const { visibleFields, advancedFields } = useMemo(() => {
    const visible: FormFieldConfig[] = []
    const advanced: FormFieldConfig[] = []
    for (const field of fields) {
      if (field.hidden) {
        advanced.push(field)
      } else {
        visible.push(field)
      }
    }
    return { visibleFields: visible, advancedFields: advanced }
  }, [fields])

  // Set defaults when endpoint changes
  useEffect(() => {
    onFieldsChange?.(fields)

    const hasExistingValues = Object.keys(values).some(
      (key) =>
        values[key] !== undefined &&
        values[key] !== '' &&
        !(Array.isArray(values[key]) && (values[key] as unknown[]).length === 0)
    )

    if (initializedRef.current !== endpoint.endpointKey && !hasExistingValues) {
      const defaults = getDefaultValues(fields)
      onSetDefaults(defaults)
    }
    initializedRef.current = endpoint.endpointKey
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [fields, endpoint.endpointKey, onFieldsChange, onSetDefaults])

  if (fields.length === 0) {
    return (
      <div className="text-center py-8 text-muted-foreground">
        <p className="text-sm">No configurable parameters for this model.</p>
      </div>
    )
  }

  return (
    <div className="space-y-4">
      {visibleFields.map((field) => (
        <FormField
          key={field.name}
          field={field}
          value={values[field.name]}
          onChange={(value) => onChange(field.name, value)}
          disabled={disabled}
          error={validationErrors[field.name]}
        />
      ))}

      {advancedFields.length > 0 && (
        <Collapsible defaultOpen={false}>
          <CollapsibleTrigger
            disabled={disabled}
            className={cn(
              'flex w-full items-center gap-1.5 py-1 text-xs text-muted-foreground',
              'hover:text-foreground transition-colors',
              '[&[data-state=open]>svg]:rotate-90'
            )}
          >
            <ChevronRight className="size-3.5 transition-transform duration-200" />
            Advanced
          </CollapsibleTrigger>
          <CollapsibleContent>
            <div className="space-y-4 pt-2">
              {advancedFields.map((field) => (
                <FormField
                  key={field.name}
                  field={field}
                  value={values[field.name]}
                  onChange={(value) => onChange(field.name, value)}
                  disabled={disabled}
                  error={validationErrors[field.name]}
                />
              ))}
            </div>
          </CollapsibleContent>
        </Collapsible>
      )}
    </div>
  )
}
