// src/renderer/components/generation/FormField.tsx
import { useEffect, useState } from 'react'
import type { FormFieldConfig } from '@/lib/schema-to-form'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Slider } from '@/components/ui/slider'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Button } from '@/components/ui/button'
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'
import { Dices } from 'lucide-react'
import { cn } from '@/lib/utils'
import { SizeSelector } from './SizeSelector'
import { LocalSizeSelector } from './LocalSizeSelector'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface FormFieldProps {
  field: FormFieldConfig
  value: unknown
  onChange: (value: unknown) => void
  disabled?: boolean
  error?: string
  hideLabel?: boolean
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const generateRandomSeed = () => Math.floor(Math.random() * 2147483648)

// ---------------------------------------------------------------------------
// FormField
// ---------------------------------------------------------------------------

export function FormField({
  field,
  value,
  onChange,
  disabled = false,
  error,
  hideLabel = false,
}: FormFieldProps) {
  const isSeedField = field.name.toLowerCase() === 'seed'
  const isNumericField = field.type === 'number' || field.type === 'slider'
  const isNumberField = field.type === 'number'
  const allowEmptyNumber = isNumberField && !field.required && field.default === undefined

  const numericFallback =
    value !== undefined && value !== null
      ? Number(value)
      : (field.default as number | undefined) ?? field.min ?? 0

  const [numericInput, setNumericInput] = useState(() => {
    if (!isNumericField) return ''
    if (allowEmptyNumber && (value === undefined || value === null)) return ''
    return String(numericFallback)
  })

  useEffect(() => {
    if (!isNumericField) return
    if (allowEmptyNumber && (value === undefined || value === null)) {
      setNumericInput('')
      return
    }
    const next =
      value !== undefined && value !== null
        ? Number(value)
        : (field.default as number | undefined) ?? field.min ?? 0
    setNumericInput(String(next))
  }, [isNumericField, value, field.default, field.min, allowEmptyNumber])

  const clampNumeric = (n: number) => {
    let next = n
    if (field.min !== undefined) next = Math.max(field.min, next)
    if (field.max !== undefined) next = Math.min(field.max, next)
    return next
  }

  const commitNumeric = (raw: string) => {
    if (raw.trim() === '' || Number.isNaN(Number(raw))) {
      if (allowEmptyNumber) {
        onChange(undefined)
        setNumericInput('')
        return
      }
      const fallback = (field.default as number | undefined) ?? field.min ?? 0
      onChange(fallback)
      setNumericInput(String(fallback))
      return
    }

    const parsed = Number(raw)
    const clamped = clampNumeric(parsed)
    onChange(clamped)
    setNumericInput(String(clamped))
  }

  // -------------------------------------------------------------------------
  // Render input based on field type
  // -------------------------------------------------------------------------

  const renderInput = () => {
    switch (field.type) {
      case 'text':
        return (
          <Input
            id={field.name}
            type="text"
            value={(value as string) || ''}
            onChange={(e) => onChange(e.target.value)}
            placeholder={field.placeholder || field.description || `Enter ${field.label.toLowerCase()}`}
            disabled={disabled}
          />
        )

      case 'textarea':
        return (
          <Textarea
            id={field.name}
            value={(value as string) || ''}
            onChange={(e) => onChange(e.target.value)}
            placeholder={field.placeholder || field.description || `Enter ${field.label.toLowerCase()}`}
            disabled={disabled}
            rows={4}
            className="resize-y"
            data-focus-prompt={field.name === 'prompt' ? 'true' : undefined}
          />
        )

      case 'number': {
        const hasSliderRange =
          field.default !== undefined && field.min !== undefined && field.max !== undefined
        const currentValue =
          value !== undefined && value !== null
            ? Number(value)
            : (field.default as number) ?? field.min ?? 0

        if (hasSliderRange) {
          return (
            <div className="flex items-center gap-3">
              <Slider
                value={[currentValue]}
                onValueChange={([v]) => {
                  onChange(v)
                  setNumericInput(String(v))
                }}
                min={field.min}
                max={field.max}
                step={field.step ?? 1}
                disabled={disabled}
                className="flex-1"
              />
              <Input
                id={field.name}
                type="number"
                value={numericInput}
                onChange={(e) => {
                  const val = e.target.value
                  setNumericInput(val)
                  if (val === '' || Number.isNaN(Number(val))) {
                    if (allowEmptyNumber) onChange(undefined)
                    return
                  }
                  onChange(Number(val))
                }}
                onBlur={() => commitNumeric(numericInput)}
                min={field.min}
                max={field.max}
                step={field.step}
                disabled={disabled}
                className="w-20 h-8 text-sm"
              />
            </div>
          )
        }

        // Number without full slider range (e.g. seed)
        return (
          <div className="flex items-center gap-2">
            <Input
              id={field.name}
              type="number"
              value={numericInput}
              onChange={(e) => {
                const val = e.target.value
                setNumericInput(val)
                if (val === '' || Number.isNaN(Number(val))) {
                  if (allowEmptyNumber) onChange(undefined)
                  return
                }
                onChange(Number(val))
              }}
              onBlur={() => commitNumeric(numericInput)}
              min={field.min}
              max={field.max}
              step={field.step}
              placeholder={
                field.default !== undefined
                  ? `Default: ${field.default}`
                  : 'Random'
              }
              disabled={disabled}
              className={isSeedField ? 'flex-1' : undefined}
            />
            {isSeedField && (
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    type="button"
                    variant="outline"
                    size="icon"
                    onClick={() => {
                      const next = generateRandomSeed()
                      onChange(next)
                      setNumericInput(String(next))
                    }}
                    disabled={disabled}
                    className="h-8 w-8"
                  >
                    <Dices className="h-4 w-4" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent side="top">
                  <p>Random seed</p>
                </TooltipContent>
              </Tooltip>
            )}
          </div>
        )
      }

      case 'slider': {
        const currentValue =
          value !== undefined && value !== null
            ? Number(value)
            : (field.default as number) ?? field.min ?? 0
        return (
          <div className="flex items-center gap-3">
            <Slider
              value={[currentValue]}
              onValueChange={([v]) => {
                onChange(v)
                setNumericInput(String(v))
              }}
              min={field.min ?? 0}
              max={field.max ?? 100}
              step={field.step ?? 1}
              disabled={disabled}
              className="flex-1"
            />
            <Input
              type="number"
              value={numericInput}
              onChange={(e) => {
                const val = e.target.value
                setNumericInput(val)
                if (val === '' || Number.isNaN(Number(val))) return
                onChange(Number(val))
              }}
              onBlur={() => commitNumeric(numericInput)}
              min={field.min}
              max={field.max}
              step={field.step}
              disabled={disabled}
              className="w-20 h-8 text-sm"
            />
          </div>
        )
      }

      case 'boolean':
        return (
          <div className="flex items-center space-x-2">
            <Switch
              id={field.name}
              checked={Boolean(value)}
              onCheckedChange={onChange}
              disabled={disabled}
            />
            <Label htmlFor={field.name} className="text-sm text-muted-foreground">
              {value ? 'Enabled' : 'Disabled'}
            </Label>
          </div>
        )

      case 'select': {
        const selectValue =
          value !== undefined && value !== null && value !== ''
            ? String(value)
            : field.default !== undefined
              ? String(field.default)
              : '__empty__'
        return (
          <Select
            value={selectValue}
            onValueChange={(v) => {
              if (v === '__empty__') {
                onChange(undefined)
                return
              }
              const originalOption = field.options?.find((opt) => String(opt) === v)
              onChange(originalOption !== undefined ? originalOption : v)
            }}
            disabled={disabled}
          >
            <SelectTrigger id={field.name}>
              <SelectValue placeholder={`Select ${field.label.toLowerCase()}`} />
            </SelectTrigger>
            <SelectContent>
              {!field.required && (
                <SelectItem value="__empty__" className="text-muted-foreground">
                  — None —
                </SelectItem>
              )}
              {field.options?.map((option) => (
                <SelectItem key={String(option)} value={String(option)}>
                  {String(option)}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        )
      }

      case 'size':
        return (
          <SizeSelector
            value={(value as string) || (field.default as string) || '1024*1024'}
            onChange={(v) => onChange(v)}
            disabled={disabled}
            min={field.min}
            max={field.max}
          />
        )

      case 'local-size':
        return (
          <LocalSizeSelector
            value={(value as string) || (field.default as string) || '1024*1024'}
            onChange={(v) => onChange(v)}
            disabled={disabled}
            min={field.min}
            max={field.max}
          />
        )

      default:
        return (
          <Input
            id={field.name}
            type="text"
            value={(value as string) || ''}
            onChange={(e) => onChange(e.target.value)}
            disabled={disabled}
          />
        )
    }
  }

  return (
    <div className="space-y-2">
      {!hideLabel && !field.hideLabel && (
        <div className="flex items-center gap-2">
          <Label
            htmlFor={field.name}
            className={cn(
              'text-xs font-medium',
              field.required && "after:content-['*'] after:ml-0.5 after:text-destructive",
              error && 'text-destructive'
            )}
          >
            {field.label}
          </Label>
          {field.min !== undefined && field.max !== undefined && field.type !== 'size' && field.type !== 'local-size' && (
            <span className="text-xs text-muted-foreground">
              ({field.min}–{field.max})
            </span>
          )}
        </div>
      )}
      <div
        className={cn(error && '[&_input]:border-destructive [&_textarea]:border-destructive')}
      >
        {renderInput()}
      </div>
      {error && <p className="text-xs text-destructive">{error}</p>}
      {!error && field.description && field.type !== 'text' && field.type !== 'textarea' && field.type !== 'size' && field.type !== 'local-size' && (
        <p className="text-xs text-muted-foreground">{field.description}</p>
      )}
    </div>
  )
}

// src/renderer/components/generation/FormField.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Icon } from '@iconify/vue'
import Button from 'primevue/button'
import InputText from 'primevue/inputtext'
import InputNumber from 'primevue/inputnumber'
import Textarea from 'primevue/textarea'
import Select from 'primevue/select'
import ToggleSwitch from 'primevue/toggleswitch'
import Slider from 'primevue/slider'

import SizeSelector from './SizeSelector.vue'
import LocalSizeSelector from './LocalSizeSelector.vue'
import type { FormFieldConfig } from '@/lib/schema-to-form'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = withDefaults(
  defineProps<{
    field: FormFieldConfig
    modelValue: unknown
    disabled?: boolean
    error?: string
    hideLabel?: boolean
  }>(),
  { disabled: false, hideLabel: false }
)

const emit = defineEmits<{
  'update:modelValue': [value: unknown]
}>()

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const generateRandomSeed = () => Math.floor(Math.random() * 2147483648)

const isSeedField = computed(() => props.field.name.toLowerCase() === 'seed')
const hasSliderRange = computed(
  () =>
    props.field.default !== undefined &&
    props.field.min !== undefined &&
    props.field.max !== undefined
)
const showRange = computed(
  () =>
    props.field.min !== undefined &&
    props.field.max !== undefined &&
    props.field.type !== 'size' &&
    props.field.type !== 'local-size'
)

// For numeric fields, we track a local string/number to support in-progress editing
const isNumericField = computed(() => props.field.type === 'number' || props.field.type === 'slider')
const allowEmptyNumber = computed(
  () => props.field.type === 'number' && !props.field.required && props.field.default === undefined
)

const numericValue = computed(() => {
  const v = props.modelValue
  if (v !== undefined && v !== null) return Number(v)
  return (props.field.default as number | undefined) ?? props.field.min ?? 0
})

function clamp(n: number): number {
  let next = n
  if (props.field.min !== undefined) next = Math.max(props.field.min, next)
  if (props.field.max !== undefined) next = Math.min(props.field.max, next)
  return next
}

// -- Number input local state --
const numberInput = ref<number | null>(numericValue.value)

watch(
  () => props.modelValue,
  (val) => {
    if (!isNumericField.value) return
    if (allowEmptyNumber.value && (val === undefined || val === null)) {
      numberInput.value = null
    } else {
      numberInput.value = val !== undefined && val !== null
        ? Number(val)
        : ((props.field.default as number | undefined) ?? props.field.min ?? 0)
    }
  }
)

function commitNumber(): void {
  if (numberInput.value === null || numberInput.value === undefined) {
    if (allowEmptyNumber.value) {
      emit('update:modelValue', undefined)
      return
    }
    const fallback = (props.field.default as number | undefined) ?? props.field.min ?? 0
    numberInput.value = fallback
    emit('update:modelValue', fallback)
    return
  }
  const clamped = clamp(numberInput.value)
  numberInput.value = clamped
  emit('update:modelValue', clamped)
}

function handleSliderChange(value: number): void {
  numberInput.value = value
  emit('update:modelValue', value)
}

// -- Select options --
const selectOptions = computed(() => {
  const options = (props.field.options ?? []).map((opt) => ({
    label: String(opt),
    value: opt
  }))
  if (!props.field.required) {
    options.unshift({ label: '— None —', value: undefined as unknown as string | number })
  }
  return options
})

const selectValue = computed(() => {
  if (props.modelValue !== undefined && props.modelValue !== null && props.modelValue !== '') {
    return props.modelValue
  }
  return props.field.default
})

// Size value
const sizeValue = computed({
  get: () => (props.modelValue as string) || (props.field.default as string) || '1024*1024',
  set: (v: string) => emit('update:modelValue', v)
})

// Description visible?
const showDescription = computed(
  () =>
    !props.error &&
    props.field.description &&
    !['text', 'textarea', 'size', 'local-size'].includes(props.field.type)
)
</script>

<template>
  <div class="space-y-1.5">
    <!-- Label -->
    <div v-if="!hideLabel && !field.hideLabel" class="flex items-center gap-2">
      <label :for="field.name" class="text-xs font-medium">
        {{ field.label }}
        <span v-if="field.required" class="text-red-400 ml-0.5">*</span>
      </label>
      <span v-if="showRange" class="text-xs text-muted">
        ({{ field.min }}–{{ field.max }})
      </span>
    </div>

    <!-- Text -->
    <InputText
      v-if="field.type === 'text'"
      :id="field.name"
      :model-value="(modelValue as string) || ''"
      :placeholder="field.placeholder || field.description || `Enter ${field.label.toLowerCase()}`"
      :disabled="disabled"
      :invalid="!!error"
      class="w-full"
      @update:model-value="(v: string | undefined) => emit('update:modelValue', v ?? '')"
    />

    <!-- Textarea -->
    <Textarea
      v-else-if="field.type === 'textarea'"
      :id="field.name"
      :model-value="(modelValue as string) || ''"
      :placeholder="field.placeholder || field.description || `Enter ${field.label.toLowerCase()}`"
      :disabled="disabled"
      :invalid="!!error"
      rows="4"
      auto-resize
      class="w-full"
      @update:model-value="(v: string | undefined) => emit('update:modelValue', v ?? '')"
    />

    <!-- Number with slider range -->
    <div v-else-if="field.type === 'number' && hasSliderRange" class="flex items-center gap-3">
      <Slider
        :model-value="numericValue"
        :min="field.min"
        :max="field.max"
        :step="field.step ?? 1"
        :disabled="disabled"
        class="flex-1"
        @update:model-value="(v: number | number[]) => handleSliderChange(Array.isArray(v) ? v[0] : v)"
      />
      <InputNumber
        v-model="numberInput"
        :min="field.min"
        :max="field.max"
        :step="field.step"
        :disabled="disabled"
        input-class="w-16 text-sm"
        @blur="commitNumber"
      />
    </div>

    <!-- Number without slider (e.g. seed) -->
    <div v-else-if="field.type === 'number'" class="flex items-center gap-2">
      <InputNumber
        v-model="numberInput"
        :min="field.min"
        :max="field.max"
        :step="field.step"
        :placeholder="field.default !== undefined ? `Default: ${field.default}` : 'Random'"
        :disabled="disabled"
        :invalid="!!error"
        :input-class="isSeedField ? 'w-full' : undefined"
        :class="isSeedField ? 'flex-1' : undefined"
        @blur="commitNumber"
      />
      <Button
        v-if="isSeedField"
        v-tooltip.top="'Random seed'"
        type="button"
        text
        severity="secondary"
        size="small"
        :disabled="disabled"
        @click="() => { const s = generateRandomSeed(); numberInput = s; emit('update:modelValue', s) }"
      >
        <Icon icon="lucide:dices" class="size-4" />
      </Button>
    </div>

    <!-- Slider -->
    <div v-else-if="field.type === 'slider'" class="flex items-center gap-3">
      <Slider
        :model-value="numericValue"
        :min="field.min ?? 0"
        :max="field.max ?? 100"
        :step="field.step ?? 1"
        :disabled="disabled"
        class="flex-1"
        @update:model-value="(v: number | number[]) => handleSliderChange(Array.isArray(v) ? v[0] : v)"
      />
      <InputNumber
        v-model="numberInput"
        :min="field.min"
        :max="field.max"
        :step="field.step"
        :disabled="disabled"
        input-class="w-16 text-sm"
        @blur="commitNumber"
      />
    </div>

    <!-- Boolean -->
    <div v-else-if="field.type === 'boolean'" class="flex items-center gap-2">
      <ToggleSwitch
        :id="field.name"
        :model-value="Boolean(modelValue)"
        :disabled="disabled"
        @update:model-value="(v: boolean) => emit('update:modelValue', v)"
      />
      <label :for="field.name" class="text-sm text-muted">
        {{ modelValue ? 'Enabled' : 'Disabled' }}
      </label>
    </div>

    <!-- Select -->
    <Select
      v-else-if="field.type === 'select'"
      :id="field.name"
      :model-value="selectValue"
      :options="selectOptions"
      option-label="label"
      option-value="value"
      :placeholder="`Select ${field.label.toLowerCase()}`"
      :disabled="disabled"
      :invalid="!!error"
      class="w-full"
      @update:model-value="(v: unknown) => emit('update:modelValue', v)"
    />

    <!-- Size selectors -->
    <SizeSelector
      v-else-if="field.type === 'size'"
      v-model="sizeValue"
      :disabled="disabled"
      :min="field.min"
      :max="field.max"
    />
    <LocalSizeSelector
      v-else-if="field.type === 'local-size'"
      v-model="sizeValue"
      :disabled="disabled"
      :min="field.min"
      :max="field.max"
    />

    <!-- Fallback -->
    <InputText
      v-else
      :id="field.name"
      :model-value="(modelValue as string) || ''"
      :disabled="disabled"
      class="w-full"
      @update:model-value="(v: string | undefined) => emit('update:modelValue', v ?? '')"
    />

    <!-- Error -->
    <p v-if="error" class="text-xs text-red-400">{{ error }}</p>

    <!-- Description -->
    <p v-if="showDescription" class="text-xs text-muted">{{ field.description }}</p>
  </div>
</template>
