// src/renderer/components/generation/ModeToggle.tsx
import * as React from 'react'

import { Film, ImageIcon, ImagePlus, Video } from 'lucide-react'

import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import { useGenerationStore } from '@/stores/generation-store'
import type { CanonicalEndpointDef, GenerationMode } from '@/types'

const MODES: Array<{
  value: GenerationMode
  label: string
  icon: React.ElementType
  outputType: 'image' | 'video'
}> = [
  { value: 'text-to-image', label: 'Text to Image', icon: ImageIcon, outputType: 'image' },
  { value: 'image-to-image', label: 'Image to Image', icon: ImagePlus, outputType: 'image' },
  { value: 'text-to-video', label: 'Text to Video', icon: Video, outputType: 'video' },
  { value: 'image-to-video', label: 'Image to Video', icon: Film, outputType: 'video' }
]

/**
 * Top-level generation mode toggle.
 * Dictates which models/endpoints are available in the ModelSelector.
 */
export function ModeToggle(): React.JSX.Element {
  const generationMode = useGenerationStore((s) => s.generationMode)
  const endpointKey = useGenerationStore((s) => s.endpointKey)
  const setGenerationMode = useGenerationStore((s) => s.setGenerationMode)

  const [endpoints, setEndpoints] = React.useState<CanonicalEndpointDef[]>([])

  React.useEffect(() => {
    window.api
      .listGenerationEndpoints()
      .then(setEndpoints)
      .catch(() => {})
  }, [])

  const selectedEndpoint = React.useMemo(
    () => endpoints.find((endpoint) => endpoint.endpointKey === endpointKey),
    [endpointKey, endpoints]
  )

  const availableModes = React.useMemo(() => {
    if (!selectedEndpoint) {
      return MODES
    }

    return MODES.filter((mode) => mode.outputType === selectedEndpoint.outputType)
  }, [selectedEndpoint])

  React.useEffect(() => {
    if (availableModes.some((mode) => mode.value === generationMode)) {
      return
    }

    if (availableModes[0]) {
      setGenerationMode(availableModes[0].value)
    }
  }, [availableModes, generationMode, setGenerationMode])

  return (
    <ToggleGroup
      type="single"
      value={generationMode}
      onValueChange={(value) => {
        // ToggleGroup fires empty string when deselecting — ignore it
        if (value) setGenerationMode(value as GenerationMode)
      }}
      variant="outline"
      size="sm"
      className="w-full"
    >
      {availableModes.map(({ value, label, icon: Icon }) => (
        <ToggleGroupItem
          key={value}
          value={value}
          className="flex-1 gap-1.5 text-xs"
          aria-label={label}
        >
          <Icon className="size-3.5" />
          {label}
        </ToggleGroupItem>
      ))}
    </ToggleGroup>
  )
}

// src/renderer/components/generation/ModeToggle.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { Icon } from '@iconify/vue'
import Button from 'primevue/button'

import { useGenerationStore } from '@/stores/generation'
import type { CanonicalEndpointDef, GenerationMode } from '@/types'

const MODES: { value: GenerationMode; label: string; icon: string; outputType: 'image' | 'video' }[] = [
  { value: 'text-to-image', label: 'Text to Image', icon: 'lucide:image', outputType: 'image' },
  { value: 'image-to-image', label: 'Image to Image', icon: 'lucide:image-plus', outputType: 'image' },
  { value: 'text-to-video', label: 'Text to Video', icon: 'lucide:video', outputType: 'video' },
  { value: 'image-to-video', label: 'Image to Video', icon: 'lucide:film', outputType: 'video' }
]

const generationStore = useGenerationStore()
const endpoints = ref<CanonicalEndpointDef[]>([])

onMounted(async () => {
  try {
    endpoints.value = await window.api.listGenerationEndpoints()
  } catch {
    // ignore
  }
})

const selectedEndpoint = computed(() =>
  endpoints.value.find((ep) => ep.endpointKey === generationStore.endpointKey) ?? null
)

const availableModes = computed(() => {
  if (!selectedEndpoint.value) return MODES
  return MODES.filter((m) => m.outputType === selectedEndpoint.value!.outputType)
})

// Ensure current mode is valid when available modes change
watch(availableModes, (modes) => {
  if (modes.some((m) => m.value === generationStore.generationMode)) return
  if (modes[0]) generationStore.setGenerationMode(modes[0].value)
})

function handleModeChange(value: GenerationMode): void {
  if (value) generationStore.setGenerationMode(value)
}
</script>

<template>
  <div class="flex gap-1">
    <Button
      v-for="mode in availableModes"
      :key="mode.value"
      size="small"
      :outlined="generationStore.generationMode !== mode.value"
      :severity="generationStore.generationMode === mode.value ? undefined : 'secondary'"
      class="flex-1 gap-1"
      :aria-label="mode.label"
      @click="handleModeChange(mode.value)"
    >
      <Icon :icon="mode.icon" class="size-3.5" />
      <span class="text-xs">{{ mode.label }}</span>
    </Button>
  </div>
</template>
