// src/renderer/components/generation/ModelSelector.tsx
import * as React from 'react'

import {
  Select,
  SelectContent,
  SelectItem,
  SelectSeparator,
  SelectTrigger,
  SelectValue
} from '@/components/ui/select'
import { SectionLabel } from '@/components/ui/section-label'
import { useModelStore } from '@/stores/model-store'
import { useProviderStore } from '@/stores/provider-store'
import { useModelBrowsingStore } from '@/stores/model-browsing-store'
import { useGenerationStore } from '@/stores/generation-store'
import { useUIStore } from '@/stores/ui-store'
import type { CanonicalEndpointDef, ModelIdentity } from '@/types'

const MANAGE_MODELS_VALUE = '__manage_models__'
const MANAGE_PROVIDERS_VALUE = '__manage_providers__'

/**
 * A unified provider entry — either local or remote.
 */
interface ProviderOption {
  label: string
  endpointKey: string
  providerId: string
  providerModelId: string
  isLocal: boolean
  isReady: boolean
}

export function ModelSelector(): React.JSX.Element {
  const filesByModelId = useModelStore((s) => s.filesByModelId)
  const setActiveModel = useModelStore((s) => s.setActiveModel)

  const providers = useProviderStore((s) => s.providers)
  const loadProviders = useProviderStore((s) => s.loadProviders)
  const identities = useModelBrowsingStore((s) => s.identities)
  const loadAllUserModels = useModelBrowsingStore((s) => s.loadAllUserModels)
  const loadIdentities = useModelBrowsingStore((s) => s.loadIdentities)
  const catalogVersion = useModelBrowsingStore((s) => s.catalogVersion)

  const endpointKey = useGenerationStore((s) => s.endpointKey)
  const setEndpointKey = useGenerationStore((s) => s.setEndpointKey)
  const generationMode = useGenerationStore((s) => s.generationMode)

  const openModal = useUIStore((s) => s.openModal)

  const [endpoints, setEndpoints] = React.useState<CanonicalEndpointDef[]>([])

  // Load endpoints and provider data on mount; re-fetch endpoints when user models change
  React.useEffect(() => {
    window.api
      .listGenerationEndpoints()
      .then(setEndpoints)
      .catch(() => {})
  }, [catalogVersion])

  React.useEffect(() => {
    void loadProviders().then(() => void loadAllUserModels())
    void loadIdentities()
  }, [loadProviders, loadAllUserModels, loadIdentities])

  // Filter endpoints to only those supporting the active generation mode
  const modeEndpoints = React.useMemo(
    () => endpoints.filter((ep) => ep.modes.includes(generationMode)),
    [endpoints, generationMode]
  )

  const providerDisplayNames = React.useMemo(
    () =>
      Object.fromEntries(
        providers.map((provider) => [
          provider.providerId,
          provider.displayName ?? provider.providerId
        ])
      ),
    [providers]
  )

  const identityMap = React.useMemo(() => {
    const map = new Map<string, { identity: ModelIdentity; providerOptions: ProviderOption[] }>()

    for (const endpoint of modeEndpoints) {
      const isLocal = endpoint.providerId === 'local'
      const isReady = isLocal ? (filesByModelId[endpoint.providerModelId]?.isReady ?? false) : true
      const identityId =
        endpoint.modelIdentityId ?? `${endpoint.providerId}-${endpoint.providerModelId}`
      const identity =
        identities.find((entry) => entry.id === identityId) ??
        identities.find((entry) =>
          entry.providerMapping?.[endpoint.providerId]?.includes(endpoint.providerModelId)
        )
      const resolvedIdentityId = identity?.id ?? identityId
      const label = isLocal
        ? 'Local (cn-engine)'
        : (providerDisplayNames[endpoint.providerId] ?? endpoint.providerId)

      if (!map.has(resolvedIdentityId)) {
        map.set(resolvedIdentityId, {
          identity: identity ?? {
            id: resolvedIdentityId,
            name: endpoint.displayName,
            providerMapping: {}
          },
          providerOptions: []
        })
      }

      map.get(resolvedIdentityId)!.providerOptions.push({
        label,
        endpointKey: endpoint.endpointKey,
        providerId: endpoint.providerId,
        providerModelId: endpoint.providerModelId,
        isLocal,
        isReady
      })
    }

    return map
  }, [modeEndpoints, filesByModelId, identities, providerDisplayNames])

  // Find currently selected identity and provider from endpointKey
  const currentEntry = (() => {
    for (const entry of identityMap.values()) {
      const match = entry.providerOptions.find((p) => p.endpointKey === endpointKey)
      if (match) return { identity: entry.identity, provider: match, entry }
    }
    return null
  })()

  // Available identities as sorted array
  const identityEntries = React.useMemo(
    () =>
      Array.from(identityMap.entries())
        .map(([id, entry]) => ({ id, ...entry }))
        .sort((a, b) => a.identity.name.localeCompare(b.identity.name)),
    [identityMap]
  )

  // Provider options for the currently selected identity
  const currentProviderOptions = currentEntry?.entry.providerOptions ?? []

  // Auto-select an endpoint when the generation mode changes and the current
  // endpoint doesn't support the new mode (currentEntry becomes null).
  React.useEffect(() => {
    if (currentEntry || identityEntries.length === 0) return

    // Pick the first identity with a ready provider option, fall back to first available
    const firstReady = identityEntries.find((e) => e.providerOptions.some((p) => p.isReady))
    const fallback = firstReady ?? identityEntries[0]
    if (!fallback) return

    const local = fallback.providerOptions.find((p) => p.isLocal && p.isReady)
    const first = fallback.providerOptions[0]
    const chosen = local ?? first
    if (chosen) {
      setEndpointKey(chosen.endpointKey)
      if (chosen.isLocal) void setActiveModel(chosen.providerModelId)
    }
  }, [currentEntry, identityEntries, setEndpointKey, setActiveModel])

  // When model identity changes, pick the first available provider
  const handleModelChange = (identityId: string): void => {
    if (identityId === MANAGE_MODELS_VALUE) {
      openModal('models')
      return
    }

    const entry = identityMap.get(identityId)
    if (!entry) return

    // Prefer local if ready, otherwise first available
    const local = entry.providerOptions.find((p) => p.isLocal && p.isReady)
    const first = entry.providerOptions[0]
    const chosen = local ?? first
    if (chosen) {
      setEndpointKey(chosen.endpointKey)
      if (chosen.isLocal) void setActiveModel(chosen.providerModelId)
    }
  }

  const handleProviderChange = (newEndpointKey: string): void => {
    if (newEndpointKey === MANAGE_PROVIDERS_VALUE) {
      openModal('providers')
      return
    }
    setEndpointKey(newEndpointKey)

    // If switching to local, set active model from the provider option
    const option = currentProviderOptions.find((p) => p.endpointKey === newEndpointKey)
    if (option?.isLocal) {
      void setActiveModel(option.providerModelId)
    }
  }

  return (
    <div className="space-y-2">
      {/* Model selector */}
      <SectionLabel>Model</SectionLabel>
      <Select value={currentEntry?.identity.id ?? ''} onValueChange={handleModelChange}>
        <SelectTrigger className="w-full">
          <SelectValue placeholder="Select model" />
        </SelectTrigger>
        <SelectContent>
          {identityEntries.map((entry) => {
            const hasReadyOption = entry.providerOptions.some((p) => p.isReady)
            return (
              <SelectItem key={entry.id} value={entry.id}>
                {entry.identity.name}
                {!hasReadyOption ? ' (Setup Required)' : ''}
              </SelectItem>
            )
          })}
          <SelectSeparator />
        </SelectContent>
      </Select>

      {/* Provider selector — only show when there are multiple provider options */}
      {currentProviderOptions.length > 1 && (
        <>
          <SectionLabel>Provider</SectionLabel>
          <Select value={endpointKey} onValueChange={handleProviderChange}>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select provider" />
            </SelectTrigger>
            <SelectContent>
              {currentProviderOptions.map((option) => (
                <SelectItem key={option.endpointKey} value={option.endpointKey}>
                  {option.label}
                  {!option.isReady ? ' (Setup Required)' : ''}
                </SelectItem>
              ))}
              <SelectSeparator />
            </SelectContent>
          </Select>
        </>
      )}

    </div>
  )
}

// src/renderer/components/generation/ModelSelector.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import Select from 'primevue/select'

import PaneSection from '@/components/panes/PaneSection.vue'
import { useModelStore } from '@/stores/model'
import { useProviderStore } from '@/stores/provider'
import { useModelBrowsingStore } from '@/stores/model-browsing'
import { useGenerationStore } from '@/stores/generation'
import type { CanonicalEndpointDef, ModelIdentity } from '@/types'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ProviderOption {
  label: string
  endpointKey: string
  providerId: string
  providerModelId: string
  isLocal: boolean
  isReady: boolean
}

interface IdentityEntry {
  id: string
  identity: ModelIdentity
  providerOptions: ProviderOption[]
}

// ---------------------------------------------------------------------------
// Stores
// ---------------------------------------------------------------------------

const modelStore = useModelStore()
const providerStore = useProviderStore()
const modelBrowsingStore = useModelBrowsingStore()
const generationStore = useGenerationStore()

const endpoints = ref<CanonicalEndpointDef[]>([])

// ---------------------------------------------------------------------------
// Load data
// ---------------------------------------------------------------------------

onMounted(async () => {
  await providerStore.loadProviders()
  await modelBrowsingStore.loadAllUserModels()
  await modelBrowsingStore.loadIdentities()
})

// Re-fetch endpoints when catalog version changes (user model added/removed)
watch(
  () => modelBrowsingStore.catalogVersion,
  async () => {
    try {
      endpoints.value = await window.api.listGenerationEndpoints()
    } catch {
      // ignore
    }
  },
  { immediate: true }
)

// ---------------------------------------------------------------------------
// Computed
// ---------------------------------------------------------------------------

const modeEndpoints = computed(() =>
  endpoints.value.filter((ep) => ep.modes.includes(generationStore.generationMode))
)

const providerDisplayNames = computed(() =>
  Object.fromEntries(
    providerStore.providers.map((p) => [p.providerId, p.displayName ?? p.providerId])
  )
)

const identityMap = computed(() => {
  const map = new Map<string, { identity: ModelIdentity; providerOptions: ProviderOption[] }>()

  for (const endpoint of modeEndpoints.value) {
    const isLocal = endpoint.providerId === 'local'
    const isReady = isLocal
      ? (modelStore.filesByModelId[endpoint.providerModelId]?.isReady ?? false)
      : true
    const identityId = endpoint.modelIdentityId ?? `${endpoint.providerId}-${endpoint.providerModelId}`
    const identity =
      modelBrowsingStore.identities.find((e) => e.id === identityId) ??
      modelBrowsingStore.identities.find((e) =>
        e.providerMapping?.[endpoint.providerId]?.includes(endpoint.providerModelId)
      )
    const resolvedId = identity?.id ?? identityId
    const label = isLocal
      ? 'Local (cn-engine)'
      : (providerDisplayNames.value[endpoint.providerId] ?? endpoint.providerId)

    if (!map.has(resolvedId)) {
      map.set(resolvedId, {
        identity: identity ?? { id: resolvedId, name: endpoint.displayName, providerMapping: {} },
        providerOptions: []
      })
    }

    map.get(resolvedId)!.providerOptions.push({
      label,
      endpointKey: endpoint.endpointKey,
      providerId: endpoint.providerId,
      providerModelId: endpoint.providerModelId,
      isLocal,
      isReady
    })
  }

  return map
})

const identityEntries = computed<IdentityEntry[]>(() =>
  Array.from(identityMap.value.entries())
    .map(([id, entry]) => ({ id, ...entry }))
    .sort((a, b) => a.identity.name.localeCompare(b.identity.name))
)

const currentEntry = computed(() => {
  for (const entry of identityMap.value.values()) {
    const match = entry.providerOptions.find((p) => p.endpointKey === generationStore.endpointKey)
    if (match) return { identity: entry.identity, provider: match, entry }
  }
  return null
})

const currentIdentityId = computed(() => currentEntry.value?.identity.id ?? null)
const currentProviderOptions = computed(() => currentEntry.value?.entry.providerOptions ?? [])
const showProviderSelect = computed(() => currentProviderOptions.value.length > 1)

// PrimeVue Select options
const modelOptions = computed(() =>
  identityEntries.value.map((e) => ({
    label: e.identity.name + (e.providerOptions.some((p) => p.isReady) ? '' : ' (Setup Required)'),
    value: e.id
  }))
)

const providerOptions = computed(() =>
  currentProviderOptions.value.map((o) => ({
    label: o.label + (o.isReady ? '' : ' (Setup Required)'),
    value: o.endpointKey
  }))
)

// ---------------------------------------------------------------------------
// Auto-select
// ---------------------------------------------------------------------------

watch(
  [currentEntry, identityEntries],
  ([entry, entries]) => {
    if (entry || entries.length === 0) return
    const firstReady = entries.find((e) => e.providerOptions.some((p) => p.isReady))
    const fallback = firstReady ?? entries[0]
    if (!fallback) return
    const local = fallback.providerOptions.find((p) => p.isLocal && p.isReady)
    const chosen = local ?? fallback.providerOptions[0]
    if (chosen) {
      generationStore.setEndpointKey(chosen.endpointKey)
      if (chosen.isLocal) void modelStore.setActiveModel(chosen.providerModelId)
    }
  }
)

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

function handleModelChange(identityId: string): void {
  const entry = identityMap.value.get(identityId)
  if (!entry) return
  const local = entry.providerOptions.find((p) => p.isLocal && p.isReady)
  const chosen = local ?? entry.providerOptions[0]
  if (chosen) {
    generationStore.setEndpointKey(chosen.endpointKey)
    if (chosen.isLocal) void modelStore.setActiveModel(chosen.providerModelId)
  }
}

function handleProviderChange(endpointKey: string): void {
  generationStore.setEndpointKey(endpointKey)
  const option = currentProviderOptions.value.find((p) => p.endpointKey === endpointKey)
  if (option?.isLocal) void modelStore.setActiveModel(option.providerModelId)
}
</script>

<template>
  <div class="space-y-2">
    <PaneSection title="Model">
      <Select
        :model-value="currentIdentityId"
        :options="modelOptions"
        option-label="label"
        option-value="value"
        placeholder="Select model"
        class="w-full"
        @update:model-value="handleModelChange"
      />
    </PaneSection>

    <PaneSection v-if="showProviderSelect" title="Provider">
      <Select
        :model-value="generationStore.endpointKey"
        :options="providerOptions"
        option-label="label"
        option-value="value"
        placeholder="Select provider"
        class="w-full"
        @update:model-value="handleProviderChange"
      />
    </PaneSection>
  </div>
</template>
