// src/renderer/components/panes/CollectionsPane.vue
<script setup lang="ts">
import { ref } from 'vue'

import PaneLayout from '@/components/panes/PaneLayout.vue'
import SelectableItem from '@/components/shared/SelectableItem.vue'
import { useCollectionStore } from '@/stores/collection'
import { useUIStore } from '@/stores/ui'
import type { CollectionRecord } from '@/types'

const uiStore = useUIStore()
const collectionStore = useCollectionStore()

// ---------------------------------------------------------------------------
// Drag & drop state
// ---------------------------------------------------------------------------

const draggingCollectionId = ref<string | null>(null)
const dragOverCollectionId = ref<string | null>(null)
const mediaDragOverId = ref<string | null>(null)

function hasMediaDragData(e: DragEvent): boolean {
  return (
    e.dataTransfer?.types.includes('application/x-distillery-media-ids') === true ||
    e.dataTransfer?.types.includes('application/x-distillery-media-id') === true
  )
}

function parseDroppedMediaIds(e: DragEvent): string[] {
  if (!e.dataTransfer) return []

  const multiIdsRaw = e.dataTransfer.getData('application/x-distillery-media-ids')
  const singleId = e.dataTransfer.getData('application/x-distillery-media-id')

  if (multiIdsRaw) {
    try {
      const parsed: unknown = JSON.parse(multiIdsRaw)
      if (Array.isArray(parsed)) {
        return parsed.filter((id): id is string => typeof id === 'string' && id.length > 0)
      }
    } catch {
      // no-op
    }
  }

  return singleId ? [singleId] : []
}

// ---------------------------------------------------------------------------
// Collection drag-to-reorder handlers
// ---------------------------------------------------------------------------

function onDragStart(e: DragEvent, collection: CollectionRecord): void {
  draggingCollectionId.value = collection.id
  if (e.dataTransfer) {
    e.dataTransfer.effectAllowed = 'move'
    e.dataTransfer.setData('application/x-distillery-collection-id', collection.id)
  }
}

function onDragEnd(): void {
  draggingCollectionId.value = null
  dragOverCollectionId.value = null
}

function onDragOver(e: DragEvent, collection: CollectionRecord): void {
  if (hasMediaDragData(e)) {
    e.preventDefault()
    mediaDragOverId.value = collection.id
    return
  }

  if (draggingCollectionId.value && draggingCollectionId.value !== collection.id) {
    e.preventDefault()
    dragOverCollectionId.value = collection.id
  }
}

function onDragLeave(): void {
  dragOverCollectionId.value = null
  mediaDragOverId.value = null
}

function onDrop(e: DragEvent, collection: CollectionRecord): void {
  e.preventDefault()
  mediaDragOverId.value = null

  // Handle media drop onto collection
  const mediaIds = parseDroppedMediaIds(e)
  if (mediaIds.length > 0) {
    void collectionStore.addMediaToCollection(collection.id, mediaIds)
    dragOverCollectionId.value = null
    return
  }

  // Handle collection reorder
  const draggedId =
    e.dataTransfer?.getData('application/x-distillery-collection-id') ||
    draggingCollectionId.value

  if (!draggedId || draggedId === collection.id) {
    dragOverCollectionId.value = null
    return
  }

  const orderedIds = collectionStore.manualCollections.map((c) => c.id)
  const fromIndex = orderedIds.indexOf(draggedId)
  const toIndex = orderedIds.indexOf(collection.id)

  if (fromIndex === -1 || toIndex === -1 || fromIndex === toIndex) {
    dragOverCollectionId.value = null
    return
  }

  const [moved] = orderedIds.splice(fromIndex, 1)
  orderedIds.splice(toIndex, 0, moved)
  collectionStore.reorderCollections(orderedIds)

  draggingCollectionId.value = null
  dragOverCollectionId.value = null
}

// ---------------------------------------------------------------------------
// Edit modal (placeholder — modal not yet ported)
// ---------------------------------------------------------------------------

function openEditModal(collectionId: string): void {
  collectionStore.setEditingCollectionId(collectionId)
  uiStore.openModal('collection')
}
</script>

<template>
  <PaneLayout title="Collections">
    <div class="space-y-1">
      <!-- Special collections (All, Generated, Imported) -->
      <SelectableItem
        v-for="collection in collectionStore.specialCollections"
        :key="collection.id"
        :selected="collection.id === collectionStore.activeCollectionId"
        @select="collectionStore.setActiveCollection(collection.id)"
      >
        <UIcon name="i-lucide-star" class="size-4 shrink-0 text-muted" />
        <span class="min-w-0 flex-1 truncate">{{ collection.name }}</span>
        <UBadge color="neutral" variant="subtle" size="sm">
          {{ collection.media_count }}
        </UBadge>
      </SelectableItem>

      <!-- Separator between special and manual collections -->
      <USeparator
        v-if="collectionStore.specialCollections.length > 0 && collectionStore.manualCollections.length > 0"
        class="my-2"
      />

      <!-- Manual collections (user-created, draggable) -->
      <SelectableItem
        v-for="collection in collectionStore.manualCollections"
        :key="collection.id"
        :selected="collection.id === collectionStore.activeCollectionId"
        :draggable="true"
        :drag-over="
          dragOverCollectionId === collection.id || mediaDragOverId === collection.id
        "
        @select="collectionStore.setActiveCollection(collection.id)"
        @dragstart="onDragStart($event, collection)"
        @dragend="onDragEnd"
        @dragover="onDragOver($event, collection)"
        @dragleave="onDragLeave"
        @drop="onDrop($event, collection)"
      >
        <UIcon
          name="i-lucide-layers-3"
          class="size-4 shrink-0"
          :style="{ color: collection.color }"
        />
        <span class="min-w-0 flex-1 truncate">{{ collection.name }}</span>

        <UTooltip text="Edit collection">
          <UButton
            icon="i-lucide-settings"
            color="neutral"
            variant="ghost"
            size="xs"
            class="opacity-0 group-hover/item:opacity-100"
            @click.stop="openEditModal(collection.id)"
          />
        </UTooltip>

        <UBadge color="neutral" variant="subtle" size="sm">
          {{ collection.media_count }}
        </UBadge>
      </SelectableItem>
    </div>
  </PaneLayout>
</template>

// src/renderer/components/panes/CollectionsPane.tsx
import * as React from 'react'
import { Layers3, Settings, Star } from 'lucide-react'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import { cn } from '@/lib/utils'
import { useCollectionStore } from '@/stores/collection-store'
import { useUIStore } from '@/stores/ui-store'
import type { CollectionRecord } from '@/types'

function parseDroppedMediaIds(e: React.DragEvent): string[] {
  const multiIdsRaw = e.dataTransfer.getData('application/x-distillery-media-ids')
  const singleId = e.dataTransfer.getData('application/x-distillery-media-id')

  if (multiIdsRaw) {
    try {
      const parsed = JSON.parse(multiIdsRaw) as unknown
      if (Array.isArray(parsed)) {
        return parsed.filter((id): id is string => typeof id === 'string' && id.length > 0)
      }
    } catch {
      // no-op
    }
  }

  return singleId ? [singleId] : []
}

function CollectionRow({
  collection,
  active,
  isReorderDragOver,
  onSelect,
  onEdit,
  onDragStart,
  onDragEnd,
  onDragOver,
  onDragLeave,
  onDrop
}: {
  collection: CollectionRecord
  active: boolean
  isReorderDragOver: boolean
  onSelect: () => void
  onEdit: () => void
  onDragStart: (e: React.DragEvent) => void
  onDragEnd: () => void
  onDragOver: (e: React.DragEvent) => void
  onDragLeave: () => void
  onDrop: (e: React.DragEvent) => void
}): React.JSX.Element {
  const isSpecial = collection.type === 'special'
  const [isHovered, setIsHovered] = React.useState(false)

  return (
    <div
      className={cn(
        'flex items-center gap-2 rounded-md border px-2 py-1.5 transition-colors',
        active ? 'border-primary/40 bg-primary/10' : 'border-transparent hover:bg-accent',
        isReorderDragOver && 'border-primary/50 bg-primary/5'
      )}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      draggable={!isSpecial}
      onDragStart={onDragStart}
      onDragEnd={onDragEnd}
      onDragOver={onDragOver}
      onDragLeave={onDragLeave}
      onDrop={onDrop}
    >
      <button
        type="button"
        className="flex min-w-0 flex-1 items-center gap-2 text-left"
        onClick={onSelect}
      >
        {isSpecial ? (
          <Star className="size-3.5 text-muted-foreground" />
        ) : (
          <Layers3 className="size-3.5" color={collection.color} aria-hidden="true" />
        )}
        <span className="truncate text-sm">{collection.name}</span>
      </button>

      <div className="ml-auto flex items-center gap-0.5">
        {!isSpecial ? (
          <Button
            type="button"
            variant="outline"
            size="icon-sm"
            className={cn(
              'size-6 transition-opacity bg-background',
              isHovered ? 'opacity-100' : 'pointer-events-none opacity-0'
            )}
            onClick={(e) => {
              e.stopPropagation()
              onEdit()
            }}
            aria-label={`Edit ${collection.name}`}
          >
            <Settings className="size-3.5" />
          </Button>
        ) : (
          <span className="size-6" aria-hidden="true" />
        )}
        <div className="w-8 text-right">
          <Badge variant="ghost" className="bg-background">
            {collection.media_count}
          </Badge>
        </div>
      </div>
    </div>
  )
}

export function CollectionsPane(): React.JSX.Element {
  const openModal = useUIStore((state) => state.openModal)

  const collections = useCollectionStore((state) => state.collections)
  const activeCollectionId = useCollectionStore((state) => state.activeCollectionId)
  const setActiveCollection = useCollectionStore((state) => state.setActiveCollection)
  const setEditingCollectionId = useCollectionStore((state) => state.setEditingCollectionId)
  const reorderCollections = useCollectionStore((state) => state.reorderCollections)
  const addMediaToCollection = useCollectionStore((state) => state.addMediaToCollection)

  const [draggingCollectionId, setDraggingCollectionId] = React.useState<string | null>(null)
  const [dragOverCollectionId, setDragOverCollectionId] = React.useState<string | null>(null)

  const specialCollections = collections.filter((collection) => collection.type === 'special')
  const manualCollections = collections.filter((collection) => collection.type !== 'special')

  const openEditModal = React.useCallback(
    (collectionId: string) => {
      setEditingCollectionId(collectionId)
      openModal('collection')
    },
    [openModal, setEditingCollectionId]
  )

  return (
    <div className="space-y-1">
      {specialCollections.map((collection) => (
        <CollectionRow
          key={collection.id}
          collection={collection}
          active={collection.id === activeCollectionId}
          isReorderDragOver={false}
          onSelect={() => setActiveCollection(collection.id)}
          onEdit={() => {}}
          onDragStart={() => {}}
          onDragEnd={() => {
            setDraggingCollectionId(null)
            setDragOverCollectionId(null)
          }}
          onDragOver={(e) => {
            const mediaIds = parseDroppedMediaIds(e)
            if (mediaIds.length > 0) e.preventDefault()
          }}
          onDragLeave={() => setDragOverCollectionId(null)}
          onDrop={() => {
            setDragOverCollectionId(null)
          }}
        />
      ))}

      {manualCollections.length > 0 && specialCollections.length > 0 && (
        <Separator className="my-2" />
      )}

      {manualCollections.map((collection) => (
        <CollectionRow
          key={collection.id}
          collection={collection}
          active={collection.id === activeCollectionId}
          isReorderDragOver={dragOverCollectionId === collection.id}
          onSelect={() => setActiveCollection(collection.id)}
          onEdit={() => openEditModal(collection.id)}
          onDragStart={(e) => {
            setDraggingCollectionId(collection.id)
            e.dataTransfer.effectAllowed = 'move'
            e.dataTransfer.setData('application/x-distillery-collection-id', collection.id)
          }}
          onDragEnd={() => {
            setDraggingCollectionId(null)
            setDragOverCollectionId(null)
          }}
          onDragOver={(e) => {
            const mediaIds = parseDroppedMediaIds(e)
            const draggedCollectionId =
              e.dataTransfer.getData('application/x-distillery-collection-id') ||
              draggingCollectionId

            if (mediaIds.length > 0) {
              e.preventDefault()
              return
            }

            if (draggedCollectionId && draggedCollectionId !== collection.id) {
              e.preventDefault()
              setDragOverCollectionId(collection.id)
            }
          }}
          onDragLeave={() => setDragOverCollectionId(null)}
          onDrop={(e) => {
            e.preventDefault()

            const mediaIds = parseDroppedMediaIds(e)
            if (mediaIds.length > 0) {
              void addMediaToCollection(collection.id, mediaIds)
              setDragOverCollectionId(null)
              return
            }

            const draggedCollectionId =
              e.dataTransfer.getData('application/x-distillery-collection-id') ||
              draggingCollectionId

            if (!draggedCollectionId || draggedCollectionId === collection.id) {
              setDragOverCollectionId(null)
              return
            }

            const nextOrderedIds = manualCollections.map((item) => item.id)
            const fromIndex = nextOrderedIds.indexOf(draggedCollectionId)
            const toIndex = nextOrderedIds.indexOf(collection.id)

            if (fromIndex === -1 || toIndex === -1 || fromIndex === toIndex) {
              setDragOverCollectionId(null)
              return
            }

            const [moved] = nextOrderedIds.splice(fromIndex, 1)
            nextOrderedIds.splice(toIndex, 0, moved)
            reorderCollections(nextOrderedIds)

            setDraggingCollectionId(null)
            setDragOverCollectionId(null)
          }}
        />
      ))}
    </div>
  )
}
