// src/renderer/components/panes/GenerationPane.tsx
import * as React from 'react'

import { Loader2 } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { validateFormValues, type FormFieldConfig } from '@/lib/schema-to-form'
import { useGenerationStore } from '@/stores/generation-store'
import { useEngineStore } from '@/stores/engine-store'
import { useQueueStore } from '@/stores/queue-store'
import { useModelStore } from '@/stores/model-store'
import { ModelSelector } from '@/components/generation/ModelSelector'
import { RefImageDropzone } from '@/components/generation/RefImageDropzone'
import { SectionLabel } from '@/components/ui/section-label'
import { DynamicForm } from '@/components/generation/DynamicForm'
import { GenerationStatus } from '@/components/generation/GenerationStatus'
import { ModelSetupWizard } from '@/components/panes/ModelSetupWizard'
import type { CanonicalEndpointDef } from '@/types'

export function GenerationPane(): React.JSX.Element {
  const [endpoint, setEndpoint] = React.useState<CanonicalEndpointDef | null>(null)
  const [validationErrors, setValidationErrors] = React.useState<Record<string, string>>({})
  const fieldsRef = React.useRef<FormFieldConfig[]>([])

  const filesByModelId = useModelStore((s) => s.filesByModelId)
  const anyModelReady = Object.values(filesByModelId).some((f) => f.isReady)

  const formValues = useGenerationStore((s) => s.formValues)
  const setFormValue = useGenerationStore((s) => s.setFormValue)
  const setFormValues = useGenerationStore((s) => s.setFormValues)
  const endpointKey = useGenerationStore((s) => s.endpointKey)
  const buildParams = useGenerationStore((s) => s.buildParams)
  const addGeneration = useGenerationStore((s) => s.addGeneration)

  const engineState = useEngineStore((s) => s.state)
  const engineCanGenerate = engineState === 'ready' || engineState === 'idle'

  const { activePhase, items: queueItems } = useQueueStore()
  const isGenerating = !!activePhase || queueItems.some((q) => q.status === 'processing')

  // Fetch the endpoint schema on mount / when endpoint key changes
  React.useEffect(() => {
    let cancelled = false
    window.api.getGenerationEndpointSchema(endpointKey).then((ep) => {
      if (!cancelled && ep) setEndpoint(ep)
    })
    return () => {
      cancelled = true
    }
  }, [endpointKey])

  const prompt = typeof formValues.prompt === 'string' ? formValues.prompt : ''
  const generateDisabled = !engineCanGenerate || !prompt.trim()

  // Callbacks for DynamicForm
  const handleFieldChange = React.useCallback(
    (key: string, value: unknown) => {
      setFormValue(key, value)
      setValidationErrors((prev) => {
        if (!prev[key]) return prev
        const next = { ...prev }
        delete next[key]
        return next
      })
    },
    [setFormValue]
  )

  const handleSetDefaults = React.useCallback(
    (defaults: Record<string, unknown>) => {
      setFormValues(defaults)
    },
    [setFormValues]
  )

  const handleFieldsChange = React.useCallback((fields: FormFieldConfig[]) => {
    fieldsRef.current = fields
  }, [])

  const handleSubmit = React.useCallback(async () => {
    // Validate
    const errors = validateFormValues(fieldsRef.current, formValues)
    if (Object.keys(errors).length > 0) {
      setValidationErrors(errors)
      return
    }

    const built = buildParams()
    if (!built.params.prompt?.trim()) return

    const genId = await window.api.submitGeneration(built)
    try {
      const gen = await window.api.timeline.get(genId)
      if (gen) addGeneration(gen)
    } catch {
      // ignore
    }
  }, [formValues, buildParams, addGeneration])

  if (!anyModelReady) {
    return (
      <div className="space-y-4">
        <ModelSetupWizard />
      </div>
    )
  }

  return (
    <div className="space-y-4">
      <ModelSelector />

      {/* Reference images */}
      <div className="space-y-2">
        <SectionLabel>Reference images</SectionLabel>
        <RefImageDropzone />
      </div>

      {/* Prompt */}
      <div className="space-y-2">
        <SectionLabel>Prompt</SectionLabel>
        <Textarea
          data-focus-prompt="true"
          placeholder="Describe what you want to generate…"
          value={prompt}
          onChange={(e) => setFormValue('prompt', e.target.value)}
          onKeyDown={(e) => {
            if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
              e.preventDefault()
              handleSubmit()
            }
          }}
          rows={3}
          className="resize-none text-sm"
        />
        {validationErrors.prompt && (
          <p className="text-xs text-destructive">{validationErrors.prompt}</p>
        )}
      </div>

      {/* Dynamic form — size, steps, guidance, etc. */}
      {endpoint ? (
        <DynamicForm
          endpoint={endpoint}
          values={formValues}
          validationErrors={validationErrors}
          onChange={handleFieldChange}
          onSetDefaults={handleSetDefaults}
          onFieldsChange={handleFieldsChange}
          disabled={false}
        />
      ) : (
        <div className="py-4 text-center text-sm text-muted-foreground">Loading schema…</div>
      )}

      {/* Generate button */}
      <Button
        type="button"
        size="lg"
        className="w-full"
        disabled={generateDisabled}
        onClick={handleSubmit}
      >
        {isGenerating ? (
          <>
            <Loader2 className="animate-spin" />
            Generating
          </>
        ) : (
          'Generate'
        )}
      </Button>

      {/* Generation status — model load, progress, pending items */}
      <GenerationStatus />
    </div>
  )
}

// src/renderer/components/panes/GenerationPane.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Icon } from '@iconify/vue'
import Button from 'primevue/button'
import InputText from 'primevue/inputtext'
import Textarea from 'primevue/textarea'
import Tag from 'primevue/tag'
import { useToast } from 'primevue/usetoast'

import PaneLayout from '@/components/panes/primitives/PaneLayout.vue'
import PaneBody from '@/components/panes/primitives/PaneBody.vue'
import PaneSection from '@/components/panes/primitives/PaneSection.vue'
import ModeToggle from '@/components/generation/ModeToggle.vue'
import ModelSelector from '@/components/generation/ModelSelector.vue'
import RefImageDropzone from '@/components/generation/RefImageDropzone.vue'
import DynamicForm from '@/components/generation/DynamicForm.vue'
import GenerationStatus from '@/components/generation/GenerationStatus.vue'

import { validateFormValues, type FormFieldConfig } from '@/lib/schema-to-form'
import { useGenerationStore } from '@/stores/generation'
import { useEngineStore } from '@/stores/engine'
import { useQueueStore } from '@/stores/queue'
import { useModelStore } from '@/stores/model'
import { useProviderStore } from '@/stores/provider'
import { useModelBrowsingStore } from '@/stores/model-browsing'
import { usePromptStore } from '@/stores/prompt'
import { useUIStore } from '@/stores/ui'
import type { CanonicalEndpointDef } from '@/types'

// ---------------------------------------------------------------------------
// Store access
// ---------------------------------------------------------------------------

const generationStore = useGenerationStore()
const engineStore = useEngineStore()
const queueStore = useQueueStore()
const modelStore = useModelStore()
const providerStore = useProviderStore()
const modelBrowsingStore = useModelBrowsingStore()
const promptStore = usePromptStore()
const uiStore = useUIStore()
const toast = useToast()

// ---------------------------------------------------------------------------
// Local state
// ---------------------------------------------------------------------------

const endpoint = ref<CanonicalEndpointDef | null>(null)
const validationErrors = ref<Record<string, string>>({})
const fieldsRef = ref<FormFieldConfig[]>([])
const showSavePromptForm = ref(false)
const savePromptTitle = ref('')
const savePromptPending = ref(false)

// ---------------------------------------------------------------------------
// Model availability check
// ---------------------------------------------------------------------------

const hasLocalModels = computed(() =>
  Object.values(modelStore.filesByModelId).some((f) => f.isReady)
)
const hasRemoteModels = computed(() =>
  Object.values(modelBrowsingStore.userModelsByProvider).some((models) => models.length > 0)
)
const hasAnyModels = computed(() => hasLocalModels.value || hasRemoteModels.value)

// ---------------------------------------------------------------------------
// Generation readiness
// ---------------------------------------------------------------------------

const prompt = computed(() => generationStore.prompt)
const requiresLocalEngine = computed(() => endpoint.value?.providerId === 'local')
const engineCanGenerate = computed(() => engineStore.status.state === 'ready' || engineStore.status.state === 'idle')
const generateDisabled = computed(
  () => !prompt.value.trim() || (requiresLocalEngine.value && !engineCanGenerate.value)
)

const isRemoteEndpoint = computed(() => endpoint.value?.executionMode === 'remote-async')
const isGenerating = computed(
  () => !!queueStore.activePhase || queueStore.items.some((q) => q.status === 'processing')
)

const showRefImages = computed(
  () => generationStore.generationMode === 'image-to-image' || generationStore.generationMode === 'image-to-video'
)

// ---------------------------------------------------------------------------
// Fetch endpoint schema on key change
// ---------------------------------------------------------------------------

watch(
  () => generationStore.endpointKey,
  async (key) => {
    const ep = await window.api.getGenerationEndpointSchema(key)
    if (ep) endpoint.value = ep
  },
  { immediate: true }
)

// ---------------------------------------------------------------------------
// DynamicForm callbacks
// ---------------------------------------------------------------------------

function handleFieldChange(key: string, value: unknown): void {
  generationStore.setFormValue(key, value)
  if (validationErrors.value[key]) {
    const next = { ...validationErrors.value }
    delete next[key]
    validationErrors.value = next
  }
}

function handleSetDefaults(defaults: Record<string, unknown>): void {
  generationStore.setFormValues(defaults)
}

function handleFieldsChange(fields: FormFieldConfig[]): void {
  fieldsRef.value = fields
}

// ---------------------------------------------------------------------------
// Submit
// ---------------------------------------------------------------------------

async function handleSubmit(): Promise<void> {
  const errors = validateFormValues(fieldsRef.value, generationStore.formValues)
  if (Object.keys(errors).length > 0) {
    validationErrors.value = errors
    return
  }

  const built = generationStore.buildParams()
  if (!built.params.prompt?.trim()) return

  const genId = await window.api.submitGeneration(built)
  try {
    const gen = await window.api.timeline.get(genId)
    if (gen) generationStore.addGeneration(gen)
  } catch {
    // ignore
  }
}

function openPromptEditor(): void {
  uiStore.openModal('prompt-editor')
}

function openSavePromptForm(): void {
  if (!prompt.value.trim()) return
  showSavePromptForm.value = true
  savePromptTitle.value = ''
}

function cancelSavePrompt(): void {
  showSavePromptForm.value = false
  savePromptTitle.value = ''
}

async function handleSavePrompt(): Promise<void> {
  if (!prompt.value.trim() || savePromptPending.value) return

  savePromptPending.value = true

  try {
    const created = await promptStore.createPrompt({
      text: prompt.value,
      title: savePromptTitle.value.trim() || undefined
    })

    cancelSavePrompt()
    toast.add({
      severity: 'success',
      summary: 'Prompt saved',
      detail: created.title ?? 'Saved to prompt library',
      life: 3000
    })
  } catch (error) {
    toast.add({
      severity: 'error',
      summary: 'Save failed',
      detail: error instanceof Error ? error.message : String(error),
      life: 3500
    })
  } finally {
    savePromptPending.value = false
  }
}

// ---------------------------------------------------------------------------
// API status (inline for remote endpoints)
// ---------------------------------------------------------------------------

const apiProvider = computed(() => {
  const pid = endpoint.value?.providerId
  if (!pid) return null
  return providerStore.providers.find((p) => p.providerId === pid) ?? null
})

const apiKeyPresent = computed(() => {
  const pid = endpoint.value?.providerId
  return pid ? (providerStore.hasApiKey[pid] ?? false) : false
})

const apiConnStatus = computed(() => {
  const pid = endpoint.value?.providerId
  return pid ? providerStore.connectionStatus[pid] : undefined
})
</script>

<template>
  <PaneLayout title="Generate">
    <PaneBody>
      <!-- No models available — prompt to set up -->
      <template v-if="!hasAnyModels">
        <div class="flex flex-col items-center gap-3 py-8 text-center">
          <Icon icon="lucide:download" class="size-8 text-muted" />
          <div>
            <p class="text-sm font-medium">No models available</p>
            <p class="mt-1 text-xs text-muted">
              Open the Model Manager to download a model or add an API provider.
            </p>
          </div>
        </div>
      </template>

      <!-- Main generation form -->
      <template v-else>
        <div class="space-y-4">
          <ModeToggle />
          <ModelSelector />

          <!-- Reference images -->
          <PaneSection v-if="showRefImages" title="Reference Images">
            <RefImageDropzone />
          </PaneSection>

          <!-- Prompt -->
          <PaneSection title="Prompt">
            <div class="relative">
              <Textarea
                data-focus-prompt="true"
                placeholder="Describe what you want to generate…"
                :model-value="prompt"
                rows="3"
                auto-resize
                class="w-full resize-none pr-24 text-sm"
                @update:model-value="(v: string) => generationStore.setFormValue('prompt', v)"
                @keydown.meta.enter.prevent="handleSubmit"
                @keydown.ctrl.enter.prevent="handleSubmit"
              />

              <div class="absolute right-1 top-1 flex items-center gap-1">
                <Button
                  v-tooltip.top="'Save prompt to library'"
                  type="button"
                  text
                  plain
                  severity="secondary"
                  size="small"
                  :disabled="!prompt.trim()"
                  @click="openSavePromptForm"
                >
                  <Icon icon="lucide:bookmark-plus" class="size-3.5" />
                </Button>
                <Button
                  v-tooltip.top="'Open prompt editor'"
                  type="button"
                  text
                  plain
                  severity="secondary"
                  size="small"
                  @click="openPromptEditor"
                >
                  <Icon icon="lucide:pen-square" class="size-3.5" />
                </Button>
              </div>
            </div>

            <p v-if="validationErrors.prompt" class="mt-1 text-xs text-red-400">
              {{ validationErrors.prompt }}
            </p>

            <div v-if="showSavePromptForm" class="mt-3 rounded-lg border border-default bg-elevated p-3">
              <div class="flex flex-col gap-3 sm:flex-row sm:items-end">
                <div class="flex-1">
                  <label class="mb-1 block text-xs font-medium uppercase tracking-wide text-muted">
                    Title
                  </label>
                  <InputText
                    v-model="savePromptTitle"
                    class="w-full"
                    maxlength="120"
                    placeholder="Optional title"
                    @keydown.enter.prevent="handleSavePrompt"
                  />
                </div>

                <div class="flex items-center gap-2">
                  <Button
                    type="button"
                    label="Cancel"
                    severity="secondary"
                    outlined
                    size="small"
                    :disabled="savePromptPending"
                    @click="cancelSavePrompt"
                  />
                  <Button
                    type="button"
                    label="Save"
                    size="small"
                    :loading="savePromptPending"
                    :disabled="!prompt.trim()"
                    @click="handleSavePrompt"
                  />
                </div>
              </div>
            </div>
          </PaneSection>

          <!-- Dynamic form fields -->
          <DynamicForm
            v-if="endpoint"
            :endpoint="endpoint"
            :values="generationStore.formValues"
            :validation-errors="validationErrors"
            @change="handleFieldChange"
            @set-defaults="handleSetDefaults"
            @fields-change="handleFieldsChange"
          />
          <div v-else class="py-4 text-center text-sm text-muted">Loading schema…</div>

          <!-- Generate button -->
          <Button
            type="button"
            class="w-full"
            :disabled="generateDisabled"
            @click="handleSubmit"
          >
            <template v-if="isGenerating">
              <Icon icon="lucide:loader-2" class="size-4 animate-spin" />
              Generating
            </template>
            <template v-else>Generate</template>
          </Button>

          <!-- Status: local engine or API mode -->
          <template v-if="isRemoteEndpoint && endpoint?.providerId">
            <div class="rounded-lg border border-default bg-elevated p-3">
              <div class="flex items-center gap-2">
                <Icon icon="lucide:wifi" class="size-3.5 text-muted shrink-0" />
                <span class="text-xs text-muted flex-1">
                  {{ isGenerating
                    ? `Sending to ${apiProvider?.displayName ?? endpoint.providerId}…`
                    : `API Mode — ${apiProvider?.displayName ?? endpoint.providerId}` }}
                </span>
                <Tag
                  v-if="apiConnStatus?.status === 'success'"
                  severity="success"
                  class="text-[10px]"
                  value="Connected"
                />
                <Tag
                  v-if="apiConnStatus?.status === 'error'"
                  severity="danger"
                  class="text-[10px]"
                  :value="'API Error'"
                  v-tooltip.top="apiConnStatus.message"
                />
                <Tag
                  v-if="!apiKeyPresent"
                  severity="warn"
                  class="text-[10px]"
                  value="No API Key"
                />
              </div>
            </div>
          </template>
          <GenerationStatus v-else />
        </div>
      </template>
    </PaneBody>
  </PaneLayout>
</template>
