// src/renderer/components/library/canvas/CanvasViewer.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch, watchEffect } from 'vue'

import { draw } from '@/lib/canvas-draw'
import type { ZoomLevel } from '@/stores/ui'
import { useRemovalStore } from '@/stores/removal'
import { useTransformStore } from '@/stores/transform'
import type { MediaRecord } from '@/types'

const props = withDefaults(
  defineProps<{
    media: MediaRecord | null
    zoom?: ZoomLevel
  }>(),
  {
    zoom: 'fit'
  }
)

const removalStore = useRemovalStore()
const transformStore = useTransformStore()

const containerRef = ref<HTMLDivElement | null>(null)
const canvasRef = ref<HTMLCanvasElement | null>(null)
const imageRef = ref<HTMLImageElement | null>(null)
const isPannable = ref(false)
const dragging = ref(false)

const panOffset = { x: 0, y: 0 }
const dragStart = { x: 0, y: 0 }
const dragStartOffset = { x: 0, y: 0 }
let isDragging = false
let resizeObserver: ResizeObserver | null = null

const imageUrl = computed(() => props.media?.working_file_path ?? props.media?.file_path ?? null)

const transforms = computed(() =>
  props.media ? transformStore.getTransformsFor(props.media.id) : null
)

const isCropTarget = computed(
  () => transformStore.cropMode && transformStore.cropMediaId === props.media?.id
)

const isPaintTarget = computed(
  () => removalStore.paintMode && removalStore.paintMediaId === props.media?.id
)

const cursor = computed(() => {
  if (isCropTarget.value) return 'crosshair'
  if (isPaintTarget.value) return 'default'
  if (!isPannable.value) return 'default'
  return dragging.value ? 'grabbing' : 'grab'
})

// Load transforms when media changes
watch(
  () => props.media,
  (media) => {
    if (media?.id && media.media_type === 'image') {
      void transformStore.loadTransforms(media.id)
    }
  },
  { immediate: true }
)

function resetPan(): void {
  panOffset.x = 0
  panOffset.y = 0
}

function redraw(): void {
  const container = containerRef.value
  const canvas = canvasRef.value
  if (!container || !canvas) return

  const ctx = canvas.getContext('2d')
  if (!ctx) return

  const rect = container.getBoundingClientRect()
  const result = draw({
    ctx,
    width: rect.width,
    height: rect.height,
    img: imageRef.value,
    media: props.media,
    zoom: props.zoom,
    panOffset,
    transforms: transforms.value,
    suppressCrop: isCropTarget.value
  })

  panOffset.x = result.clampedPanOffset.x
  panOffset.y = result.clampedPanOffset.y
  isPannable.value = !isCropTarget.value && !isPaintTarget.value && result.pannable

  // Report image rect to transform store for crop overlay positioning
  if (isCropTarget.value && result.imageRect) {
    transformStore.setCropOverlay({
      containerWidth: rect.width,
      containerHeight: rect.height,
      imageX: result.imageRect.x,
      imageY: result.imageRect.y,
      imageWidth: result.imageRect.w,
      imageHeight: result.imageRect.h
    })
  } else {
    transformStore.setCropOverlay(null)
  }

  // Report image rect to removal store for mask overlay positioning
  if (removalStore.paintMode && result.imageRect) {
    removalStore.setMaskOverlay({
      containerWidth: rect.width,
      containerHeight: rect.height,
      imageX: result.imageRect.x,
      imageY: result.imageRect.y,
      imageWidth: result.imageRect.w,
      imageHeight: result.imageRect.h
    })
  } else if (!removalStore.paintMode) {
    removalStore.setMaskOverlay(null)
  }
}

function resizeCanvas(): void {
  const container = containerRef.value
  const canvas = canvasRef.value
  if (!container || !canvas) return

  const ctx = canvas.getContext('2d')
  if (!ctx) return

  const rect = container.getBoundingClientRect()
  const dpr = window.devicePixelRatio || 1
  canvas.width = Math.max(1, Math.floor(rect.width * dpr))
  canvas.height = Math.max(1, Math.floor(rect.height * dpr))
  canvas.style.width = `${rect.width}px`
  canvas.style.height = `${rect.height}px`
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0)
  redraw()
}

function onMouseDown(event: MouseEvent): void {
  if (isCropTarget.value || isPaintTarget.value || !isPannable.value) return

  isDragging = true
  dragging.value = true
  dragStart.x = event.clientX
  dragStart.y = event.clientY
  dragStartOffset.x = panOffset.x
  dragStartOffset.y = panOffset.y
}

function onMouseMove(event: MouseEvent): void {
  if (!isDragging || isCropTarget.value) return

  panOffset.x = dragStartOffset.x + (event.clientX - dragStart.x)
  panOffset.y = dragStartOffset.y + (event.clientY - dragStart.y)
  redraw()
}

function onMouseUp(): void {
  isDragging = false
  dragging.value = false
}

// Reset pan when zoom, transforms, crop mode, paint mode, or image changes
watch(
  [() => props.zoom, imageUrl, transforms, isCropTarget, isPaintTarget],
  () => {
    resetPan()
    redraw()
  }
)

// Redraw when transforms change (rotation, flip, crop applied)
watch(transforms, () => {
  redraw()
})

watchEffect((onCleanup) => {
  const url = imageUrl.value
  let cancelled = false

  async function loadImage(): Promise<void> {
    if (!url) {
      imageRef.value = null
      redraw()
      return
    }

    try {
      const image = new Image()
      image.src = url
      await image.decode()

      if (cancelled) return

      imageRef.value = image
      redraw()
    } catch {
      if (cancelled) return

      imageRef.value = null
      redraw()
    }
  }

  void loadImage()

  onCleanup(() => {
    cancelled = true
  })
})

onMounted(() => {
  resizeCanvas()

  if (containerRef.value) {
    resizeObserver = new ResizeObserver(() => {
      resizeCanvas()
    })

    resizeObserver.observe(containerRef.value)
  }
})

onBeforeUnmount(() => {
  resizeObserver?.disconnect()
  resizeObserver = null
  transformStore.setCropOverlay(null)
  removalStore.setMaskOverlay(null)
})
</script>

<template>
  <div
    ref="containerRef"
    class="h-full w-full"
    :style="{ cursor }"
    @mousedown="onMouseDown"
    @mousemove="onMouseMove"
    @mouseup="onMouseUp"
    @mouseleave="onMouseUp"
  >
    <canvas ref="canvasRef" class="block h-full w-full" />
  </div>
</template>

// src/renderer/components/library/canvas/CanvasViewer.tsx
import * as React from 'react'

import { normalizeCrop } from '@/lib/transform-math'
import { useTransformStore } from '@/stores/transform-store'
import { useRemovalStore } from '@/stores/removal-store'
import type { ZoomLevel } from '@/stores/ui-store'
import type { ImageTransforms, MediaRecord } from '@/types'

async function loadImage(url: string): Promise<HTMLImageElement> {
  const img = new Image()
  img.src = url
  await img.decode()
  return img
}

interface DrawOptions {
  ctx: CanvasRenderingContext2D
  width: number
  height: number
  img: HTMLImageElement | null
  media: MediaRecord | null
  zoom: ZoomLevel
  panOffset: { x: number; y: number }
  transforms: ImageTransforms | null
  suppressCrop: boolean
}

interface DrawResult {
  imageRect: { x: number; y: number; w: number; h: number } | null
  pannable: boolean
}

function getRotatedDimensions(
  width: number,
  height: number,
  rotation: ImageTransforms['rotation']
): { width: number; height: number } {
  if (rotation === 90 || rotation === 270) {
    return { width: height, height: width }
  }

  return { width, height }
}

function draw({
  ctx,
  width,
  height,
  img,
  media,
  zoom,
  panOffset,
  transforms,
  suppressCrop
}: DrawOptions): DrawResult {
  ctx.clearRect(0, 0, width, height)
  ctx.fillStyle = 'rgba(0,0,0,0)'
  ctx.fillRect(0, 0, width, height)

  if (!img || !media) {
    ctx.fillStyle = 'rgba(255,255,255,0.06)'
    ctx.fillRect(0, 0, width, height)
    ctx.fillStyle = 'rgba(255,255,255,0.65)'
    ctx.font = '13px Inter, ui-sans-serif, system-ui, sans-serif'
    ctx.fillText(media ? media.file_name : 'No selection', 20, 34)
    return { imageRect: null, pannable: false }
  }

  const iw = img.naturalWidth || img.width
  const ih = img.naturalHeight || img.height
  if (!iw || !ih) return { imageRect: null, pannable: false }

  const active = transforms ?? {
    rotation: 0,
    flip_h: false,
    flip_v: false,
    crop: null,
    aspect_ratio: null
  }

  const rotated = getRotatedDimensions(iw, ih, active.rotation)

  const transformedCanvas = document.createElement('canvas')
  transformedCanvas.width = Math.max(1, Math.round(rotated.width))
  transformedCanvas.height = Math.max(1, Math.round(rotated.height))

  const transformedCtx = transformedCanvas.getContext('2d')
  if (!transformedCtx) {
    return { imageRect: null, pannable: false }
  }

  transformedCtx.imageSmoothingEnabled = true
  transformedCtx.imageSmoothingQuality = 'high'
  transformedCtx.translate(rotated.width / 2, rotated.height / 2)
  transformedCtx.rotate((active.rotation * Math.PI) / 180)
  transformedCtx.scale(active.flip_h ? -1 : 1, active.flip_v ? -1 : 1)
  transformedCtx.drawImage(img, -iw / 2, -ih / 2, iw, ih)

  const crop = suppressCrop ? null : normalizeCrop(active.crop)

  const sx = crop ? Math.floor(crop.x * rotated.width) : 0
  const sy = crop ? Math.floor(crop.y * rotated.height) : 0
  const sw = crop
    ? Math.max(1, Math.min(rotated.width - sx, Math.round(crop.w * rotated.width)))
    : rotated.width
  const sh = crop
    ? Math.max(1, Math.min(rotated.height - sy, Math.round(crop.h * rotated.height)))
    : rotated.height

  const effectiveWidth = sw
  const effectiveHeight = sh

  const scale = zoom === 'actual' ? 1.0 : Math.min(width / effectiveWidth, height / effectiveHeight)
  const dw = effectiveWidth * scale
  const dh = effectiveHeight * scale

  const overflowX = Math.max(0, dw - width)
  const overflowY = Math.max(0, dh - height)
  const clampedPanX =
    overflowX > 0 ? Math.max(-overflowX / 2, Math.min(overflowX / 2, panOffset.x)) : 0
  const clampedPanY =
    overflowY > 0 ? Math.max(-overflowY / 2, Math.min(overflowY / 2, panOffset.y)) : 0

  const dx = (width - dw) / 2 + clampedPanX
  const dy = (height - dh) / 2 + clampedPanY

  ctx.imageSmoothingEnabled = true
  ctx.imageSmoothingQuality = 'high'
  ctx.drawImage(transformedCanvas, sx, sy, sw, sh, dx, dy, dw, dh)

  return {
    imageRect: { x: dx, y: dy, w: dw, h: dh },
    pannable: dw > width || dh > height
  }
}

interface CanvasViewerProps {
  media: MediaRecord | null
  zoom?: ZoomLevel
}

export function CanvasViewer({ media, zoom = 'fit' }: CanvasViewerProps): React.JSX.Element {
  const containerRef = React.useRef<HTMLDivElement | null>(null)
  const canvasRef = React.useRef<HTMLCanvasElement | null>(null)
  const imageRef = React.useRef<HTMLImageElement | null>(null)

  const transforms = useTransformStore((s) => (media ? s.transforms[media.id] ?? null : null))
  const loadTransforms = useTransformStore((s) => s.loadTransforms)
  const cropMode = useTransformStore((s) => s.cropMode)
  const cropMediaId = useTransformStore((s) => s.cropMediaId)
  const setCropOverlay = useTransformStore((s) => s.setCropOverlay)

  const paintMode = useRemovalStore((s) => s.paintMode)
  const paintMediaId = useRemovalStore((s) => s.paintMediaId)
  const setMaskOverlay = useRemovalStore((s) => s.setMaskOverlay)

  // Pan state (local refs, not in store)
  const panOffset = React.useRef({ x: 0, y: 0 })
  const isDragging = React.useRef(false)
  const dragStart = React.useRef({ x: 0, y: 0 })
  const dragStartOffset = React.useRef({ x: 0, y: 0 })

  // Track whether image overflows viewport for cursor styling
  const [isPannable, setIsPannable] = React.useState(false)
  const [dragging, setDragging] = React.useState(false)

  const isCropTarget = cropMode && cropMediaId === media?.id
  const isPaintTarget = paintMode && paintMediaId === media?.id

  // Derive the image URL: working_file_path (active upscale variant) or original file_path
  const imageUrl = media?.working_file_path ?? media?.file_path ?? null

  React.useEffect(() => {
    if (media?.id && media.media_type === 'image') {
      void loadTransforms(media.id)
    }
  }, [loadTransforms, media?.id, media?.media_type])

  // Reset pan when zoom, transforms, crop mode, or image changes
  React.useEffect(() => {
    panOffset.current = { x: 0, y: 0 }
  }, [zoom, imageUrl, transforms, isCropTarget, isPaintTarget])

  // Helper to redraw
  const redraw = React.useCallback(() => {
    const container = containerRef.current
    const canvas = canvasRef.current
    if (!container || !canvas) return

    const ctx = canvas.getContext('2d')
    if (!ctx) return

    const rect = container.getBoundingClientRect()
    const result = draw({
      ctx,
      width: rect.width,
      height: rect.height,
      img: imageRef.current,
      media,
      zoom,
      panOffset: panOffset.current,
      transforms,
      suppressCrop: isCropTarget
    })

    setIsPannable(!isCropTarget && result.pannable)

    if (isCropTarget && result.imageRect) {
      setCropOverlay({
        containerWidth: rect.width,
        containerHeight: rect.height,
        imageX: result.imageRect.x,
        imageY: result.imageRect.y,
        imageWidth: result.imageRect.w,
        imageHeight: result.imageRect.h
      })
    } else {
      setCropOverlay(null)
    }

    if (isPaintTarget && result.imageRect) {
      setMaskOverlay({
        containerWidth: rect.width,
        containerHeight: rect.height,
        imageX: result.imageRect.x,
        imageY: result.imageRect.y,
        imageWidth: result.imageRect.w,
        imageHeight: result.imageRect.h
      })
    } else {
      setMaskOverlay(null)
    }
  }, [isCropTarget, isPaintTarget, media, setCropOverlay, setMaskOverlay, transforms, zoom])

  // ResizeObserver
  React.useEffect(() => {
    const container = containerRef.current
    const canvas = canvasRef.current
    if (!container || !canvas) return

    const ctx = canvas.getContext('2d')
    if (!ctx) return

    const ro = new ResizeObserver(() => {
      const rect = container.getBoundingClientRect()
      const dpr = window.devicePixelRatio || 1
      canvas.width = Math.max(1, Math.floor(rect.width * dpr))
      canvas.height = Math.max(1, Math.floor(rect.height * dpr))
      canvas.style.width = `${rect.width}px`
      canvas.style.height = `${rect.height}px`
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0)
      redraw()
    })

    ro.observe(container)
    return () => ro.disconnect()
  }, [redraw])

  // Load image
  React.useEffect(() => {
    let cancelled = false

    const run = async (): Promise<void> => {
      const container = containerRef.current
      const canvas = canvasRef.current
      if (!container || !canvas) return

      if (!imageUrl) {
        imageRef.current = null
        redraw()
        return
      }

      try {
        const img = await loadImage(imageUrl)
        if (cancelled) return
        imageRef.current = img
        redraw()
      } catch {
        if (cancelled) return
        imageRef.current = null
        redraw()
      }
    }

    void run()
    return () => {
      cancelled = true
    }
  }, [imageUrl, redraw])

  // Redraw on state changes.
  React.useEffect(() => {
    redraw()
  }, [redraw])

  // Pan mouse handlers
  const onMouseDown = React.useCallback(
    (e: React.MouseEvent) => {
      if (!isPannable || isCropTarget || isPaintTarget) return
      isDragging.current = true
      dragStart.current = { x: e.clientX, y: e.clientY }
      dragStartOffset.current = { ...panOffset.current }
      setDragging(true)
    },
    [isCropTarget, isPaintTarget, isPannable]
  )

  const onMouseMove = React.useCallback(
    (e: React.MouseEvent) => {
      if (!isDragging.current || isCropTarget || isPaintTarget) return
      const dx = e.clientX - dragStart.current.x
      const dy = e.clientY - dragStart.current.y
      panOffset.current = {
        x: dragStartOffset.current.x + dx,
        y: dragStartOffset.current.y + dy
      }
      redraw()
    },
    [isCropTarget, isPaintTarget, redraw]
  )

  const onMouseUp = React.useCallback(() => {
    isDragging.current = false
    setDragging(false)
  }, [])

  React.useEffect(() => {
    return () => {
      setCropOverlay(null)
      setMaskOverlay(null)
    }
  }, [setCropOverlay, setMaskOverlay])

  const cursor = isCropTarget ? 'crosshair' : isPannable && !isPaintTarget ? (dragging ? 'grabbing' : 'grab') : 'default'

  return (
    <div
      ref={containerRef}
      className="h-full w-full"
      style={{ cursor }}
      onMouseDown={onMouseDown}
      onMouseMove={onMouseMove}
      onMouseUp={onMouseUp}
      onMouseLeave={onMouseUp}
    >
      <canvas ref={canvasRef} className="block h-full w-full" />
    </div>
  )
}
