// src/renderer/components/modals/GenerationDetailModal.tsx
import * as React from 'react'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from '@/components/ui/dialog'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Separator } from '@/components/ui/separator'
import { useGenerationStore } from '@/stores/generation-store'
import { useUIStore } from '@/stores/ui-store'
import type { GenerationInput, GenerationRecord } from '@/types'

export function GenerationDetailModal(): React.JSX.Element {
  const activeModals = useUIStore((s) => s.activeModals)
  const closeModal = useUIStore((s) => s.closeModal)
  const setLeftPanelTab = useUIStore((s) => s.setLeftPanelTab)

  const detailGenerationId = useGenerationStore((s) => s.detailGenerationId)
  const setDetailGenerationId = useGenerationStore((s) => s.setDetailGenerationId)
  const setGenerations = useGenerationStore((s) => s.setGenerations)
  const reloadFromGeneration = useGenerationStore((s) => s.reloadFromGeneration)

  const open = activeModals.includes('generation-detail')

  const [gen, setGen] = React.useState<GenerationRecord | null>(null)
  const [inputs, setInputs] = React.useState<GenerationInput[]>([])
  const [outputThumb, setOutputThumb] = React.useState<string | null>(null)

  React.useEffect(() => {
    if (!open || !detailGenerationId) {
      setGen(null)
      setInputs([])
      setOutputThumb(null)
      return
    }

    void window.api.timeline.get(detailGenerationId).then(setGen).catch(() => setGen(null))
    void window.api.timeline
      .getGenerationInputs(detailGenerationId)
      .then(setInputs)
      .catch(() => setInputs([]))
    void window.api.timeline
      .getThumbnail(detailGenerationId)
      .then(setOutputThumb)
      .catch(() => setOutputThumb(null))
  }, [open, detailGenerationId])

  const close = React.useCallback(() => {
    closeModal('generation-detail')
    setDetailGenerationId(null)
  }, [closeModal, setDetailGenerationId])

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        if (!next) close()
      }}
    >
      <DialogContent className="sm:max-w-3xl">
        <DialogHeader>
          <DialogTitle>
            {gen ? `Generation #${gen.number}` : 'Generation'}
          </DialogTitle>
          <DialogDescription>
            {gen?.created_at ? gen.created_at : '—'}
          </DialogDescription>
        </DialogHeader>

        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <div className="space-y-3">
            <div className="text-xs font-medium text-muted-foreground">Output</div>
            <div className="aspect-square w-full overflow-hidden rounded-md border bg-muted">
              {outputThumb ? (
                <img
                  src={outputThumb}
                  alt="Generation output"
                  className="h-full w-full object-cover"
                  draggable={false}
                />
              ) : (
                <div className="flex h-full w-full items-center justify-center text-xs text-muted-foreground">
                  —
                </div>
              )}
            </div>

            <div className="text-xs font-medium text-muted-foreground">Reference images</div>
            {inputs.length === 0 ? (
              <div className="text-xs text-muted-foreground">—</div>
            ) : (
              <div className="flex items-center gap-2 overflow-x-auto">
                {inputs.map((input) => (
                  <div
                    key={input.id}
                    className="relative size-12 overflow-hidden rounded-md border bg-muted"
                    title={input.original_filename ?? ''}
                  >
                    <img
                      src={input.thumb_path}
                      alt={input.original_filename ?? 'Reference'}
                      className="absolute inset-0 h-full w-full object-cover"
                      draggable={false}
                    />
                  </div>
                ))}
                <Badge variant="outline">{inputs.length}</Badge>
              </div>
            )}
          </div>

          <div className="space-y-3">
            <div className="text-xs font-medium text-muted-foreground">Prompt</div>
            <ScrollArea className="h-32 rounded-md border bg-background">
              <div className="p-2 text-sm">{gen?.prompt ?? '—'}</div>
            </ScrollArea>

            <Separator />

            <div className="text-xs font-medium text-muted-foreground">Parameters</div>
            <div className="space-y-1 text-xs text-muted-foreground">
              <div>
                Provider: <span className="text-foreground">{gen?.provider ?? '—'}</span>
              </div>
              <div>
                Model: <span className="text-foreground">{gen?.model_file ?? '—'}</span>
              </div>
              <div>
                Resolution:{' '}
                <span className="text-foreground">
                  {gen?.width ?? '—'} × {gen?.height ?? '—'}
                </span>
              </div>
              <div>
                Seed: <span className="text-foreground">{gen?.seed ?? '—'}</span>
              </div>
              <div>
                Steps: <span className="text-foreground">{gen?.steps ?? '—'}</span>
              </div>
              <div>
                Guidance: <span className="text-foreground">{gen?.guidance ?? '—'}</span>
              </div>
              {gen?.total_time_ms ? (
                <div>
                  Time:{' '}
                  <span className="text-foreground">
                    {(gen.total_time_ms / 1000).toFixed(1)}s
                  </span>
                </div>
              ) : null}
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button
            type="button"
            variant="outline"
            disabled={!gen}
            onClick={async () => {
              if (!gen) return
              setLeftPanelTab('generation')
              await reloadFromGeneration(gen.id)
              close()
            }}
          >
            Reload Settings
          </Button>
          <Button
            type="button"
            variant="destructive"
            disabled={!detailGenerationId}
            onClick={async () => {
              if (!detailGenerationId) return
              await window.api.timeline.remove(detailGenerationId)
              const { generations } = await window.api.timeline.getAll()
              setGenerations(generations)
              close()
            }}
          >
            Remove from Timeline
          </Button>
          <Button type="button" variant="secondary" onClick={close}>
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// src/renderer/components/modals/GenerationDetailModal.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import Button from 'primevue/button'
import Dialog from 'primevue/dialog'
import Tag from 'primevue/tag'

import ImagePreviewModal from '@/components/modals/ImagePreviewModal.vue'
import { useGenerationStore } from '@/stores/generation'
import { useUIStore } from '@/stores/ui'
import type { GenerationInput, GenerationRecord } from '@/types'

const uiStore = useUIStore()
const generationStore = useGenerationStore()

// ---------------------------------------------------------------------------
// Visibility
// ---------------------------------------------------------------------------

const open = computed({
  get: () => uiStore.activeModals.includes('generation-detail'),
  set: (val: boolean) => {
    if (!val) close()
  }
})

// ---------------------------------------------------------------------------
// Data loading
// ---------------------------------------------------------------------------

const gen = ref<GenerationRecord | null>(null)
const inputs = ref<GenerationInput[]>([])
const outputThumb = ref<string | null>(null)

watch(
  [open, () => generationStore.detailGenerationId],
  async ([isOpen, genId]) => {
    if (!isOpen || !genId) {
      gen.value = null
      inputs.value = []
      outputThumb.value = null
      return
    }

    const [record, genInputs, thumb] = await Promise.all([
      window.api.timeline.get(genId).catch(() => null),
      window.api.timeline.getGenerationInputs(genId).catch(() => [] as GenerationInput[]),
      window.api.timeline.getThumbnail(genId).catch(() => null)
    ])

    gen.value = record
    inputs.value = genInputs
    outputThumb.value = thumb
  },
  { immediate: true }
)

// ---------------------------------------------------------------------------
// Parameter rows — reusable pattern from GenerationInfoPane
// ---------------------------------------------------------------------------

interface InfoRow {
  label: string
  value: string | number
}

const paramRows = computed<InfoRow[]>(() => {
  const g = gen.value
  if (!g) return []

  const rows: InfoRow[] = [
    { label: 'Provider', value: g.provider ?? '—' },
    { label: 'Model', value: g.model_file ?? '—' },
    { label: 'Resolution', value: g.width && g.height ? `${g.width} × ${g.height}` : '—' },
    { label: 'Seed', value: g.seed ?? '—' },
    { label: 'Steps', value: g.steps ?? '—' },
    { label: 'Guidance', value: g.guidance ?? '—' }
  ]

  if (g.total_time_ms) {
    rows.push({ label: 'Time', value: `${(g.total_time_ms / 1000).toFixed(1)}s` })
  }

  return rows
})

// ---------------------------------------------------------------------------
// Image preview modal
// ---------------------------------------------------------------------------

const previewOpen = ref(false)
const previewSrc = ref<string | null>(null)

function openPreview(src: string): void {
  previewSrc.value = src
  previewOpen.value = true
}

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

function close(): void {
  uiStore.closeModal('generation-detail')
  generationStore.setDetailGenerationId(null)
}

async function reloadSettings(): Promise<void> {
  if (!gen.value) return
  uiStore.setLeftPanelTab('generation')
  await generationStore.reloadFromGeneration(gen.value.id)
  close()
}

async function removeFromTimeline(): Promise<void> {
  if (!generationStore.detailGenerationId) return
  await window.api.timeline.remove(generationStore.detailGenerationId)
  await generationStore.loadTimeline()
  close()
}
</script>

<template>
  <Dialog
    v-model:visible="open"
    :header="gen ? `Generation #${gen.number}` : 'Generation'"
    modal
    :closable="true"
    :style="{ width: '48rem' }"
  >
    <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
      <!-- Left column: Output + Reference images -->
      <div class="space-y-4">
        <div>
          <div class="mb-1.5 text-xs font-medium text-muted">Output</div>
          <div
            class="aspect-square w-full overflow-hidden rounded-lg border border-default bg-surface-100/30"
            :class="{ 'cursor-pointer': outputThumb }"
            @click="outputThumb ? openPreview(outputThumb) : undefined"
          >
            <img
              v-if="outputThumb"
              :src="outputThumb"
              alt="Generation output"
              class="size-full object-cover"
              draggable="false"
            />
            <div v-else class="flex size-full items-center justify-center text-xs text-muted">
              —
            </div>
          </div>
        </div>

        <div>
          <div class="mb-1.5 text-xs font-medium text-muted">Reference Images</div>
          <div v-if="inputs.length === 0" class="text-xs text-muted">None</div>
          <div v-else class="flex items-center gap-2 overflow-x-auto">
            <div
              v-for="input in inputs"
              :key="input.id"
              class="relative size-12 shrink-0 overflow-hidden rounded border border-default bg-surface-100/30"
              :title="input.original_filename ?? ''"
            >
              <img
                :src="input.thumb_path"
                :alt="input.original_filename ?? 'Reference'"
                class="absolute inset-0 size-full object-cover"
                draggable="false"
              />
            </div>
            <Tag :value="String(inputs.length)" severity="secondary" />
          </div>
        </div>
      </div>

      <!-- Right column: Prompt + Parameters -->
      <div class="space-y-4">
        <div>
          <div class="mb-1.5 text-xs font-medium text-muted">Prompt</div>
          <div
            class="max-h-32 overflow-y-auto rounded-lg border border-default bg-surface-100/30 p-2 text-sm"
          >
            {{ gen?.prompt ?? '—' }}
          </div>
        </div>

        <div>
          <div class="mb-1.5 text-xs font-medium text-muted">Parameters</div>
          <dl class="grid grid-cols-[auto_1fr] gap-x-3 gap-y-1 text-xs">
            <template v-for="row in paramRows" :key="row.label">
              <dt class="text-muted">{{ row.label }}</dt>
              <dd class="truncate">{{ row.value }}</dd>
            </template>
          </dl>
        </div>
      </div>
    </div>

    <template #footer>
      <div class="flex items-center justify-end gap-2">
        <Button
          label="Reload Settings"
          outlined
          severity="secondary"
          :disabled="!gen"
          @click="reloadSettings"
        />
        <Button
          label="Remove from Timeline"
          severity="danger"
          :disabled="!generationStore.detailGenerationId"
          @click="removeFromTimeline"
        />
      </div>
    </template>
  </Dialog>

  <ImagePreviewModal v-model:open="previewOpen" :src="previewSrc" alt="Generation output" />
</template>
