// src/renderer/components/modals/ProviderManagerModal.vue
<script setup lang="ts">
import { computed } from 'vue'
import Dialog from 'primevue/dialog'

import ProviderManager from '@/components/providers/ProviderManager.vue'
import { useUIStore } from '@/stores/ui'

const uiStore = useUIStore()

const open = computed({
  get: () => uiStore.activeModals.includes('providers'),
  set: (val: boolean) => {
    if (!val) uiStore.closeModal('providers')
  }
})
</script>

<template>
  <Dialog
    v-model:visible="open"
    header="Models"
    modal
    :style="{ width: '1100px', height: '82vh' }"
    :closable="true"
    content-class="!p-4 flex flex-col min-h-0 flex-1 overflow-hidden"
  >
    <p class="mb-4 text-sm text-muted">
      Manage API providers, local models, and available endpoints
    </p>
    <div class="min-h-0 flex-1 overflow-hidden">
      <ProviderManager />
    </div>
  </Dialog>
</template>

// src/renderer/components/modals/ProviderManagerModal.tsx
import * as React from 'react'

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle
} from '@/components/ui/dialog'
import { ProviderManager } from '@/components/providers/ProviderManager'
import { useUIStore } from '@/stores/ui-store'

export function ProviderManagerModal(): React.JSX.Element {
  const activeModals = useUIStore((s) => s.activeModals)
  const closeModal = useUIStore((s) => s.closeModal)

  const open = activeModals.includes('providers')

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        if (!next) closeModal('providers')
      }}
    >
      <DialogContent className="top-[4vh] h-[82vh] w-[96vw] sm:max-w-[1100px] translate-y-0 flex flex-col overflow-hidden p-4 data-[state=closed]:slide-out-to-top-[4vh] data-[state=open]:slide-in-from-top-[4vh] sm:rounded-xl">
        <DialogHeader>
          <DialogTitle>Models</DialogTitle>
          <DialogDescription>
            Manage API providers, local models, and available endpoints
          </DialogDescription>
        </DialogHeader>

        <div className="min-h-0 flex-1 overflow-hidden">
          <ProviderManager />
        </div>
      </DialogContent>
    </Dialog>
  )
}
