// src/renderer/components/modals/SettingsModal.tsx
import * as React from 'react'
import { FolderOpen, Settings as SettingsIcon } from 'lucide-react'

import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Separator } from '@/components/ui/separator'
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import { SectionHeader } from '@/components/ui/section-header'
import { cn } from '@/lib/utils'
import { useModelStore } from '@/stores/model-store'
import { useUIStore } from '@/stores/ui-store'
import { useUpscaleStore } from '@/stores/upscale-store'
import type { AppSettings, SettingsUpdate, UpscaleBackendPreference } from '@/types'

function FieldLabel({ children }: { children: React.ReactNode }): React.JSX.Element {
  return <div className="text-xs font-medium text-muted-foreground">{children}</div>
}

function Row({ children }: { children: React.ReactNode }): React.JSX.Element {
  return <div className="flex items-center gap-2">{children}</div>
}

function PathField({
  label,
  value,
  placeholder,
  onChange,
  onBrowse
}: {
  label: string
  value: string
  placeholder?: string
  onChange: (value: string) => void
  onBrowse: () => Promise<void>
}): React.JSX.Element {
  return (
    <div className="space-y-2">
      <FieldLabel>{label}</FieldLabel>
      <Row>
        <Input value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} />
        <Button type="button" variant="secondary" size="icon" onClick={() => void onBrowse()}>
          <FolderOpen />
        </Button>
      </Row>
    </div>
  )
}

function BoolField({
  label,
  value,
  onChange
}: {
  label: string
  value: boolean
  onChange: (value: boolean) => void
}): React.JSX.Element {
  return (
    <div className="space-y-2">
      <FieldLabel>{label}</FieldLabel>
      <ToggleGroup
        type="single"
        value={value ? 'on' : 'off'}
        onValueChange={(v) => {
          if (!v) return
          onChange(v === 'on')
        }}
        className="justify-start gap-1"
      >
        <ToggleGroupItem value="on" size="sm">
          On
        </ToggleGroupItem>
        <ToggleGroupItem value="off" size="sm">
          Off
        </ToggleGroupItem>
      </ToggleGroup>
    </div>
  )
}

function ChoiceField({
  label,
  value,
  options,
  onChange
}: {
  label: string
  value: string
  options: Array<{ value: string; label: string }>
  onChange: (value: string) => void
}): React.JSX.Element {
  return (
    <div className="space-y-2">
      <FieldLabel>{label}</FieldLabel>
      <ToggleGroup
        type="single"
        value={value}
        onValueChange={(next) => {
          if (!next) return
          onChange(next)
        }}
        className="justify-start gap-1"
      >
        {options.map((option) => (
          <ToggleGroupItem key={option.value} value={option.value} size="sm">
            {option.label}
          </ToggleGroupItem>
        ))}
      </ToggleGroup>
    </div>
  )
}

export function SettingsModal(): React.JSX.Element {
  const activeModals = useUIStore((s) => s.activeModals)
  const closeModal = useUIStore((s) => s.closeModal)
  const hydrateModels = useModelStore((s) => s.hydrate)
  const loadUpscaleModels = useUpscaleStore((s) => s.loadModels)

  const open = activeModals.includes('settings')

  const [loaded, setLoaded] = React.useState<AppSettings | null>(null)
  const [draft, setDraft] = React.useState<AppSettings | null>(null)
  const [saving, setSaving] = React.useState(false)
  const [error, setError] = React.useState<string | null>(null)

  const showEnginePath = import.meta.env.DEV

  React.useEffect(() => {
    if (!open) {
      setLoaded(null)
      setDraft(null)
      setSaving(false)
      setError(null)
      return
    }

    setSaving(false)
    setError(null)

    void window.api
      .getSettings()
      .then((s) => {
        setLoaded(s)
        setDraft(s)
      })
      .catch((err) => {
        setError(err instanceof Error ? err.message : String(err))
      })
  }, [open])

  const close = React.useCallback(() => {
    closeModal('settings')
  }, [closeModal])

  const update = <K extends keyof AppSettings>(key: K, value: AppSettings[K]): void => {
    setDraft((prev) => (prev ? { ...prev, [key]: value } : prev))
  }

  const browseFolder = async (title: string): Promise<string | null> => {
    const paths = await window.api.showOpenDialog({
      title,
      properties: ['openDirectory']
    })

    if (!paths || paths.length === 0) return null
    return paths[0] ?? null
  }

  const canSave = !!draft && !saving

  const onSave = async (): Promise<void> => {
    if (!draft) return
    setSaving(true)
    setError(null)

    try {
      const modelBasePathChanged = draft.model_base_path !== loaded?.model_base_path
      const upscaleBackendChanged = draft.upscale_backend !== loaded?.upscale_backend

      const updates: SettingsUpdate = {
        library_root: draft.library_root,
        engine_path: draft.engine_path,
        model_base_path: draft.model_base_path,
        upscale_backend: draft.upscale_backend,
        offload_to_cpu: draft.offload_to_cpu,
        flash_attn: draft.flash_attn,
        vae_on_cpu: draft.vae_on_cpu,
        llm_on_cpu: draft.llm_on_cpu,
        confirm_before_delete: draft.confirm_before_delete
      }

      await window.api.saveSettings(updates)

      if (modelBasePathChanged) {
        await hydrateModels()
      }

      if (upscaleBackendChanged) {
        await loadUpscaleModels()
      }

      close()
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err))
    } finally {
      setSaving(false)
    }
  }

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        if (!next) close()
      }}
    >
      <DialogContent className="sm:max-w-3xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <SettingsIcon className="size-5" />
            Settings
          </DialogTitle>
          <DialogDescription>
            Library location, model directory, and engine runtime flags.
          </DialogDescription>
        </DialogHeader>

        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <div className="space-y-4">
            <div className="space-y-3">
              <SectionHeader>
                PATHS
              </SectionHeader>

              <PathField
                label="Library root"
                value={draft?.library_root ?? ''}
                placeholder="C:\\Users\\...\\Distillery\\Library"
                onChange={(v) => update('library_root', v)}
                onBrowse={async () => {
                  const selected = await browseFolder('Choose library root')
                  if (selected) update('library_root', selected)
                }}
              />

              {showEnginePath ? (
                <PathField
                  label="Engine base path (dev)"
                  value={draft?.engine_path ?? ''}
                  placeholder="C:\\path\\to\\resources\\cn-engine\\win32\\vulkan"
                  onChange={(v) => update('engine_path', v)}
                  onBrowse={async () => {
                    const selected = await browseFolder('Choose cn-engine directory')
                    if (selected) update('engine_path', selected)
                  }}
                />
              ) : null}

              <PathField
                label="Model directory"
                value={draft?.model_base_path ?? ''}
                placeholder="C:\\Users\\...\\AppData\\Roaming\\distillery\\models"
                onChange={(v) => update('model_base_path', v)}
                onBrowse={async () => {
                  const selected = await browseFolder('Choose model directory')
                  if (selected) update('model_base_path', selected)
                }}
              />

              <ChoiceField
                label="Upscale backend"
                value={draft?.upscale_backend ?? 'auto'}
                options={[
                  { value: 'auto', label: 'Auto' },
                  { value: 'onnx', label: 'ONNX' },
                  { value: 'cn-engine', label: 'cn-engine' }
                ]}
                onChange={(value) => update('upscale_backend', value as UpscaleBackendPreference)}
              />
            </div>
          </div>

          <div className="space-y-4">
            <div className="space-y-3">
              <SectionHeader>
                ENGINE FLAGS
              </SectionHeader>

              <BoolField
                label="Offload to CPU"
                value={draft?.offload_to_cpu ?? true}
                onChange={(v) => update('offload_to_cpu', v)}
              />

              <BoolField
                label="Flash attention"
                value={draft?.flash_attn ?? true}
                onChange={(v) => update('flash_attn', v)}
              />

              <BoolField
                label="VAE on CPU"
                value={draft?.vae_on_cpu ?? false}
                onChange={(v) => update('vae_on_cpu', v)}
              />

              <BoolField
                label="LLM on CPU"
                value={draft?.llm_on_cpu ?? false}
                onChange={(v) => update('llm_on_cpu', v)}
              />
            </div>

            <Separator />

            <div className="space-y-3">
              <SectionHeader>
                BEHAVIOR
              </SectionHeader>

              <BoolField
                label="Confirm before delete"
                value={draft?.confirm_before_delete ?? true}
                onChange={(v) => update('confirm_before_delete', v)}
              />
            </div>

            <Separator />

            {error ? <div className={cn('text-sm', 'text-destructive')}>{error}</div> : null}

            {!loaded && open ? <div className="text-sm text-muted-foreground">Loading…</div> : null}
          </div>
        </div>

        <DialogFooter>
          <Button type="button" variant="secondary" onClick={close} disabled={saving}>
            Cancel
          </Button>
          <Button type="button" onClick={() => void onSave()} disabled={!canSave}>
            {saving ? 'Saving…' : 'Save'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// src/renderer/components/modals/SettingsModal.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Icon } from '@iconify/vue'
import Button from 'primevue/button'
import Dialog from 'primevue/dialog'
import InputText from 'primevue/inputtext'
import Divider from 'primevue/divider'
import SelectButton from 'primevue/selectbutton'

import { useModelStore } from '@/stores/model'
import { useUIStore } from '@/stores/ui'
import { useUpscaleStore } from '@/stores/upscale'
import type { AppSettings, SettingsUpdate, UpscaleBackendPreference } from '@/types'

const uiStore = useUIStore()
const modelStore = useModelStore()
const upscaleStore = useUpscaleStore()

const open = computed({
  get: () => uiStore.activeModals.includes('settings'),
  set: (val: boolean) => {
    if (!val) uiStore.closeModal('settings')
  }
})

const loaded = ref<AppSettings | null>(null)
const draft = ref<AppSettings | null>(null)
const saving = ref(false)
const error = ref<string | null>(null)

const showEnginePath = import.meta.env.DEV

const onOffOptions = [
  { label: 'On', value: true },
  { label: 'Off', value: false }
]

const upscaleBackendOptions = [
  { label: 'Auto', value: 'auto' },
  { label: 'ONNX', value: 'onnx' },
  { label: 'cn-engine', value: 'cn-engine' }
]

// Load settings when modal opens, reset when it closes
watch(open, async (isOpen) => {
  if (!isOpen) {
    loaded.value = null
    draft.value = null
    saving.value = false
    error.value = null
    return
  }

  saving.value = false
  error.value = null

  try {
    const s = await window.api.getSettings()
    loaded.value = s
    draft.value = { ...s }
  } catch (err) {
    error.value = err instanceof Error ? err.message : String(err)
  }
})

function update<K extends keyof AppSettings>(key: K, value: AppSettings[K]): void {
  if (draft.value) draft.value = { ...draft.value, [key]: value }
}

async function browseFolder(title: string, key: keyof AppSettings): Promise<void> {
  const paths = await window.api.showOpenDialog({ title, properties: ['openDirectory'] })
  if (paths && paths.length > 0 && paths[0]) {
    update(key, paths[0] as AppSettings[typeof key])
  }
}

async function onSave(): Promise<void> {
  if (!draft.value) return
  saving.value = true
  error.value = null

  try {
    const modelBasePathChanged = draft.value.model_base_path !== loaded.value?.model_base_path
    const upscaleBackendChanged = draft.value.upscale_backend !== loaded.value?.upscale_backend

    const updates: SettingsUpdate = {
      library_root: draft.value.library_root,
      engine_path: draft.value.engine_path,
      model_base_path: draft.value.model_base_path,
      upscale_backend: draft.value.upscale_backend,
      offload_to_cpu: draft.value.offload_to_cpu,
      flash_attn: draft.value.flash_attn,
      vae_on_cpu: draft.value.vae_on_cpu,
      llm_on_cpu: draft.value.llm_on_cpu,
      confirm_before_delete: draft.value.confirm_before_delete
    }

    await window.api.saveSettings(updates)

    if (modelBasePathChanged) await modelStore.hydrate()
    if (upscaleBackendChanged) await upscaleStore.loadModels()

    uiStore.closeModal('settings')
  } catch (err) {
    error.value = err instanceof Error ? err.message : String(err)
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <Dialog
    v-model:visible="open"
    modal
    :style="{ width: '720px' }"
    :closable="true"
  >
    <template #header>
      <div class="flex items-center gap-2">
        <Icon icon="lucide:settings" class="size-5" />
        <span class="font-semibold">Settings</span>
      </div>
    </template>

    <p class="mb-4 text-sm text-muted">
      Library location, model directory, and engine runtime flags.
    </p>

    <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
      <!-- Left column: Paths -->
      <div class="space-y-4">
        <div class="text-xs font-medium uppercase tracking-wide text-muted">Paths</div>

        <!-- Library root -->
        <div class="space-y-1.5">
          <label class="text-xs font-medium text-muted">Library root</label>
          <div class="flex items-center gap-2">
            <InputText
              :model-value="draft?.library_root ?? ''"
              placeholder="C:\Users\...\Distillery\Library"
              class="w-full"
              @update:model-value="update('library_root', String($event))"
            />
            <Button
              severity="secondary"
              size="small"
              @click="browseFolder('Choose library root', 'library_root')"
            >
              <Icon icon="lucide:folder-open" class="size-4" />
            </Button>
          </div>
        </div>

        <!-- Engine path (dev only) -->
        <div v-if="showEnginePath" class="space-y-1.5">
          <label class="text-xs font-medium text-muted">Engine base path (dev)</label>
          <div class="flex items-center gap-2">
            <InputText
              :model-value="draft?.engine_path ?? ''"
              placeholder="C:\path\to\resources\cn-engine\win32\vulkan"
              class="w-full"
              @update:model-value="update('engine_path', String($event))"
            />
            <Button
              severity="secondary"
              size="small"
              @click="browseFolder('Choose cn-engine directory', 'engine_path')"
            >
              <Icon icon="lucide:folder-open" class="size-4" />
            </Button>
          </div>
        </div>

        <!-- Model directory -->
        <div class="space-y-1.5">
          <label class="text-xs font-medium text-muted">Model directory</label>
          <div class="flex items-center gap-2">
            <InputText
              :model-value="draft?.model_base_path ?? ''"
              placeholder="C:\Users\...\AppData\Roaming\distillery\models"
              class="w-full"
              @update:model-value="update('model_base_path', String($event))"
            />
            <Button
              severity="secondary"
              size="small"
              @click="browseFolder('Choose model directory', 'model_base_path')"
            >
              <Icon icon="lucide:folder-open" class="size-4" />
            </Button>
          </div>
        </div>

        <!-- Upscale backend -->
        <div class="space-y-1.5">
          <label class="text-xs font-medium text-muted">Upscale backend</label>
          <SelectButton
            :model-value="draft?.upscale_backend ?? 'auto'"
            :options="upscaleBackendOptions"
            option-label="label"
            option-value="value"
            @update:model-value="update('upscale_backend', $event as UpscaleBackendPreference)"
          />
        </div>
      </div>

      <!-- Right column: Engine flags + behavior -->
      <div class="space-y-4">
        <div class="text-xs font-medium uppercase tracking-wide text-muted">Engine Flags</div>

        <div class="space-y-3">
          <div class="space-y-1.5">
            <label class="text-xs font-medium text-muted">Offload to CPU</label>
            <SelectButton
              :model-value="draft?.offload_to_cpu ?? true"
              :options="onOffOptions"
              option-label="label"
              option-value="value"
            @update:model-value="update('offload_to_cpu', Boolean($event))"
            />
          </div>

          <div class="space-y-1.5">
            <label class="text-xs font-medium text-muted">Flash attention</label>
            <SelectButton
              :model-value="draft?.flash_attn ?? true"
              :options="onOffOptions"
              option-label="label"
              option-value="value"
              @update:model-value="update('flash_attn', Boolean($event))"
            />
          </div>

          <div class="space-y-1.5">
            <label class="text-xs font-medium text-muted">VAE on CPU</label>
            <SelectButton
              :model-value="draft?.vae_on_cpu ?? false"
              :options="onOffOptions"
              option-label="label"
              option-value="value"
              @update:model-value="update('vae_on_cpu', Boolean($event))"
            />
          </div>

          <div class="space-y-1.5">
            <label class="text-xs font-medium text-muted">LLM on CPU</label>
            <SelectButton
              :model-value="draft?.llm_on_cpu ?? false"
              :options="onOffOptions"
              option-label="label"
              option-value="value"
              @update:model-value="update('llm_on_cpu', Boolean($event))"
            />
          </div>
        </div>

        <Divider />

        <div class="text-xs font-medium uppercase tracking-wide text-muted">Behavior</div>

        <div class="space-y-1.5">
          <label class="text-xs font-medium text-muted">Confirm before delete</label>
          <SelectButton
            :model-value="draft?.confirm_before_delete ?? true"
            :options="onOffOptions"
            option-label="label"
            option-value="value"
            @update:model-value="update('confirm_before_delete', Boolean($event))"
          />
        </div>

        <Divider />

        <div v-if="error" class="text-sm text-red-400">{{ error }}</div>
        <div v-if="!loaded && open" class="text-sm text-muted">Loading…</div>
      </div>
    </div>

    <template #footer>
      <Button
        severity="secondary"
        :disabled="saving"
        label="Cancel"
        @click="uiStore.closeModal('settings')"
      />
      <Button
        :disabled="!draft || saving"
        :loading="saving"
        :label="saving ? 'Saving…' : 'Save'"
        @click="onSave"
      />
    </template>
  </Dialog>
</template>
