// src/renderer/components/providers/LocalModelItem.tsx
import * as React from 'react'

import { Check, ChevronRight, Clock3, Download, Trash2, X } from 'lucide-react'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { Progress } from '@/components/ui/progress'
import { SectionHeader } from '@/components/ui/section-header'
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'
import { formatApproxSize, toPercent } from '@/lib/format'
import { cn } from '@/lib/utils'
import type { DownloadProgressEvent, ModelDefinition, ModelFileRef, QuantVariant } from '@/types'

interface LocalModelItemProps {
  model: ModelDefinition
  diffusionQuantId: string
  textEncoderQuantId: string
  isReady: boolean
  downloadedByPath: Record<string, boolean>
  downloadStatusByPath: Record<string, DownloadProgressEvent>
  onSelectQuant: (component: 'diffusion' | 'textEncoder', quantId: string) => void
  onDownload: (component: 'vae' | 'diffusion' | 'textEncoder', quantId?: string) => void
  onCancelDownload: (relativePath: string) => void
  onRemoveDownload: (relativePath: string) => void
}

function normalizeRelativePath(relativePath: string): string {
  return relativePath.replace(/\\+/g, '/')
}

function statusDot(ready: boolean): React.JSX.Element {
  return <span className={cn('size-2 shrink-0 rounded-full', ready ? 'bg-emerald-500' : 'bg-amber-500')} />
}

export function LocalModelItem({
  model,
  diffusionQuantId,
  textEncoderQuantId,
  isReady,
  downloadedByPath,
  downloadStatusByPath,
  onSelectQuant,
  onDownload,
  onCancelDownload,
  onRemoveDownload
}: LocalModelItemProps): React.JSX.Element {
  const [open, setOpen] = React.useState(!isReady)

  const normalizedDownloadedByPath = React.useMemo(
    () =>
      Object.fromEntries(
        Object.entries(downloadedByPath).map(([key, value]) => [normalizeRelativePath(key), value])
      ),
    [downloadedByPath]
  )

  const normalizedDownloadStatusByPath = React.useMemo(
    () =>
      Object.fromEntries(
        Object.entries(downloadStatusByPath).map(([key, value]) => [normalizeRelativePath(key), value])
      ),
    [downloadStatusByPath]
  )

  return (
    <Collapsible open={open} onOpenChange={setOpen} className="rounded-md border border-border/60">
      <CollapsibleTrigger asChild>
        <button
          type="button"
          className="flex w-full items-center gap-3 rounded-md px-3 py-2 text-left transition-colors hover:bg-muted/40"
        >
          <ChevronRight className={cn('size-4 shrink-0 text-muted-foreground transition-transform', open && 'rotate-90')} />

          <div className="min-w-0 flex-1">
            <div className="truncate text-sm font-medium">{model.name}</div>
            <div className="truncate text-xs text-muted-foreground">{model.description}</div>
          </div>

          <Badge
            className={cn(
              'gap-1 border',
              isReady
                ? 'border-emerald-500/25 bg-emerald-500/10 text-emerald-400'
                : 'border-amber-500/25 bg-amber-500/10 text-amber-400'
            )}
            variant="outline"
          >
            {isReady ? 'Ready' : 'Setup Required'}
            {statusDot(isReady)}
          </Badge>
        </button>
      </CollapsibleTrigger>

      <CollapsibleContent>
        <div className="px-3 pb-3 pt-1">
          <div className="grid grid-cols-2 gap-3">
            <QuantColumn
              title="Diffusion Model"
              quants={model.diffusion.quants}
              activeQuantId={diffusionQuantId}
              downloadedByPath={normalizedDownloadedByPath}
              downloadStatusByPath={normalizedDownloadStatusByPath}
              onSelectQuant={(quantId) => onSelectQuant('diffusion', quantId)}
              onDownload={(quantId) => onDownload('diffusion', quantId)}
              onCancel={onCancelDownload}
              onRemove={onRemoveDownload}
            />

            <QuantColumn
              title="Text Encoder"
              quants={model.textEncoder.quants}
              activeQuantId={textEncoderQuantId}
              downloadedByPath={normalizedDownloadedByPath}
              downloadStatusByPath={normalizedDownloadStatusByPath}
              onSelectQuant={(quantId) => onSelectQuant('textEncoder', quantId)}
              onDownload={(quantId) => onDownload('textEncoder', quantId)}
              onCancel={onCancelDownload}
              onRemove={onRemoveDownload}
            />
          </div>

          <VaeRow
            vae={model.vae}
            isDownloaded={!!normalizedDownloadedByPath[normalizeRelativePath(model.vae.file)]}
            downloadStatus={normalizedDownloadStatusByPath[normalizeRelativePath(model.vae.file)]}
            onDownload={() => onDownload('vae')}
            onCancel={() => onCancelDownload(model.vae.file)}
            onRemove={() => onRemoveDownload(model.vae.file)}
          />
        </div>
      </CollapsibleContent>
    </Collapsible>
  )
}

interface QuantColumnProps {
  title: string
  quants: QuantVariant[]
  activeQuantId: string
  downloadedByPath: Record<string, boolean>
  downloadStatusByPath: Record<string, DownloadProgressEvent>
  onSelectQuant: (quantId: string) => void
  onDownload: (quantId: string) => void
  onCancel: (relativePath: string) => void
  onRemove: (relativePath: string) => void
}

function QuantColumn({
  title,
  quants,
  activeQuantId,
  downloadedByPath,
  downloadStatusByPath,
  onSelectQuant,
  onDownload,
  onCancel,
  onRemove
}: QuantColumnProps): React.JSX.Element {
  return (
    <div className="space-y-1">
      <SectionHeader className="px-1 text-xs text-muted-foreground">{title}</SectionHeader>
      <div className="space-y-0.5 rounded-md border border-border/40 bg-muted/15 p-1.5">
        {quants.map((quant) => (
          <QuantRow
            key={quant.id}
            quant={quant}
            isActive={quant.id === activeQuantId}
            isDownloaded={!!downloadedByPath[normalizeRelativePath(quant.file)]}
            downloadStatus={downloadStatusByPath[normalizeRelativePath(quant.file)]}
            onSelect={() => onSelectQuant(quant.id)}
            onDownload={() => onDownload(quant.id)}
            onCancel={() => onCancel(quant.file)}
            onRemove={() => onRemove(quant.file)}
          />
        ))}
      </div>
    </div>
  )
}

function QuantRow({
  quant,
  isActive,
  isDownloaded,
  downloadStatus,
  onSelect,
  onDownload,
  onCancel,
  onRemove
}: {
  quant: QuantVariant
  isActive: boolean
  isDownloaded: boolean
  downloadStatus?: DownloadProgressEvent
  onSelect: () => void
  onDownload: () => void
  onCancel: () => void
  onRemove: () => void
}): React.JSX.Element {
  const isDownloading = !isDownloaded && downloadStatus?.status === 'downloading'
  const isQueued = !isDownloaded && downloadStatus?.status === 'queued'
  const isFailed = !isDownloaded && downloadStatus?.status === 'failed'
  const isRecommended =
    quant.label.toLowerCase().includes('balanced') ||
    quant.description.toLowerCase().startsWith('balanced')
  const canSelect = isDownloaded && !isActive

  return (
    <button
      type="button"
      onClick={canSelect ? onSelect : undefined}
      className={cn(
        'flex w-full items-center gap-1.5 rounded px-2 py-1.5 text-left text-sm transition-colors',
        isActive
          ? 'bg-primary/10'
          : canSelect
            ? 'cursor-pointer hover:bg-muted/60'
            : 'cursor-default opacity-70'
      )}
    >
      <span
        className={cn(
          'size-3 shrink-0 rounded-full border',
          isActive
            ? 'border-primary bg-primary'
            : isDownloaded
              ? 'border-muted-foreground/50'
              : 'border-muted-foreground/25'
        )}
      />

      <div className="min-w-0 flex items-center gap-1.5">
        <Tooltip>
          <TooltipTrigger asChild>
            <span className={cn('truncate', isActive ? 'font-medium' : 'font-normal')}>
              {quant.label}
            </span>
          </TooltipTrigger>
          <TooltipContent side="bottom">{quant.description}</TooltipContent>
        </Tooltip>
        {isRecommended ? (
          <Badge variant="outline" className="h-4 px-1 text-[9px] leading-none text-muted-foreground">
            Rec.
          </Badge>
        ) : null}
      </div>

      <span className="flex-1" />

      <span className="shrink-0 text-[11px] text-muted-foreground">{formatApproxSize(quant.size)}</span>

      <div className="ml-1 shrink-0" onClick={(event) => event.stopPropagation()}>
        {isDownloading && downloadStatus ? (
          <div className="flex items-center gap-1">
            <Progress
              value={toPercent(downloadStatus.downloadedBytes, downloadStatus.totalBytes)}
              className="h-1.5 w-12"
            />
            <span className="w-7 text-right text-[10px] text-muted-foreground">
              {toPercent(downloadStatus.downloadedBytes, downloadStatus.totalBytes)}%
            </span>
            <Button type="button" size="icon-xs" variant="ghost" onClick={onCancel}>
              <X className="size-3" />
            </Button>
          </div>
        ) : isQueued ? (
          <div className="flex items-center gap-1">
            <Badge
              variant="outline"
              className="h-5 border-amber-500/25 bg-amber-500/10 px-1.5 text-[10px] text-amber-400"
            >
              <Clock3 className="mr-1 size-3" />
              Queued
            </Badge>
            <Button type="button" size="icon-xs" variant="ghost" onClick={onCancel}>
              <X className="size-3" />
            </Button>
          </div>
        ) : isFailed ? (
          <Button type="button" size="xs" variant="outline" onClick={onDownload}>
            Retry
          </Button>
        ) : isDownloaded && isActive ? (
          <span className="inline-flex h-6 w-6 items-center justify-center text-emerald-500">
            <Check className="size-3.5" />
          </span>
        ) : isDownloaded ? (
          <Button type="button" size="icon-xs" variant="ghost" onClick={onRemove}>
            <Trash2 className="size-3" />
          </Button>
        ) : (
          <Button type="button" size="icon-xs" variant="outline" onClick={onDownload}>
            <Download className="size-3" />
          </Button>
        )}
      </div>
    </button>
  )
}

function VaeRow({
  vae,
  isDownloaded,
  downloadStatus,
  onDownload,
  onCancel,
  onRemove
}: {
  vae: ModelFileRef
  isDownloaded: boolean
  downloadStatus?: DownloadProgressEvent
  onDownload: () => void
  onCancel: () => void
  onRemove: () => void
}): React.JSX.Element {
  const isDownloading = !isDownloaded && downloadStatus?.status === 'downloading'
  const isQueued = !isDownloaded && downloadStatus?.status === 'queued'
  const isFailed = !isDownloaded && downloadStatus?.status === 'failed'
  const fileName = vae.file.split(/[\\/]/).pop() ?? vae.file

  return (
    <div className="mt-2 flex items-center gap-2 rounded-md border border-border/40 px-2 py-1.5 text-sm">
      <SectionHeader className="shrink-0 text-xs text-muted-foreground">VAE</SectionHeader>
      <span className="truncate font-medium">{fileName}</span>
      <span className="shrink-0 text-xs text-muted-foreground">{formatApproxSize(vae.size)}</span>
      <span className="flex-1" />

      {isDownloading && downloadStatus ? (
        <div className="flex items-center gap-1">
          <Progress
            value={toPercent(downloadStatus.downloadedBytes, downloadStatus.totalBytes)}
            className="h-1.5 w-16"
          />
          <span className="w-8 text-right text-[10px] text-muted-foreground">
            {toPercent(downloadStatus.downloadedBytes, downloadStatus.totalBytes)}%
          </span>
          <Button type="button" size="icon-xs" variant="ghost" onClick={onCancel}>
            <X className="size-3" />
          </Button>
        </div>
      ) : isQueued ? (
        <div className="flex items-center gap-1">
          <Badge
            variant="outline"
            className="h-5 border-amber-500/25 bg-amber-500/10 px-1.5 text-[10px] text-amber-400"
          >
            <Clock3 className="mr-1 size-3" />
            Queued
          </Badge>
          <Button type="button" size="icon-xs" variant="ghost" onClick={onCancel}>
            <X className="size-3" />
          </Button>
        </div>
      ) : isFailed ? (
        <Button type="button" size="xs" variant="outline" onClick={onDownload}>
          Retry
        </Button>
      ) : isDownloaded ? (
        <div className="flex items-center gap-1">
          <Badge
            variant="outline"
            className="border-emerald-500/25 bg-emerald-500/10 text-emerald-400"
          >
            <Check className="mr-1 size-3" />
            Ready
          </Badge>
          <Button type="button" size="icon-xs" variant="ghost" onClick={onRemove}>
            <Trash2 className="size-3" />
          </Button>
        </div>
      ) : (
        <Button type="button" size="icon-xs" variant="outline" onClick={onDownload}>
          <Download className="size-3" />
        </Button>
      )}
    </div>
  )
}

// src/renderer/components/providers/LocalModelItem.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { Icon } from '@iconify/vue'
import Button from 'primevue/button'
import Tag from 'primevue/tag'
import ProgressBar from 'primevue/progressbar'

import { formatApproxSize, toPercent } from '@/lib/format'
import type { DownloadProgressEvent, ModelDefinition, ModelComponent } from '@/types'

const props = defineProps<{
  model: ModelDefinition
  diffusionQuantId: string
  textEncoderQuantId: string
  isReady: boolean
  downloadedByPath: Record<string, boolean>
  downloadStatusByPath: Record<string, DownloadProgressEvent>
}>()

const emit = defineEmits<{
  selectQuant: [component: Exclude<ModelComponent, 'vae'>, quantId: string]
  download: [component: ModelComponent, quantId?: string]
  cancelDownload: [relativePath: string]
  removeDownload: [relativePath: string]
}>()

const open = ref(!props.isReady)

function norm(p: string): string {
  return p.replace(/\\+/g, '/')
}

const normalizedDownloaded = computed(() =>
  Object.fromEntries(Object.entries(props.downloadedByPath).map(([k, v]) => [norm(k), v]))
)

const normalizedStatus = computed(() =>
  Object.fromEntries(Object.entries(props.downloadStatusByPath).map(([k, v]) => [norm(k), v]))
)

function isDownloaded(filePath: string): boolean {
  return !!normalizedDownloaded.value[norm(filePath)]
}

function getStatus(filePath: string): DownloadProgressEvent | undefined {
  return normalizedStatus.value[norm(filePath)]
}

// VAE helpers
const vaeFileName = computed(() => props.model.vae.file.split(/[\\/]/).pop() ?? props.model.vae.file)
const vaeDownloaded = computed(() => isDownloaded(props.model.vae.file))
const vaeStatus = computed(() => getStatus(props.model.vae.file))
const vaeDownloading = computed(
  () => !vaeDownloaded.value && vaeStatus.value?.status === 'downloading'
)
const vaeQueued = computed(() => !vaeDownloaded.value && vaeStatus.value?.status === 'queued')
const vaeFailed = computed(() => !vaeDownloaded.value && vaeStatus.value?.status === 'failed')
</script>

<template>
  <div class="rounded-md border border-default">
    <!-- Collapsible header -->
    <button
      type="button"
      class="flex w-full items-center gap-3 rounded-md px-3 py-2 text-left transition-colors hover:bg-emphasis"
      @click="open = !open"
    >
      <Icon
        icon="lucide:chevron-right"
        class="size-4 shrink-0 text-muted transition-transform"
        :class="open ? 'rotate-90' : ''"
      />
      <div class="min-w-0 flex-1">
        <div class="truncate text-sm font-medium">{{ model.name }}</div>
        <div class="truncate text-xs text-muted">{{ model.description }}</div>
      </div>
      <Tag
        :severity="isReady ? 'success' : 'warn'"
        :value="isReady ? 'Ready' : 'Setup Required'"
        class="gap-1"
      >
        <span
          class="size-2 shrink-0 rounded-full"
          :class="isReady ? 'bg-emerald-500' : 'bg-amber-500'"
        />
      </Tag>
    </button>

    <!-- Collapsible content -->
    <div v-if="open" class="px-3 pb-3 pt-1">
      <div class="grid grid-cols-2 gap-3">
        <!-- Diffusion column -->
        <div class="space-y-1">
          <div class="px-1 text-xs font-medium uppercase text-muted">Diffusion Model</div>
          <div class="space-y-0.5 rounded-md border border-default bg-emphasis/40 p-1.5">
            <button
              v-for="quant in model.diffusion.quants"
              :key="quant.id"
              type="button"
              class="flex w-full items-center gap-1.5 rounded px-2 py-1.5 text-left text-sm transition-colors"
              :class="
                quant.id === diffusionQuantId
                  ? 'bg-primary/10'
                  : isDownloaded(quant.file) && quant.id !== diffusionQuantId
                    ? 'cursor-pointer hover:bg-emphasis'
                    : 'cursor-default opacity-70'
              "
              @click="isDownloaded(quant.file) && quant.id !== diffusionQuantId ? emit('selectQuant', 'diffusion', quant.id) : undefined"
            >
              <!-- Radio dot -->
              <span
                class="size-3 shrink-0 rounded-full border"
                :class="
                  quant.id === diffusionQuantId
                    ? 'border-primary bg-primary'
                    : isDownloaded(quant.file)
                      ? 'border-surface-400'
                      : 'border-surface-500'
                "
              />

              <!-- Label -->
              <span
                v-tooltip.bottom="quant.description"
                class="min-w-0 truncate"
                :class="quant.id === diffusionQuantId ? 'font-medium' : ''"
              >
                {{ quant.label }}
              </span>
              <Tag
                v-if="quant.label.toLowerCase().includes('balanced') || quant.description.toLowerCase().startsWith('balanced')"
                severity="secondary"
                class="text-[9px]"
                value="Rec."
              />

              <span class="flex-1" />
              <span class="shrink-0 text-[11px] text-muted">{{ formatApproxSize(quant.size) }}</span>

              <!-- Actions -->
              <div class="ml-1 shrink-0" @click.stop>
                <!-- Downloading -->
                <div v-if="!isDownloaded(quant.file) && getStatus(quant.file)?.status === 'downloading'" class="flex items-center gap-1">
                  <ProgressBar
                    :value="toPercent(getStatus(quant.file)!.downloadedBytes, getStatus(quant.file)!.totalBytes)"
                    :show-value="false"
                    class="!h-1.5 w-12"
                  />
                  <span class="w-7 text-right text-[10px] text-muted">
                    {{ toPercent(getStatus(quant.file)!.downloadedBytes, getStatus(quant.file)!.totalBytes) }}%
                  </span>
                  <Button text severity="secondary" size="small" class="!p-0.5" @click="emit('cancelDownload', quant.file)">
                    <Icon icon="lucide:x" class="size-3" />
                  </Button>
                </div>
                <!-- Queued -->
                <div v-else-if="!isDownloaded(quant.file) && getStatus(quant.file)?.status === 'queued'" class="flex items-center gap-1">
                  <Tag severity="warn" class="text-[10px]">
                    <Icon icon="lucide:clock-3" class="mr-1 size-3" />
                    Queued
                  </Tag>
                  <Button text severity="secondary" size="small" class="!p-0.5" @click="emit('cancelDownload', quant.file)">
                    <Icon icon="lucide:x" class="size-3" />
                  </Button>
                </div>
                <!-- Failed -->
                <Button
                  v-else-if="!isDownloaded(quant.file) && getStatus(quant.file)?.status === 'failed'"
                  outlined
                  severity="secondary"
                  size="small"
                  label="Retry"
                  @click="emit('download', 'diffusion', quant.id)"
                />
                <!-- Downloaded + active -->
                <span v-else-if="isDownloaded(quant.file) && quant.id === diffusionQuantId" class="inline-flex size-6 items-center justify-center text-emerald-500">
                  <Icon icon="lucide:check" class="size-3.5" />
                </span>
                <!-- Downloaded + not active -->
                <Button
                  v-else-if="isDownloaded(quant.file)"
                  text
                  severity="secondary"
                  size="small"
                  class="!p-0.5"
                  @click="emit('removeDownload', quant.file)"
                >
                  <Icon icon="lucide:trash-2" class="size-3" />
                </Button>
                <!-- Not downloaded -->
                <Button v-else outlined severity="secondary" size="small" class="!p-0.5" @click="emit('download', 'diffusion', quant.id)">
                  <Icon icon="lucide:download" class="size-3" />
                </Button>
              </div>
            </button>
          </div>
        </div>

        <!-- Text Encoder column -->
        <div class="space-y-1">
          <div class="px-1 text-xs font-medium uppercase text-muted">Text Encoder</div>
          <div class="space-y-0.5 rounded-md border border-default bg-emphasis/40 p-1.5">
            <button
              v-for="quant in model.textEncoder.quants"
              :key="quant.id"
              type="button"
              class="flex w-full items-center gap-1.5 rounded px-2 py-1.5 text-left text-sm transition-colors"
              :class="
                quant.id === textEncoderQuantId
                  ? 'bg-primary/10'
                  : isDownloaded(quant.file) && quant.id !== textEncoderQuantId
                    ? 'cursor-pointer hover:bg-emphasis'
                    : 'cursor-default opacity-70'
              "
              @click="isDownloaded(quant.file) && quant.id !== textEncoderQuantId ? emit('selectQuant', 'textEncoder', quant.id) : undefined"
            >
              <span
                class="size-3 shrink-0 rounded-full border"
                :class="
                  quant.id === textEncoderQuantId
                    ? 'border-primary bg-primary'
                    : isDownloaded(quant.file)
                      ? 'border-surface-400'
                      : 'border-surface-500'
                "
              />

              <span
                v-tooltip.bottom="quant.description"
                class="min-w-0 truncate"
                :class="quant.id === textEncoderQuantId ? 'font-medium' : ''"
              >
                {{ quant.label }}
              </span>
              <Tag
                v-if="quant.label.toLowerCase().includes('balanced') || quant.description.toLowerCase().startsWith('balanced')"
                severity="secondary"
                class="text-[9px]"
                value="Rec."
              />

              <span class="flex-1" />
              <span class="shrink-0 text-[11px] text-muted">{{ formatApproxSize(quant.size) }}</span>

              <div class="ml-1 shrink-0" @click.stop>
                <div v-if="!isDownloaded(quant.file) && getStatus(quant.file)?.status === 'downloading'" class="flex items-center gap-1">
                  <ProgressBar
                    :value="toPercent(getStatus(quant.file)!.downloadedBytes, getStatus(quant.file)!.totalBytes)"
                    :show-value="false"
                    class="!h-1.5 w-12"
                  />
                  <span class="w-7 text-right text-[10px] text-muted">
                    {{ toPercent(getStatus(quant.file)!.downloadedBytes, getStatus(quant.file)!.totalBytes) }}%
                  </span>
                  <Button text severity="secondary" size="small" class="!p-0.5" @click="emit('cancelDownload', quant.file)">
                    <Icon icon="lucide:x" class="size-3" />
                  </Button>
                </div>
                <div v-else-if="!isDownloaded(quant.file) && getStatus(quant.file)?.status === 'queued'" class="flex items-center gap-1">
                  <Tag severity="warn" class="text-[10px]">
                    <Icon icon="lucide:clock-3" class="mr-1 size-3" />
                    Queued
                  </Tag>
                  <Button text severity="secondary" size="small" class="!p-0.5" @click="emit('cancelDownload', quant.file)">
                    <Icon icon="lucide:x" class="size-3" />
                  </Button>
                </div>
                <Button
                  v-else-if="!isDownloaded(quant.file) && getStatus(quant.file)?.status === 'failed'"
                  outlined
                  severity="secondary"
                  size="small"
                  label="Retry"
                  @click="emit('download', 'textEncoder', quant.id)"
                />
                <span v-else-if="isDownloaded(quant.file) && quant.id === textEncoderQuantId" class="inline-flex size-6 items-center justify-center text-emerald-500">
                  <Icon icon="lucide:check" class="size-3.5" />
                </span>
                <Button
                  v-else-if="isDownloaded(quant.file)"
                  text
                  severity="secondary"
                  size="small"
                  class="!p-0.5"
                  @click="emit('removeDownload', quant.file)"
                >
                  <Icon icon="lucide:trash-2" class="size-3" />
                </Button>
                <Button v-else outlined severity="secondary" size="small" class="!p-0.5" @click="emit('download', 'textEncoder', quant.id)">
                  <Icon icon="lucide:download" class="size-3" />
                </Button>
              </div>
            </button>
          </div>
        </div>
      </div>

      <!-- VAE Row -->
      <div class="mt-2 flex items-center gap-2 rounded-md border border-default px-2 py-1.5 text-sm">
        <span class="shrink-0 text-xs font-medium uppercase text-muted">VAE</span>
        <span class="truncate font-medium">{{ vaeFileName }}</span>
        <span class="shrink-0 text-xs text-muted">{{ formatApproxSize(model.vae.size) }}</span>
        <span class="flex-1" />

        <!-- Downloading -->
        <div v-if="vaeDownloading && vaeStatus" class="flex items-center gap-1">
          <ProgressBar
            :value="toPercent(vaeStatus.downloadedBytes, vaeStatus.totalBytes)"
            :show-value="false"
            class="!h-1.5 w-16"
          />
          <span class="w-8 text-right text-[10px] text-muted">
            {{ toPercent(vaeStatus.downloadedBytes, vaeStatus.totalBytes) }}%
          </span>
          <Button text severity="secondary" size="small" class="!p-0.5" @click="emit('cancelDownload', model.vae.file)">
            <Icon icon="lucide:x" class="size-3" />
          </Button>
        </div>
        <!-- Queued -->
        <div v-else-if="vaeQueued" class="flex items-center gap-1">
          <Tag severity="warn" class="text-[10px]">
            <Icon icon="lucide:clock-3" class="mr-1 size-3" />
            Queued
          </Tag>
          <Button text severity="secondary" size="small" class="!p-0.5" @click="emit('cancelDownload', model.vae.file)">
            <Icon icon="lucide:x" class="size-3" />
          </Button>
        </div>
        <!-- Failed -->
        <Button
          v-else-if="vaeFailed"
          outlined
          severity="secondary"
          size="small"
          label="Retry"
          @click="emit('download', 'vae')"
        />
        <!-- Ready -->
        <div v-else-if="vaeDownloaded" class="flex items-center gap-1">
          <Tag severity="success" class="gap-1">
            <Icon icon="lucide:check" class="size-3" />
            Ready
          </Tag>
          <Button text severity="secondary" size="small" class="!p-0.5" @click="emit('removeDownload', model.vae.file)">
            <Icon icon="lucide:trash-2" class="size-3" />
          </Button>
        </div>
        <!-- Not downloaded -->
        <Button v-else outlined severity="secondary" size="small" class="!p-0.5" @click="emit('download', 'vae')">
          <Icon icon="lucide:download" class="size-3" />
        </Button>
      </div>
    </div>
  </div>
</template>
