// src/renderer/components/providers/ModelBrowser.tsx
import * as React from 'react'

import { Loader2, Plus, Check, Search, AlertCircle } from 'lucide-react'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Skeleton } from '@/components/ui/skeleton'
import { Item, ItemContent, ItemTitle, ItemActions, ItemGroup } from '@/components/ui/item'
import { useModelBrowsingStore } from '@/stores/model-browsing-store'
import type { ProviderModel, SearchResultModel } from '@/types'

interface ModelBrowserProps {
  providerId: string
  browseMode: 'search' | 'list'
  addedModelIds: Set<string>
}

export function ModelBrowser({
  providerId,
  browseMode,
  addedModelIds
}: ModelBrowserProps): React.JSX.Element {
  if (browseMode === 'list') {
    return <ListBrowser providerId={providerId} addedModelIds={addedModelIds} />
  }
  return <SearchBrowser providerId={providerId} addedModelIds={addedModelIds} />
}

// =============================================================================
// Search-based browser (Fal, Replicate)
// =============================================================================

function SearchBrowser({
  providerId,
  addedModelIds
}: {
  providerId: string
  addedModelIds: Set<string>
}): React.JSX.Element {
  const searchModels = useModelBrowsingStore((s) => s.searchModels)
  const addUserModel = useModelBrowsingStore((s) => s.addUserModel)
  const searchResults = useModelBrowsingStore((s) => s.searchResults)
  const searchLoading = useModelBrowsingStore((s) => s.searchLoading)

  const [query, setQuery] = React.useState('')
  const debounceRef = React.useRef<number | null>(null)

  const results = searchResults[providerId]?.models ?? []
  const isLoading = searchLoading[providerId] ?? false

  // Debounced search
  React.useEffect(() => {
    if (debounceRef.current) window.clearTimeout(debounceRef.current)
    if (!query.trim()) return

    debounceRef.current = window.setTimeout(() => {
      void searchModels(providerId, query.trim())
    }, 400)

    return () => {
      if (debounceRef.current) window.clearTimeout(debounceRef.current)
    }
  }, [query, providerId, searchModels])

  // Reset search when switching providers
  React.useEffect(() => {
    setQuery('')
  }, [providerId])

  const handleAdd = async (model: SearchResultModel): Promise<void> => {
    // Fetch full model detail (with request schema) before persisting.
    // Fall back to a stub schema only when the detail call fails.
    let detailedModel: ProviderModel | null = null
    try {
      detailedModel = await window.api.providers.fetchModelDetail(providerId, model.modelId)
    } catch {
      // ignore — will fall back below
    }

    const providerModel: ProviderModel = detailedModel ?? {
      modelId: model.modelId,
      name: model.name,
      description: model.description,
      type: model.type,
      providerId,
      requestSchema: {
        properties: {
          prompt: {
            type: 'string',
            title: 'Prompt'
          }
        },
        required: ['prompt'],
        order: ['prompt']
      }
    }
    await addUserModel(providerId, providerModel)
  }

  return (
    <div className="space-y-2">
      <div className="relative">
        <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 size-3.5 text-muted-foreground" />
        <Input
          placeholder="Search models…"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          className="pl-8"
        />
      </div>

      {/* Fixed-height results pane — always occupies space to prevent layout shift */}
      <div className="h-[200px] rounded-md border border-border/60">
        <ScrollArea className="h-full">
          {isLoading ? (
            <div className="space-y-1.5 p-2">
              {[1, 2, 3].map((i) => (
                <Skeleton key={i} className="h-14 w-full rounded-md" />
              ))}
            </div>
          ) : !query.trim() ? (
            <div className="flex h-[280px] items-center justify-center text-xs text-muted-foreground">
              Type to search for models
            </div>
          ) : results.length === 0 ? (
            <div className="flex h-[280px] items-center justify-center text-xs text-muted-foreground">
              No models found for &ldquo;{query}&rdquo;
            </div>
          ) : (
            <ModelResultList models={results} addedModelIds={addedModelIds} onAdd={handleAdd} />
          )}
        </ScrollArea>
      </div>
    </div>
  )
}

// =============================================================================
// List-based browser (Wavespeed)
// =============================================================================

function ListBrowser({
  providerId,
  addedModelIds
}: {
  providerId: string
  addedModelIds: Set<string>
}): React.JSX.Element {
  const listModels = useModelBrowsingStore((s) => s.listModels)
  const addUserModel = useModelBrowsingStore((s) => s.addUserModel)
  const listCache = useModelBrowsingStore((s) => s.listCache)
  const listLoading = useModelBrowsingStore((s) => s.listLoading)

  const [filter, setFilter] = React.useState('')

  const allModels = React.useMemo(() => listCache[providerId] ?? [], [listCache, providerId])
  const isLoading = listLoading[providerId] ?? false

  // Load on mount
  React.useEffect(() => {
    void listModels(providerId)
  }, [providerId, listModels])

  // Reset filter when switching providers
  React.useEffect(() => {
    setFilter('')
  }, [providerId])

  const filtered = React.useMemo(() => {
    if (!filter.trim()) return allModels
    const q = filter.toLowerCase()
    return allModels.filter(
      (m) =>
        m.name.toLowerCase().includes(q) ||
        m.modelId.toLowerCase().includes(q) ||
        m.description?.toLowerCase().includes(q)
    )
  }, [allModels, filter])

  const handleAdd = async (model: ProviderModel | SearchResultModel): Promise<void> => {
    const providerModel: ProviderModel = {
      modelId: model.modelId,
      name: model.name,
      description: model.description,
      type: model.type,
      providerId,
      requestSchema:
        'requestSchema' in model
          ? model.requestSchema
          : {
              properties: {
                prompt: {
                  type: 'string',
                  title: 'Prompt'
                }
              },
              required: ['prompt'],
              order: ['prompt']
            }
    }
    await addUserModel(providerId, providerModel)
  }

  return (
    <div className="space-y-2">
      <div className="relative">
        <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 size-3.5 text-muted-foreground" />
        <Input
          placeholder="Filter models…"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          className="pl-8"
        />
      </div>

      {/* Fixed-height results pane — always occupies space to prevent layout shift */}
      <div className="h-[280px] rounded-md border border-border/60">
        <ScrollArea className="h-full">
          {isLoading ? (
            <div className="space-y-1.5 p-2">
              {[1, 2, 3].map((i) => (
                <Skeleton key={i} className="h-14 w-full rounded-md" />
              ))}
            </div>
          ) : filtered.length === 0 ? (
            <div className="flex h-[280px] items-center justify-center text-xs text-muted-foreground">
              {allModels.length > 0 ? 'No models match your filter' : 'No models available'}
            </div>
          ) : (
            <ModelResultList models={filtered} addedModelIds={addedModelIds} onAdd={handleAdd} />
          )}
        </ScrollArea>
      </div>
    </div>
  )
}

// =============================================================================
// Shared model result list
// =============================================================================

function ModelResultList({
  models,
  addedModelIds,
  onAdd
}: {
  models: Array<SearchResultModel | ProviderModel>
  addedModelIds: Set<string>
  onAdd: (model: SearchResultModel | ProviderModel) => Promise<void>
}): React.JSX.Element {
  const [addingIds, setAddingIds] = React.useState<Set<string>>(new Set())
  const [errorIds, setErrorIds] = React.useState<Set<string>>(new Set())

  const handleAdd = async (model: SearchResultModel | ProviderModel): Promise<void> => {
    setAddingIds((prev) => new Set(prev).add(model.modelId))
    setErrorIds((prev) => {
      const next = new Set(prev)
      next.delete(model.modelId)
      return next
    })
    try {
      await onAdd(model)
    } catch {
      setErrorIds((prev) => new Set(prev).add(model.modelId))
    } finally {
      setAddingIds((prev) => {
        const next = new Set(prev)
        next.delete(model.modelId)
        return next
      })
    }
  }

  return (
    <ItemGroup>
      {models.map((model) => {
        const isAdded = addedModelIds.has(model.modelId)
        const isAdding = addingIds.has(model.modelId)
        const hasError = errorIds.has(model.modelId)

        return (
          <Item
            key={model.modelId}
            variant="outline"
            size="sm"
            className="hover:border-border hover:bg-muted/50"
          >
            <ItemContent>
              <ItemTitle className="flex items-center gap-1.5 truncate">
                <span className="truncate">{model.name}</span>
                {model.modelId !== model.name && (
                  <>
                    <span className="shrink-0 text-muted-foreground/40">·</span>
                    <span className="truncate text-muted-foreground font-normal">
                      {model.modelId}
                    </span>
                  </>
                )}
                {model.type && (
                  <Badge variant="secondary" className="shrink-0 ml-0.5 text-[10px] px-1">
                    {model.type}
                  </Badge>
                )}
              </ItemTitle>
            </ItemContent>
            <ItemActions>
              {hasError ? (
                <Badge
                  variant="secondary"
                  className="gap-1 border-destructive/20 text-destructive bg-destructive/10 cursor-pointer"
                  title="Failed to add — click to retry"
                  onClick={() => void handleAdd(model)}
                >
                  <AlertCircle className="size-3" />
                  Retry
                </Badge>
              ) : isAdded ? (
                <Badge variant="secondary" className="gap-1 text-emerald-600">
                  <Check className="size-3" />
                  Added
                </Badge>
              ) : (
                <Button
                  variant="outline"
                  size="xs"
                  disabled={isAdding}
                  onClick={() => void handleAdd(model)}
                >
                  {isAdding ? (
                    <Loader2 className="size-3 animate-spin" />
                  ) : (
                    <Plus className="size-3" />
                  )}
                  Add
                </Button>
              )}
            </ItemActions>
          </Item>
        )
      })}
    </ItemGroup>
  )
}

// src/renderer/components/providers/ModelBrowser.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Icon } from '@iconify/vue'
import Button from 'primevue/button'
import InputText from 'primevue/inputtext'
import Skeleton from 'primevue/skeleton'
import Tag from 'primevue/tag'

import { useModelBrowsingStore } from '@/stores/model-browsing'
import type { ProviderModel, SearchResultModel } from '@/types'

const props = defineProps<{
  providerId: string
  browseMode: 'search' | 'list'
  addedModelIds: Set<string>
}>()

const browsingStore = useModelBrowsingStore()

// ── Shared state ──────────────────────────────────────────────────────────────
const query = ref('')
const addingIds = ref(new Set<string>())
const errorIds = ref(new Set<string>())

// Reset when provider changes
watch(
  () => props.providerId,
  () => {
    query.value = ''
    addingIds.value = new Set()
    errorIds.value = new Set()
    // For list mode, load on provider switch
    if (props.browseMode === 'list') {
      void browsingStore.listModels(props.providerId)
    }
  },
  { immediate: true }
)

// ── Search mode: debounced search ─────────────────────────────────────────────
let debounceTimer: ReturnType<typeof setTimeout> | null = null

watch(query, (q) => {
  if (debounceTimer) clearTimeout(debounceTimer)
  if (!q.trim() || props.browseMode !== 'search') return
  debounceTimer = setTimeout(() => {
    void browsingStore.searchModels(props.providerId, q.trim())
  }, 400)
})

// ── Computed models ───────────────────────────────────────────────────────────
const isLoading = computed(() =>
  props.browseMode === 'search'
    ? browsingStore.searchLoading[props.providerId] ?? false
    : browsingStore.listLoading[props.providerId] ?? false
)

const models = computed<Array<SearchResultModel | ProviderModel>>(() => {
  if (props.browseMode === 'search') {
    return browsingStore.searchResults[props.providerId]?.models ?? []
  }
  const all = browsingStore.listCache[props.providerId] ?? []
  if (!query.value.trim()) return all
  const q = query.value.toLowerCase()
  return all.filter(
    (m) =>
      m.name.toLowerCase().includes(q) ||
      m.modelId.toLowerCase().includes(q) ||
      m.description?.toLowerCase().includes(q)
  )
})

const emptyMessage = computed(() => {
  if (props.browseMode === 'search') {
    return query.value.trim() ? `No models found for "${query.value}"` : 'Type to search for models'
  }
  const all = browsingStore.listCache[props.providerId] ?? []
  return all.length > 0 ? 'No models match your filter' : 'No models available'
})

// ── Add model ─────────────────────────────────────────────────────────────────
async function handleAdd(model: SearchResultModel | ProviderModel): Promise<void> {
  addingIds.value = new Set(addingIds.value).add(model.modelId)
  const nextErrors = new Set(errorIds.value)
  nextErrors.delete(model.modelId)
  errorIds.value = nextErrors

  try {
    // For search results, try to fetch full detail (with schema) first
    let providerModel: ProviderModel
    if (!('requestSchema' in model)) {
      let detail: ProviderModel | null = null
      try {
        detail = await window.api.providers.fetchModelDetail(props.providerId, model.modelId)
      } catch {
        // fall through to stub
      }
      providerModel = detail ?? {
        modelId: model.modelId,
        name: model.name,
        description: model.description,
        type: model.type,
        providerId: props.providerId,
        requestSchema: {
          properties: { prompt: { type: 'string', title: 'Prompt' } },
          required: ['prompt'],
          order: ['prompt']
        }
      }
    } else {
      providerModel = {
        modelId: model.modelId,
        name: model.name,
        description: model.description,
        type: model.type,
        providerId: props.providerId,
        requestSchema: model.requestSchema
      }
    }
    await browsingStore.addUserModel(props.providerId, providerModel)
  } catch {
    errorIds.value = new Set(errorIds.value).add(model.modelId)
  } finally {
    const next = new Set(addingIds.value)
    next.delete(model.modelId)
    addingIds.value = next
  }
}
</script>

<template>
  <div class="space-y-2">
    <!-- Search / filter input -->
    <div class="relative">
      <Icon
        icon="lucide:search"
        class="pointer-events-none absolute left-2.5 top-1/2 size-3.5 -translate-y-1/2 text-muted"
      />
      <InputText
        v-model="query"
        :placeholder="browseMode === 'search' ? 'Search models…' : 'Filter models…'"
        class="w-full !pl-8"
      />
    </div>

    <!-- Results container -->
    <div class="h-[240px] overflow-y-auto rounded-md border border-default">
      <!-- Loading -->
      <div v-if="isLoading" class="space-y-1.5 p-2">
        <Skeleton v-for="i in 3" :key="i" height="3.5rem" class="w-full rounded-md" />
      </div>

      <!-- Empty state -->
      <div
        v-else-if="models.length === 0"
        class="flex h-full items-center justify-center text-xs text-muted"
      >
        {{ emptyMessage }}
      </div>

      <!-- Model list -->
      <div v-else class="space-y-1 p-1">
        <div
          v-for="model in models"
          :key="model.modelId"
          class="flex items-center gap-2 rounded-md border border-transparent px-3 py-2 text-sm hover:bg-emphasis"
        >
          <div class="flex min-w-0 flex-1 items-center gap-1.5 truncate">
            <span class="truncate">{{ model.name }}</span>
            <template v-if="model.modelId !== model.name">
              <span class="shrink-0 opacity-30">·</span>
              <span class="truncate text-muted">{{ model.modelId }}</span>
            </template>
            <Tag
              v-if="model.type"
              severity="secondary"
              class="ml-0.5 shrink-0 text-[10px]"
              :value="model.type"
            />
          </div>

          <!-- Error / retry -->
          <Tag
            v-if="errorIds.has(model.modelId)"
            severity="danger"
            class="cursor-pointer gap-1"
            @click="handleAdd(model)"
          >
            <Icon icon="lucide:alert-circle" class="size-3" />
            Retry
          </Tag>

          <!-- Already added -->
          <Tag v-else-if="addedModelIds.has(model.modelId)" severity="success" class="gap-1">
            <Icon icon="lucide:check" class="size-3" />
            Added
          </Tag>

          <!-- Add button -->
          <Button
            v-else
            outlined
            severity="secondary"
            size="small"
            :disabled="addingIds.has(model.modelId)"
            :loading="addingIds.has(model.modelId)"
            @click="handleAdd(model)"
          >
            <Icon v-if="!addingIds.has(model.modelId)" icon="lucide:plus" class="mr-1 size-3" />
            Add
          </Button>
        </div>
      </div>
    </div>
  </div>
</template>
