// src/renderer/components/providers/ProviderManager.tsx
import * as React from 'react'

import { ProviderSidebar } from '@/components/providers/ProviderSidebar'
import { ProviderDetail } from '@/components/providers/ProviderDetail'
import { LocalDetail } from '@/components/providers/LocalDetail'
import { useProviderStore } from '@/stores/provider-store'
import { useModelBrowsingStore } from '@/stores/model-browsing-store'
import { useModelStore } from '@/stores/model-store'

export function ProviderManager(): React.JSX.Element {
  const loadProviders = useProviderStore((s) => s.loadProviders)
  const selectedProviderId = useProviderStore((s) => s.selectedProviderId)
  const loadAllUserModels = useModelBrowsingStore((s) => s.loadAllUserModels)
  const loadIdentities = useModelBrowsingStore((s) => s.loadIdentities)
  const hydrateModelStore = useModelStore((s) => s.hydrate)

  // Hydrate on mount
  React.useEffect(() => {
    void loadProviders().then(() => {
      void loadAllUserModels()
    })
    void loadIdentities()
    void hydrateModelStore()
  }, [loadProviders, loadAllUserModels, loadIdentities, hydrateModelStore])

  return (
    <div className="flex h-full min-h-0 gap-4">
      {/* Provider sidebar */}
      <div className="w-[200px] shrink-0">
        <ProviderSidebar />
      </div>

      {/* Detail panel */}
      <div className="min-w-0 flex-1">
        {selectedProviderId === 'local' ? (
          <LocalDetail />
        ) : selectedProviderId ? (
          <ProviderDetail providerId={selectedProviderId} />
        ) : (
          <div className="flex h-full items-center justify-center text-sm text-muted-foreground">
            Select a provider to configure
          </div>
        )}
      </div>
    </div>
  )
}

// src/renderer/components/providers/ProviderManager.vue
<script setup lang="ts">
import { onMounted } from 'vue'

import ProviderSidebar from '@/components/providers/ProviderSidebar.vue'
import ProviderDetail from '@/components/providers/ProviderDetail.vue'
import LocalDetail from '@/components/providers/LocalDetail.vue'
import { useProviderStore } from '@/stores/provider'
import { useModelBrowsingStore } from '@/stores/model-browsing'
import { useModelStore } from '@/stores/model'

const providerStore = useProviderStore()
const browsingStore = useModelBrowsingStore()
const modelStore = useModelStore()

onMounted(async () => {
  await providerStore.loadProviders()
  void browsingStore.loadAllUserModels()
  void browsingStore.loadIdentities()
  void modelStore.hydrate()
})
</script>

<template>
  <div class="flex h-full min-h-0 gap-4">
    <div class="w-[200px] shrink-0">
      <ProviderSidebar />
    </div>

    <div class="min-w-0 flex-1">
      <LocalDetail v-if="providerStore.selectedProviderId === 'local'" />
      <ProviderDetail
        v-else-if="providerStore.selectedProviderId"
        :provider-id="providerStore.selectedProviderId"
      />
      <div v-else class="flex h-full items-center justify-center text-sm text-muted">
        Select a provider to configure
      </div>
    </div>
  </div>
</template>
