// src/renderer/components/providers/ProviderSidebar.vue
<script setup lang="ts">
import { computed } from 'vue'
import Tag from 'primevue/tag'
import Divider from 'primevue/divider'

import { useProviderStore } from '@/stores/provider'
import { useModelBrowsingStore } from '@/stores/model-browsing'
import { useModelStore } from '@/stores/model'

const providerStore = useProviderStore()
const browsingStore = useModelBrowsingStore()
const modelStore = useModelStore()

const apiProviders = computed(() =>
  providerStore.providers.filter((p) => p.executionMode === 'remote-async')
)

const localModelCount = computed(() => modelStore.catalog?.models.length ?? 0)

const allLocalReady = computed(() =>
  modelStore.catalog?.models.every((m) => modelStore.filesByModelId[m.id]?.isReady) ?? false
)

function selectProvider(id: string): void {
  providerStore.selectProvider(id)
}
</script>

<template>
  <div class="h-full overflow-y-auto">
    <div class="space-y-1 p-1">
      <button
        v-for="provider in apiProviders"
        :key="provider.providerId"
        type="button"
        class="flex w-full items-center gap-2 rounded-md border px-3 py-2 text-left text-sm transition-colors"
        :class="
          provider.providerId === providerStore.selectedProviderId
            ? 'border-primary/40 bg-primary/10'
            : 'border-transparent hover:bg-emphasis'
        "
        @click="selectProvider(provider.providerId)"
      >
        <span
          class="size-2 shrink-0 rounded-full"
          :class="providerStore.hasApiKey[provider.providerId] ? 'bg-emerald-500' : 'bg-surface-400'"
        />
        <span class="min-w-0 flex-1 truncate">
          {{ provider.displayName ?? provider.providerId }}
        </span>
        <Tag
          v-if="(browsingStore.userModelsByProvider[provider.providerId]?.length ?? 0) > 0"
          severity="secondary"
          class="text-[10px]"
          :value="String(browsingStore.userModelsByProvider[provider.providerId]?.length ?? 0)"
        />
      </button>

      <div v-if="apiProviders.length === 0" class="px-3 py-6 text-center text-xs text-muted">
        No API providers configured
      </div>

      <Divider />

      <button
        type="button"
        class="flex w-full items-center gap-2 rounded-md border px-3 py-2 text-left text-sm transition-colors"
        :class="
          providerStore.selectedProviderId === 'local'
            ? 'border-primary/40 bg-primary/10'
            : 'border-transparent hover:bg-emphasis'
        "
        @click="selectProvider('local')"
      >
        <span
          class="size-2 shrink-0 rounded-full"
          :class="allLocalReady ? 'bg-emerald-500' : 'bg-amber-500'"
        />
        <span class="min-w-0 flex-1">Local</span>
        <Tag severity="secondary" class="text-[10px]" :value="String(localModelCount)" />
      </button>
    </div>
  </div>
</template>

// src/renderer/components/providers/ProviderSidebar.tsx
import * as React from 'react'

import { cn } from '@/lib/utils'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Separator } from '@/components/ui/separator'
import { Item, ItemContent, ItemTitle, ItemActions, ItemGroup } from '@/components/ui/item'
import { useProviderStore } from '@/stores/provider-store'
import { useModelBrowsingStore } from '@/stores/model-browsing-store'
import { useModelStore } from '@/stores/model-store'

/**
 * Status dot semantics:
 *  ready    — configured/ready
 *  warning  — setup required
 *  inactive — unavailable/not configured
 */
function statusDot(tone: 'ready' | 'warning' | 'inactive'): React.JSX.Element {
  const color =
    tone === 'ready' ? 'bg-emerald-500' : tone === 'warning' ? 'bg-amber-500' : 'bg-muted-foreground/40'
  return <span className={cn('size-2 shrink-0 rounded-full', color)} />
}

export function ProviderSidebar(): React.JSX.Element {
  const providers = useProviderStore((s) => s.providers)
  const selectedProviderId = useProviderStore((s) => s.selectedProviderId)
  const selectProvider = useProviderStore((s) => s.selectProvider)
  const userModelsByProvider = useModelBrowsingStore((s) => s.userModelsByProvider)
  const hasApiKey = useProviderStore((s) => s.hasApiKey)
  const catalog = useModelStore((s) => s.catalog)
  const filesByModelId = useModelStore((s) => s.filesByModelId)

  const localModelCount = catalog?.models.length ?? 0
  const allLocalReady =
    catalog?.models.every((model) => filesByModelId[model.id]?.isReady) ?? false

  // Only show API providers (not local)
  const apiProviders = React.useMemo(
    () => providers.filter((p) => p.executionMode === 'remote-async'),
    [providers]
  )

  return (
    <ScrollArea className="h-full">
      <ItemGroup>
        {apiProviders.map((provider) => {
          const isSelected = provider.providerId === selectedProviderId
          const modelCount = userModelsByProvider[provider.providerId]?.length ?? 0
          const keyPresent = hasApiKey[provider.providerId] ?? false

          return (
            <Item
              key={provider.providerId}
              variant="outline"
              size="sm"
              role="listitem"
              tabIndex={0}
              className={cn(
                'cursor-pointer',
                isSelected
                  ? 'border-primary/40 bg-primary/10'
                  : 'hover:border-border hover:bg-muted/50'
              )}
              onClick={() => selectProvider(provider.providerId)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault()
                  selectProvider(provider.providerId)
                }
              }}
            >
              <ItemContent>
                <ItemTitle>
                  {statusDot(keyPresent ? 'ready' : 'inactive')}
                  {provider.displayName ?? provider.providerId}
                </ItemTitle>
              </ItemContent>
              <ItemActions>
                {modelCount > 0 && (
                  <Badge variant="secondary" className="text-[10px] px-1.5">
                    {modelCount}
                  </Badge>
                )}
              </ItemActions>
            </Item>
          )
        })}

        {apiProviders.length === 0 && (
          <div className="px-3 py-6 text-center text-xs text-muted-foreground">
            No API providers configured
          </div>
        )}

        <Separator className="my-2" />

        <Item
          variant="outline"
          size="sm"
          role="listitem"
          tabIndex={0}
          className={cn(
            'cursor-pointer',
            selectedProviderId === 'local'
              ? 'border-primary/40 bg-primary/10'
              : 'hover:border-border hover:bg-muted/50'
          )}
          onClick={() => selectProvider('local')}
          onKeyDown={(e) => {
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault()
              selectProvider('local')
            }
          }}
        >
          <ItemContent>
            <ItemTitle>
              {statusDot(allLocalReady ? 'ready' : 'warning')}
              Local
            </ItemTitle>
          </ItemContent>
          <ItemActions>
            <Badge variant="secondary" className="text-[10px] px-1.5">
              {localModelCount}
            </Badge>
          </ItemActions>
        </Item>
      </ItemGroup>
    </ScrollArea>
  )
}
