// src/renderer/components/layout/LeftSidebar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Icon } from '@iconify/vue'
import Button from 'primevue/button'

import { LEFT_PANEL_WIDTH_PX, PANEL_ICON_STRIP_WIDTH_PX } from '@/lib/layout'
import GenerationPane from '@/components/panes/GenerationPane.vue'
import ImportPane from '@/components/panes/ImportPane.vue'
import TimelinePane from '@/components/panes/TimelinePane.vue'
import { useUIStore, type LeftPanelTab } from '@/stores/ui'

const uiStore = useUIStore()
const collapsed = computed(() => !uiStore.leftPanelOpen)

const tabs: { id: LeftPanelTab; icon: string; label: string }[] = [
  { id: 'generation', icon: 'lucide:sparkles', label: 'Generate' },
  { id: 'timeline', icon: 'lucide:clock-3', label: 'Timeline' },
  { id: 'import', icon: 'lucide:download', label: 'Import' }
]

const activePaneComponent = computed(() => {
  switch (uiStore.leftPanelTab) {
    case 'timeline':
      return TimelinePane
    case 'import':
      return ImportPane
    default:
      return GenerationPane
  }
})
</script>

<template>
  <aside
    id="left-sidebar"
    class="flex h-full shrink-0 transition-[width] duration-150 ease-linear bg-surface-950"
    :style="{ width: `${collapsed ? PANEL_ICON_STRIP_WIDTH_PX : LEFT_PANEL_WIDTH_PX}px` }"
  >
    <div class="flex h-full w-full overflow-hidden">
      <div class="flex w-12 shrink-0 flex-col items-center gap-1 pt-2 bg-surface-900">
        <Button
          v-for="tab in tabs"
          :key="tab.id"
          text
          plain
          :severity="uiStore.leftPanelTab === tab.id && !collapsed ? undefined : 'secondary'"
          size="small"
          :aria-label="tab.label"
          @click="uiStore.toggleLeftPanel(tab.id)"
        >
          <Icon :icon="tab.icon" class="size-5" />
        </Button>
      </div>

      <div v-if="!collapsed" class="min-w-0 flex-1 overflow-hidden">
        <component :is="activePaneComponent" />
      </div>
    </div>
  </aside>
</template>

// src/renderer/components/layout/LeftSidebar.tsx
import * as React from 'react'
import { Clock, Download, Sparkles } from 'lucide-react'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { useUIStore, type LeftPanelTab } from '@/stores/ui-store'
import { useGenerationStore } from '@/stores/generation-store'
import { AppSidebar, type SidebarTabConfig } from '@/components/layout/AppSidebar'
import { GenerationPane } from '@/components/panes/GenerationPane'
import { TimelinePane } from '@/components/panes/TimelinePane'
import { ImportPane } from '@/components/panes/ImportPane'

function TimelineHeaderActions(): React.JSX.Element {
  const generations = useGenerationStore((s) => s.generations)
  const setGenerations = useGenerationStore((s) => s.setGenerations)

  const activeCount = generations.filter((g) => g.status === 'pending').length

  const clearCompleted = React.useCallback(async () => {
    await window.api.timeline.clearCompleted()
    const { generations } = await window.api.timeline.getAll()
    setGenerations(generations)
  }, [setGenerations])

  return (
    <div className="flex items-center gap-2">
      {activeCount > 0 ? <Badge variant="secondary">{activeCount}</Badge> : null}
      <Button type="button" size="sm" variant="secondary" onClick={clearCompleted}>
        Clear completed
      </Button>
    </div>
  )
}

const LEFT_TABS: SidebarTabConfig<LeftPanelTab>[] = [
  {
    tab: 'generation',
    label: 'Generate',
    title: 'Generation',
    icon: Sparkles,
    content: <GenerationPane />
  },
  {
    tab: 'timeline',
    label: 'Timeline',
    title: 'Timeline',
    icon: Clock,
    content: <TimelinePane />,
    headerActions: <TimelineHeaderActions />
  },
  {
    tab: 'import',
    label: 'Import',
    title: 'Import',
    icon: Download,
    content: <ImportPane />
  }
]

export function LeftSidebar(): React.JSX.Element {
  const open = useUIStore((s) => s.leftPanelOpen)
  const activeTab = useUIStore((s) => s.leftPanelTab)
  const setLeftPanelOpen = useUIStore((s) => s.setLeftPanelOpen)
  const toggleLeftPanel = useUIStore((s) => s.toggleLeftPanel)
  const width = useUIStore((s) => s.leftPanelWidth)

  return (
    <AppSidebar
      side="left"
      open={open}
      onOpenChange={setLeftPanelOpen}
      activeTab={activeTab}
      onToggle={toggleLeftPanel}
      width={width}
      tabs={LEFT_TABS}
    />
  )
}
