// src/renderer/components/layout/RightSidebar.tsx
import * as React from 'react'
import { Crop, Eraser, Layers3, Info, Maximize2, Plus, SlidersHorizontal } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { useUIStore, type RightPanelTab } from '@/stores/ui-store'
import { useCollectionStore } from '@/stores/collection-store'
import { AppSidebar, type SidebarTabConfig } from '@/components/layout/AppSidebar'
import { MediaInfoPane } from '@/components/panes/MediaInfoPane'
import { GenerationInfoPane } from '@/components/panes/GenerationInfoPane'
import { CollectionsPane } from '@/components/panes/CollectionsPane'
import { UpscalePane } from '@/components/panes/UpscalePane'
import { TransformPane } from '@/components/panes/TransformPane'
import { RemovalPane } from '@/components/panes/RemovalPane'

function CollectionsHeaderActions(): React.JSX.Element {
  const openModal = useUIStore((s) => s.openModal)
  const setEditingCollectionId = useCollectionStore((s) => s.setEditingCollectionId)

  return (
    <Button
      type="button"
      variant="secondary"
      size="icon-sm"
      onClick={() => {
        setEditingCollectionId(null)
        openModal('collection')
      }}
      aria-label="Create collection"
    >
      <Plus className="size-4" />
    </Button>
  )
}

const RIGHT_TABS: SidebarTabConfig<RightPanelTab>[] = [
  {
    tab: 'collections',
    label: 'Collections',
    title: 'Collections',
    icon: Layers3,
    headerActions: <CollectionsHeaderActions />,
    content: <CollectionsPane />
  },
  {
    tab: 'info',
    label: 'Info',
    title: 'Media Info',
    icon: Info,
    content: <MediaInfoPane />
  },
  {
    tab: 'generation-info',
    label: 'Generation',
    title: 'Generation Info',
    icon: SlidersHorizontal,
    content: <GenerationInfoPane />
  },
  {
    tab: 'upscale',
    label: 'Upscale',
    title: 'Upscale',
    icon: Maximize2,
    content: <UpscalePane />
  },
  {
    tab: 'transform',
    label: 'Transform',
    title: 'Transform',
    icon: Crop,
    content: <TransformPane />
  },
  {
    tab: 'removal',
    label: 'Removals',
    title: 'Removals',
    icon: Eraser,
    content: <RemovalPane />
  }
]

export function RightSidebar(): React.JSX.Element {
  const open = useUIStore((s) => s.rightPanelOpen)
  const activeTab = useUIStore((s) => s.rightPanelTab)
  const toggleRightPanel = useUIStore((s) => s.toggleRightPanel)
  const setRightPanelOpen = useUIStore((s) => s.setRightPanelOpen)
  const width = useUIStore((s) => s.rightPanelWidth)

  return (
    <AppSidebar
      side="right"
      open={open}
      onOpenChange={setRightPanelOpen}
      activeTab={activeTab}
      onToggle={toggleRightPanel}
      width={width}
      tabs={RIGHT_TABS}
    />
  )
}

// src/renderer/components/layout/RightSidebar.vue
<script setup lang="ts">
import { computed } from 'vue'

import { PANEL_ICON_STRIP_WIDTH_PX, RIGHT_PANEL_WIDTH_PX } from '@/lib/layout'
import CollectionsPane from '@/components/panes/CollectionsPane.vue'
import AdjustmentsPane from '@/components/panes/AdjustmentsPane.vue'
import GenerationInfoPane from '@/components/panes/GenerationInfoPane.vue'
import MediaInfoPane from '@/components/panes/MediaInfoPane.vue'
import RemovalPane from '@/components/panes/RemovalPane.vue'
import TransformPane from '@/components/panes/TransformPane.vue'
import UpscalePane from '@/components/panes/UpscalePane.vue'
import SidebarIconRail, { type SidebarTab } from '@/components/layout/SidebarIconRail.vue'
import { useUIStore, type RightPanelTab } from '@/stores/ui'

const uiStore = useUIStore()
const collapsed = computed(() => !uiStore.rightPanelOpen)

const tabs: SidebarTab[] = [
  { id: 'info', icon: 'lucide:info', label: 'Info' },
  { id: 'collections', icon: 'lucide:layers-3', label: 'Collections' },
  { id: 'transform', icon: 'lucide:crop', label: 'Transform' },
  { id: 'adjustments', icon: 'lucide:sliders-horizontal', label: 'Adjustments' },
  { id: 'removal', icon: 'lucide:eraser', label: 'Removals' },
  { id: 'upscale', icon: 'lucide:maximize-2', label: 'Upscale' }
]

const activePaneComponent = computed(() => {
  switch (uiStore.rightPanelTab) {
    case 'generation':
      return GenerationInfoPane
    case 'collections':
      return CollectionsPane
    case 'transform':
      return TransformPane
    case 'adjustments':
      return AdjustmentsPane
    case 'removal':
      return RemovalPane
    case 'upscale':
      return UpscalePane
    default:
      return MediaInfoPane
  }
})
</script>

<template>
  <aside id="right-sidebar" class="flex h-full shrink-0 transition-[width] duration-150 ease-linear bg-surface-950"
    :style="{ width: `${collapsed ? PANEL_ICON_STRIP_WIDTH_PX : RIGHT_PANEL_WIDTH_PX}px` }">
    <div class="flex h-full w-full">
      <div v-if="!collapsed" class="min-w-0 flex-1 overflow-hidden">
        <component :is="activePaneComponent" />
      </div>

      <SidebarIconRail
        class="ms-auto"
        :tabs="tabs"
        :active-tab="uiStore.rightPanelTab"
        :active="!collapsed"
        @select="(id) => uiStore.toggleRightPanel(id as RightPanelTab)"
      />
    </div>
  </aside>
</template>
