// src/renderer/components/layout/TitleBar.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref } from 'vue'
import { Icon } from '@iconify/vue'
import Button from 'primevue/button'

import { useUIStore } from '@/stores/ui'

const uiStore = useUIStore()
const isMaximized = ref(false)

const dragStyle = { WebkitAppRegion: 'drag' as const }
const noDragStyle = { WebkitAppRegion: 'no-drag' as const }

function handleMinimize(): void {
  void window.api.windowMinimize()
}

function handleToggleMaximize(): void {
  void window.api.windowToggleMaximize()
}

function handleClose(): void {
  void window.api.windowClose()
}

let unsubscribe: (() => void) | null = null

onMounted(async () => {
  try {
    isMaximized.value = await window.api.windowIsMaximized()
  } catch {
    isMaximized.value = false
  }

  unsubscribe = window.api.on('app:windowMaximizedChanged', (value: unknown) => {
    isMaximized.value = Boolean(value)
  })
})

onBeforeUnmount(() => {
  unsubscribe?.()
  unsubscribe = null
})
</script>

<template>
  <header
    class="flex h-10 shrink-0 items-center px-3 bg-surface-900"
    :style="dragStyle"
    @dblclick="handleToggleMaximize"
  >
    <div class="min-w-0 flex-1">
      <span class="text-sm font-medium">Distillery</span>
    </div>

    <!-- Actions (Models, Settings) -->
    <div class="flex items-center gap-2" :style="noDragStyle" @dblclick.stop>
      <Button
        text
        severity="secondary"
        size="small"
        aria-label="Open provider manager"
        @click="uiStore.openModal('providers')"
      >
        <Icon icon="lucide:boxes" class="mr-1 size-4" />
        Models
      </Button>

      <Button
        text
        severity="secondary"
        size="small"
        aria-label="Open settings"
        @click="uiStore.openModal('settings')"
      >
        <Icon icon="lucide:settings" class="mr-1 size-4" />
        Settings
      </Button>
    </div>

    <!-- Window controls -->
    <div class="flex items-center" :style="noDragStyle" @dblclick.stop>
      <Button
        text
        plain
        severity="secondary"
        size="small"
        aria-label="Minimize"
        @click="handleMinimize"
      >
        <Icon icon="lucide:minus" class="size-4" />
      </Button>

      <Button
        text
        plain
        severity="secondary"
        size="small"
        :aria-label="isMaximized ? 'Restore window' : 'Maximize window'"
        @click="handleToggleMaximize"
      >
        <Icon :icon="isMaximized ? 'lucide:copy' : 'lucide:square'" class="size-4" />
      </Button>

      <Button
        text
        plain
        severity="secondary"
        size="small"
        aria-label="Close"
        class="hover:!bg-red-600 hover:!text-white"
        @click="handleClose"
      >
        <Icon icon="lucide:x" class="size-4" />
      </Button>
    </div>
  </header>
</template>

// src/renderer/components/layout/TitleBar.tsx
import * as React from 'react'
import { Boxes, Copy, Minus, Settings, Square, X } from 'lucide-react'

import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { useUIStore } from '@/stores/ui-store'

function WindowControls(): React.JSX.Element {
  const [isMaximized, setIsMaximized] = React.useState(false)

  React.useEffect(() => {
    void window.api
      .windowIsMaximized()
      .then(setIsMaximized)
      .catch(() => {})
    const unsub = window.api.on('app:windowMaximizedChanged', (value: unknown) => {
      setIsMaximized(Boolean(value))
    })
    return unsub
  }, [])

  const buttonClass =
    'h-8 w-11 rounded-none text-sidebar-foreground hover:bg-accent hover:text-accent-foreground'

  return (
    <div
      className="flex items-stretch"
      style={{ WebkitAppRegion: 'no-drag' } as React.CSSProperties}
      onDoubleClick={(e) => e.stopPropagation()}
    >
      <button
        type="button"
        className={cn('grid place-items-center', buttonClass)}
        aria-label="Minimize"
        onClick={() => void window.api.windowMinimize()}
      >
        <Minus className="size-4" />
      </button>

      <button
        type="button"
        className={cn('grid place-items-center', buttonClass)}
        aria-label={isMaximized ? 'Restore' : 'Maximize'}
        onClick={() => void window.api.windowToggleMaximize()}
      >
        {isMaximized ? <Copy className="size-4" /> : <Square className="size-4" />}
      </button>

      <button
        type="button"
        className={cn(
          'grid place-items-center',
          buttonClass,
          'hover:bg-destructive hover:text-destructive-foreground'
        )}
        aria-label="Close"
        onClick={() => void window.api.windowClose()}
      >
        <X className="size-4" />
      </button>
    </div>
  )
}

export function TitleBar(): React.JSX.Element {
  const openModal = useUIStore((s) => s.openModal)

  return (
    <div
      className={cn(
        'flex items-center border-b border-sidebar-border bg-sidebar pl-3 text-sidebar-foreground py-0.5'
      )}
      style={
        {
          WebkitAppRegion: 'drag'
        } as React.CSSProperties
      }
      onDoubleClick={() => void window.api.windowToggleMaximize()}
    >
      <div className="flex min-w-0 flex-1 items-center gap-3">
        <div className="text-sm font-medium text-foreground">Distillery</div>
        <div className="min-w-0 flex-1" />
      </div>

      {/* Reserved for future custom menus / actions. Marked no-drag. */}
      <div
        className="flex items-center gap-2"
        style={{ WebkitAppRegion: 'no-drag' } as React.CSSProperties}
        onDoubleClick={(e) => e.stopPropagation()}
      >
        <Button
          type="button"
          variant="ghost"
          size="sm"
          className="h-8"
          onClick={() => openModal('models')}
          aria-label="Open model manager"
        >
          <Boxes className="size-4" />
          Models
        </Button>

        <Button
          type="button"
          variant="ghost"
          size="sm"
          className="h-8"
          onClick={() => openModal('settings')}
          aria-label="Open settings"
        >
          <Settings className="size-4" />
          Settings
        </Button>
      </div>

      <WindowControls />
    </div>
  )
}
