// src/renderer/components/library/GridView.vue
<script setup lang="ts">
import { useVirtualizer } from '@tanstack/vue-virtual'
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'

import { GRID_BUFFER_ROWS } from '@/lib/constants'
import { useGridSelection } from '@/composables/useGridSelection'
import { useLibraryMediaDrag } from '@/composables/useLibraryMediaDrag'
import { useLibraryStore } from '@/stores/library'
import { useUIStore } from '@/stores/ui'
import MediaThumbnail from '@/components/library/MediaThumbnail.vue'
import type { MediaRecord } from '@/types'

const GRID_GAP = 12

const libraryStore = useLibraryStore()
const uiStore = useUIStore()
const { handleClick, handleDoubleClick } = useGridSelection()
const { handleDragStart } = useLibraryMediaDrag()

const scrollRef = ref<HTMLDivElement | null>(null)
const contentWidth = ref(0)
const initialScrollRestored = ref(false)

const columnCount = computed(() => {
  if (contentWidth.value <= 0) return 0

  return Math.max(
    1,
    Math.floor((contentWidth.value + GRID_GAP) / (uiStore.thumbnailSize + GRID_GAP))
  )
})

const rowCount = computed(() => {
  if (columnCount.value === 0) return 0
  return Math.ceil(libraryStore.items.length / columnCount.value)
})

const rowHeight = computed(() => {
  if (columnCount.value === 0 || contentWidth.value <= 0) {
    return uiStore.thumbnailSize + GRID_GAP
  }

  const columnWidth = (contentWidth.value - GRID_GAP * (columnCount.value - 1)) / columnCount.value
  return columnWidth + GRID_GAP
})

const virtualizer = useVirtualizer(
  computed(() => ({
    count: rowCount.value,
    getScrollElement: () => scrollRef.value,
    estimateSize: () => rowHeight.value,
    overscan: GRID_BUFFER_ROWS
  }))
)

const virtualRows = computed(() => virtualizer.value.getVirtualItems())
const totalSize = computed(() => virtualizer.value.getTotalSize())

watch(rowHeight, () => {
  virtualizer.value.measure()
})

watch([() => libraryStore.focusedId, columnCount, () => libraryStore.items.length], async () => {
  if (initialScrollRestored.value) return
  if (!libraryStore.focusedId || columnCount.value === 0) return

  const index = libraryStore.items.findIndex((item) => item.id === libraryStore.focusedId)
  if (index < 0) return

  await nextTick()
  const rowIndex = Math.floor(index / columnCount.value)
  virtualizer.value.scrollToIndex(rowIndex, { align: 'center' })
  initialScrollRestored.value = true
})

let resizeObserver: ResizeObserver | null = null

onMounted(() => {
  const element = scrollRef.value
  if (!element) return

  const measure = (): void => {
    contentWidth.value = element.clientWidth - 24
  }

  measure()
  resizeObserver = new ResizeObserver(measure)
  resizeObserver.observe(element)
})

onUnmounted(() => {
  resizeObserver?.disconnect()
  resizeObserver = null
})

function getRowItems(rowIndex: number): MediaRecord[] {
  if (columnCount.value === 0) return []

  const start = rowIndex * columnCount.value
  return libraryStore.items.slice(start, start + columnCount.value)
}

async function onDropImport(event: DragEvent): Promise<void> {
  const files = Array.from(event.dataTransfer?.files ?? [])
  const paths = files
    .map((file) => (file as File & { path?: string }).path)
    .filter((path): path is string => typeof path === 'string' && path.length > 0)

  if (paths.length === 0) return

  await window.api.importMedia(paths)
  await libraryStore.loadMedia()
}
</script>

<template>
  <div ref="scrollRef" class="h-full overflow-auto p-3" @dragover.prevent @drop="onDropImport">
    <div
      :style="{
        height: `${totalSize}px`,
        position: 'relative',
        width: '100%'
      }"
    >
      <div
        v-for="virtualRow in virtualRows"
        :key="virtualRow.index"
        :style="{
          position: 'absolute',
          top: '0px',
          left: '0px',
          width: '100%',
          height: `${virtualRow.size - GRID_GAP}px`,
          transform: `translateY(${virtualRow.start}px)`,
          display: 'grid',
          gridTemplateColumns: `repeat(${columnCount}, 1fr)`,
          gap: `${GRID_GAP}px`
        }"
      >
        <MediaThumbnail
          v-for="(media, columnIndex) in getRowItems(virtualRow.index)"
          :key="media.id"
          :media="media"
          :index="virtualRow.index * columnCount + columnIndex"
          :selected="libraryStore.selectedIds.has(media.id)"
          :focused="media.id === libraryStore.focusedId"
          draggable="true"
          @click="(event: MouseEvent) => handleClick(event, media.id)"
          @dragstart="(event: DragEvent) => handleDragStart(event, media.id)"
          @dblclick="
            () => {
              handleDoubleClick(media.id)
              uiStore.setViewMode('loupe')
            }
          "
        />
      </div>
    </div>
  </div>
</template>

// src/renderer/components/library/GridView.tsx
import * as React from 'react'
import { useVirtualizer } from '@tanstack/react-virtual'

import { useLibraryStore } from '@/stores/library-store'
import { useUIStore } from '@/stores/ui-store'
import { useMediaItemHandlers } from '@/hooks/useMediaItemHandlers'
import { cn } from '@/lib/utils'
import { MediaThumbnail } from '@/components/library/MediaThumbnail'
import { GRID_BUFFER_ROWS } from '@/lib/constants'
import type { MediaRecord } from '@/types'

const GRID_GAP = 12 // Tailwind gap-3

function extractDroppedFilePaths(e: React.DragEvent): string[] {
  type FileWithPath = File & { path?: string }
  const files = Array.from(e.dataTransfer.files ?? [])
  const paths = files
    .map((f) => (f as FileWithPath).path)
    .filter((p): p is string => typeof p === 'string' && p.length > 0)
  return paths
}

interface GridCellProps {
  media: MediaRecord
  index: number
  selectionClasses: (id: string) => Record<string, boolean>
  handleClick: (e: React.MouseEvent, id: string) => void
  handleDragStart: (e: React.DragEvent, id: string) => void
  selectSingle: (id: string) => void
  setViewMode: (mode: 'grid' | 'loupe') => void
}

const GridCell = React.memo(function GridCell({
  media,
  index,
  selectionClasses,
  handleClick,
  handleDragStart,
  selectSingle,
  setViewMode
}: GridCellProps) {
  return (
    <button
      type="button"
      className={cn(
        'group relative aspect-square rounded-lg outline-none',
        selectionClasses(media.id)
      )}
      onClick={(e) => handleClick(e, media.id)}
      onDoubleClick={() => {
        selectSingle(media.id)
        setViewMode('loupe')
      }}
      draggable
      onDragStart={(e) => handleDragStart(e, media.id)}
    >
      <MediaThumbnail media={media} fallbackLabel={String(index + 1)} />
    </button>
  )
})

export function GridView(): React.JSX.Element {
  const items = useLibraryStore((s) => s.items)
  const focusedId = useLibraryStore((s) => s.focusedId)
  const selectSingle = useLibraryStore((s) => s.selectSingle)
  const thumbnailSize = useUIStore((s) => s.thumbnailSize)
  const setViewMode = useUIStore((s) => s.setViewMode)
  const { handleClick, handleDragStart, selectionClasses } = useMediaItemHandlers()

  const scrollRef = React.useRef<HTMLDivElement>(null)
  const [columnCount, setColumnCount] = React.useState(0)
  const [contentWidth, setContentWidth] = React.useState(0)
  const layoutReady = columnCount > 0

  // Compute column count and content width from container size + thumbnail size
  React.useEffect(() => {
    const el = scrollRef.current
    if (!el) return

    const measure = (): void => {
      const width = el.clientWidth - 24 // subtract p-3 padding (12px each side)
      const cols = Math.max(1, Math.floor((width + GRID_GAP) / (thumbnailSize + GRID_GAP)))
      setContentWidth(width)
      setColumnCount(cols)
    }

    measure()

    const observer = new ResizeObserver(measure)
    observer.observe(el)
    return () => observer.disconnect()
  }, [thumbnailSize])

  const rowCount = layoutReady ? Math.ceil(items.length / columnCount) : 0

  // Row height derived purely from state — no DOM reads in estimateSize
  const rowHeight = React.useMemo(() => {
    if (!layoutReady || contentWidth <= 0) return thumbnailSize + GRID_GAP
    const colWidth = (contentWidth - GRID_GAP * (columnCount - 1)) / columnCount
    return colWidth + GRID_GAP // aspect-square so height = width, plus gap
  }, [thumbnailSize, columnCount, contentWidth, layoutReady])

  const virtualizer = useVirtualizer({
    count: rowCount,
    getScrollElement: () => scrollRef.current,
    estimateSize: () => rowHeight,
    overscan: GRID_BUFFER_ROWS
  })

  // Invalidate cached measurements when row height changes
  React.useEffect(() => {
    virtualizer.measure()
  }, [rowHeight, virtualizer])

  // Scroll to the focused item's row on mount (e.g. returning from loupe view)
  const initialScrollDone = React.useRef(false)
  React.useEffect(() => {
    if (initialScrollDone.current) return
    if (!focusedId || !layoutReady) return
    const idx = items.findIndex((m) => m.id === focusedId)
    if (idx < 0) return
    const row = Math.floor(idx / columnCount)
    virtualizer.scrollToIndex(row, { align: 'center' })
    initialScrollDone.current = true
  }, [focusedId, items, columnCount, layoutReady, virtualizer])

  const onDropImport = React.useCallback(async (e: React.DragEvent) => {
    e.preventDefault()
    const filePaths = extractDroppedFilePaths(e)
    if (filePaths.length === 0) return

    await window.api.importMedia(filePaths)
  }, [])

  return (
    <div
      ref={scrollRef}
      className="h-full overflow-auto p-4"
      onDragOver={(e) => e.preventDefault()}
      onDrop={onDropImport}
    >
      <div
        style={{
          height: virtualizer.getTotalSize(),
          position: 'relative',
          width: '100%'
        }}
      >
        {virtualizer.getVirtualItems().map((virtualRow) => {
          const rowStartIndex = virtualRow.index * columnCount
          const rowItems = items.slice(rowStartIndex, rowStartIndex + columnCount)

          return (
            <div
              key={virtualRow.index}
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: virtualRow.size - GRID_GAP,
                transform: `translateY(${virtualRow.start}px)`,
                display: 'grid',
                gridTemplateColumns: `repeat(${columnCount}, 1fr)`,
                gap: GRID_GAP
              }}
            >
              {rowItems.map((m, colIdx) => (
                <GridCell
                  key={m.id}
                  media={m}
                  index={rowStartIndex + colIdx}
                  selectionClasses={selectionClasses}
                  handleClick={handleClick}
                  handleDragStart={handleDragStart}
                  selectSingle={selectSingle}
                  setViewMode={setViewMode}
                />
              ))}
            </div>
          )
        })}
      </div>
    </div>
  )
}
