// src/renderer/components/library/LoupeView.vue
<script setup lang="ts">
import { computed, watch } from 'vue'

import LoupeFilmstrip from '@/components/library/LoupeFilmstrip.vue'
import CanvasViewer from '@/components/library/canvas/CanvasViewer.vue'
import CropOverlay from '@/components/library/canvas/CropOverlay.vue'
import MaskOverlay from '@/components/library/canvas/MaskOverlay.vue'
import VideoPlayer from '@/components/library/VideoPlayer.vue'
import { useLibraryStore } from '@/stores/library'
import { useRemovalStore } from '@/stores/removal'
import { useUIStore } from '@/stores/ui'
import { useTransformStore } from '@/stores/transform'

const libraryStore = useLibraryStore()
const removalStore = useRemovalStore()
const uiStore = useUIStore()
const transformStore = useTransformStore()

const currentIndex = computed(() => {
  if (libraryStore.items.length === 0) return -1
  if (!libraryStore.focusedId) return 0

  const index = libraryStore.items.findIndex((item) => item.id === libraryStore.focusedId)
  return index >= 0 ? index : 0
})

const currentItem = computed(() => {
  if (currentIndex.value < 0) return null
  return libraryStore.items[currentIndex.value] ?? null
})

watch(
  [() => libraryStore.focusedId, () => libraryStore.items.length],
  () => {
    if (!libraryStore.focusedId && libraryStore.items[0]) {
      libraryStore.selectSingle(libraryStore.items[0].id)
    }
  },
  { immediate: true }
)

// Cancel crop if navigated away from the crop target
watch(
  () => currentItem.value,
  (current) => {
    if (!transformStore.cropMode || !transformStore.cropMediaId) return
    if (!current || current.id !== transformStore.cropMediaId || current.media_type !== 'image') {
      transformStore.cancelCrop()
    }
  }
)

// Cancel paint mode if navigated away from the paint target
watch(
  () => currentItem.value,
  (current) => {
    if (!removalStore.paintMode || !removalStore.paintMediaId) return
    if (!current || current.id !== removalStore.paintMediaId || current.media_type !== 'image') {
      removalStore.cancelPaintMode()
    }
  }
)

function onSelect(id: string): void {
  libraryStore.selectSingle(id)
}
</script>

<template>
  <div class="flex h-full flex-col overflow-hidden">
    <div class="relative min-h-0 flex-1 overflow-hidden px-4 pt-4 pb-2">
      <VideoPlayer v-if="currentItem?.media_type === 'video'" :media="currentItem" :zoom="uiStore.loupeZoom" />
      <template v-else>
        <CanvasViewer :media="currentItem" :zoom="uiStore.loupeZoom" />
        <CropOverlay />
        <MaskOverlay />
      </template>
    </div>

    <LoupeFilmstrip :items="libraryStore.items" :current-index="currentIndex" @select="onSelect" />
  </div>
</template>

// src/renderer/components/library/LoupeView.tsx
import * as React from 'react'

import { useLibraryStore } from '@/stores/library-store'
import { useUIStore } from '@/stores/ui-store'
import { useTransformStore } from '@/stores/transform-store'
import { useRemovalStore } from '@/stores/removal-store'
import { CanvasViewer } from '@/components/library/canvas/CanvasViewer'
import { CropOverlay } from '@/components/library/canvas/CropOverlay'
import { MaskOverlay } from '@/components/library/canvas/MaskOverlay'
import { VideoPlayer } from '@/components/library/VideoPlayer'
import { LoupeFilmstrip } from '@/components/library/LoupeFilmstrip'

export function LoupeView(): React.JSX.Element {
  const items = useLibraryStore((s) => s.items)
  const focusedId = useLibraryStore((s) => s.focusedId)
  const selectSingle = useLibraryStore((s) => s.selectSingle)
  const loupeZoom = useUIStore((s) => s.loupeZoom)
  const cropMode = useTransformStore((s) => s.cropMode)
  const cropMediaId = useTransformStore((s) => s.cropMediaId)
  const cancelCrop = useTransformStore((s) => s.cancelCrop)
  const paintMode = useRemovalStore((s) => s.paintMode)
  const paintMediaId = useRemovalStore((s) => s.paintMediaId)
  const cancelPaintMode = useRemovalStore((s) => s.cancelPaintMode)

  const currentIndex = focusedId ? items.findIndex((m) => m.id === focusedId) : -1
  const current = currentIndex >= 0 ? items[currentIndex] : (items[0] ?? null)

  React.useEffect(() => {
    if (!focusedId && items[0]) {
      selectSingle(items[0].id)
    }
  }, [focusedId, items, selectSingle])

  React.useEffect(() => {
    if (!cropMode || !cropMediaId) {
      return
    }

    if (!current || current.id !== cropMediaId || current.media_type !== 'image') {
      cancelCrop()
    }
  }, [cancelCrop, cropMediaId, cropMode, current])

  React.useEffect(() => {
    if (!paintMode || !paintMediaId) {
      return
    }

    if (!current || current.id !== paintMediaId || current.media_type !== 'image') {
      cancelPaintMode()
    }
  }, [cancelPaintMode, current, paintMediaId, paintMode])

  return (
    <div className="flex h-full flex-col overflow-hidden">
      <div className="min-h-0 flex-1 overflow-hidden pt-4 px-4 pb-2">
        {current?.media_type === 'video' ? (
          <VideoPlayer media={current} zoom={loupeZoom} />
        ) : (
          <div className="relative h-full w-full">
            <CanvasViewer media={current} zoom={loupeZoom} />
            <CropOverlay />
            <MaskOverlay />
          </div>
        )}
      </div>

      <LoupeFilmstrip items={items} currentIndex={currentIndex} onSelect={selectSingle} />
    </div>
  )
}
