// src/renderer/components/library/MediaThumbnail.vue
<script setup lang="ts">
import { computed } from 'vue'

import { formatDuration } from '@/lib/media'
import type { MediaRecord } from '@/types'

type OverlaySize = 'grid' | 'filmstrip'

const overlayClassBySize: Record<
  OverlaySize,
  {
    statusPosition: string
    statusBadgeSize: string
    statusIconSize: string
    ratingPosition: string
    ratingStarSize: string
  }
> = {
  grid: {
    statusPosition: 'top-1.5 left-1.5',
    statusBadgeSize: 'h-5 w-5',
    statusIconSize: 'size-3',
    ratingPosition: 'top-1.5 right-1.5',
    ratingStarSize: 'size-3'
  },
  filmstrip: {
    statusPosition: 'top-1 left-1',
    statusBadgeSize: 'h-4 w-4',
    statusIconSize: 'size-2.5',
    ratingPosition: 'top-1 right-1',
    ratingStarSize: 'size-2.5'
  }
}

const props = defineProps<{
  media: MediaRecord
  index: number
  selected: boolean
  focused: boolean
  overlaySize?: OverlaySize
}>()

defineEmits<{
  click: [event: MouseEvent]
  dblclick: []
}>()

const starCount = computed(() => Math.max(0, Math.min(5, Math.floor(props.media.rating))))
const isVideo = computed(() => props.media.media_type === 'video')
const overlayClasses = computed(() => overlayClassBySize[props.overlaySize ?? 'grid'])

const ringClass = computed(() => {
  if (props.focused) return 'ring-2 ring-primary'
  if (props.selected) return 'ring-2'
  return ''
})
</script>

<template>
  <button
    type="button"
    class="group relative aspect-square rounded-lg outline-none"
    :class="ringClass"
    @click="$emit('click', $event)"
    @dblclick="$emit('dblclick')"
  >
    <div class="relative h-full w-full overflow-hidden rounded-lg bg-muted">
      <img
        v-if="media.thumb_path"
        :src="media.thumb_path"
        :alt="media.file_name"
        class="absolute inset-0 h-full w-full object-cover"
        loading="lazy"
        draggable="false"
      />

      <div v-else class="absolute inset-0 flex items-center justify-center text-xs text-muted">
        {{ index + 1 }}
      </div>

      <div
        v-if="media.status"
        class="absolute flex items-center justify-center rounded-full bg-primary text-inverted shadow-sm"
        :class="[overlayClasses.statusPosition, overlayClasses.statusBadgeSize]"
      >
        <UIcon
          :name="media.status === 'selected' ? 'i-lucide-check' : 'i-lucide-x'"
          :class="overlayClasses.statusIconSize"
        />
      </div>

      <div
        v-if="starCount > 0"
        class="absolute flex items-center gap-px drop-shadow-sm"
        :class="overlayClasses.ratingPosition"
      >
        <UIcon
          v-for="starIndex in starCount"
          :key="starIndex"
          name="i-lucide-star"
          class="fill-primary text-primary"
          :class="overlayClasses.ratingStarSize"
        />
      </div>

      <template v-if="isVideo">
        <div class="absolute bottom-1.5 left-1.5 rounded-full bg-black/65 p-1 text-white shadow-sm">
          <UIcon name="i-lucide-play" class="size-3" />
        </div>

        <div
          v-if="media.duration !== null"
          class="absolute right-1.5 bottom-1.5 rounded bg-black/70 px-1.5 py-0.5 text-[10px] font-medium tabular-nums text-white shadow-sm"
        >
          {{ formatDuration(media.duration) }}
        </div>
      </template>
    </div>
  </button>
</template>

// src/renderer/components/library/MediaThumbnail.tsx
import * as React from 'react'
import { Check, Play, Star, X } from 'lucide-react'

import type { MediaRecord } from '@/types'
import { cn } from '@/lib/utils'
import { formatDuration } from '@/lib/media'

type OverlaySize = 'grid' | 'filmstrip'

interface MediaThumbnailProps {
  media: MediaRecord
  fallbackLabel: string
  className?: string
  overlaySize?: OverlaySize
}

const overlayClassBySize: Record<
  OverlaySize,
  {
    statusPosition: string
    statusBadgeSize: string
    statusIconSize: string
    ratingPosition: string
    ratingStarSize: string
  }
> = {
  grid: {
    statusPosition: 'top-1.5 left-1.5',
    statusBadgeSize: 'h-5 w-5',
    statusIconSize: 'h-3 w-3',
    ratingPosition: 'top-1.5 right-1.5',
    ratingStarSize: 'h-3 w-3'
  },
  filmstrip: {
    statusPosition: 'top-1 left-1',
    statusBadgeSize: 'h-4 w-4',
    statusIconSize: 'h-2.5 w-2.5',
    ratingPosition: 'top-1 right-1',
    ratingStarSize: 'h-2.5 w-2.5'
  }
}

export const MediaThumbnail = React.memo(function MediaThumbnail({
  media,
  fallbackLabel,
  className,
  overlaySize = 'grid'
}: MediaThumbnailProps): React.JSX.Element {
  const overlayClasses = overlayClassBySize[overlaySize]
  const starCount = Math.max(0, Math.min(5, Math.floor(media.rating)))
  const isVideo = media.media_type === 'video'

  return (
    <div className={cn('relative h-full w-full overflow-hidden rounded-md border bg-muted', className)}>
      {media.thumb_path ? (
        <img
          src={media.thumb_path}
          alt={media.file_name}
          className="absolute inset-0 h-full w-full object-cover"
          loading="lazy"
          draggable={false}
        />
      ) : (
        <div className="absolute inset-0 flex items-center justify-center text-xs text-muted-foreground">
          {fallbackLabel}
        </div>
      )}

      {media.status && (
        <div
          className={cn(
            'absolute flex items-center justify-center rounded-full bg-primary text-primary-foreground shadow-sm',
            overlayClasses.statusPosition,
            overlayClasses.statusBadgeSize
          )}
        >
          {media.status === 'selected' ? (
            <Check className={overlayClasses.statusIconSize} strokeWidth={3} />
          ) : (
            <X className={overlayClasses.statusIconSize} strokeWidth={3} />
          )}
        </div>
      )}

      {starCount > 0 && (
        <div className={cn('absolute flex items-center gap-px drop-shadow-sm', overlayClasses.ratingPosition)}>
          {Array.from({ length: starCount }, (_, index) => (
            <Star
              key={index}
              className={cn('fill-primary text-primary', overlayClasses.ratingStarSize)}
            />
          ))}
        </div>
      )}

      {isVideo && (
        <>
          <div className="absolute bottom-1.5 left-1.5 rounded-full bg-black/65 p-1 text-white shadow-sm">
            <Play className="size-3 fill-current" />
          </div>
          {media.duration !== null && (
            <div className="absolute right-1.5 bottom-1.5 rounded bg-black/70 px-1.5 py-0.5 text-[10px] font-medium tabular-nums text-white shadow-sm">
              {formatDuration(media.duration)}
            </div>
          )}
        </>
      )}
    </div>
  )
})
