// src/renderer/components/library/VideoPlayer.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import { Icon } from '@iconify/vue'
import Slider from 'primevue/slider'

import { formatDuration } from '@/lib/media'
import type { ZoomLevel } from '@/stores/ui'
import type { MediaRecord } from '@/types'

interface Pan {
  x: number
  y: number
}

const props = defineProps<{
  media: MediaRecord | null
  zoom?: ZoomLevel
}>()

function clampPan(pan: Pan, overflowX: number, overflowY: number): Pan {
  const clampedX = overflowX > 0 ? Math.max(-overflowX / 2, Math.min(overflowX / 2, pan.x)) : 0
  const clampedY = overflowY > 0 ? Math.max(-overflowY / 2, Math.min(overflowY / 2, pan.y)) : 0
  return { x: clampedX, y: clampedY }
}

const containerRef = ref<HTMLDivElement | null>(null)
const videoRef = ref<HTMLVideoElement | null>(null)

const containerSize = ref({ width: 0, height: 0 })
const nativeSize = ref({ width: 0, height: 0 })
const pan = ref<Pan>({ x: 0, y: 0 })
const isDragging = ref(false)
const dragStart = ref<{ mouseX: number; mouseY: number; pan: Pan } | null>(null)

const isPlaying = ref(false)
const currentTime = ref(0)
const duration = ref(props.media?.duration ?? 0)
const volume = ref(1)
const isMuted = ref(false)
const isLooping = ref(false)

const controlsPinned = ref(false)
const controlsVisible = ref(true)
let hideTimer: number | null = null

const sourceUrl = computed(() => props.media?.working_file_path ?? props.media?.file_path ?? null)
const zoom = computed(() => props.zoom ?? 'fit')

// ---------------------------------------------------------------------------
// Resize observer
// ---------------------------------------------------------------------------

let resizeObserver: ResizeObserver | null = null

watch(
  containerRef,
  (el) => {
    resizeObserver?.disconnect()
    if (!el) return
    resizeObserver = new ResizeObserver(() => {
      const rect = el.getBoundingClientRect()
      containerSize.value = { width: rect.width, height: rect.height }
    })
    resizeObserver.observe(el)
  },
  { immediate: true }
)

onBeforeUnmount(() => {
  resizeObserver?.disconnect()
  clearHideTimer()
})

// ---------------------------------------------------------------------------
// Reset state on source/zoom change
// ---------------------------------------------------------------------------

watch([zoom, sourceUrl], () => {
  pan.value = { x: 0, y: 0 }
})

watch(
  () => props.media?.id,
  () => {
    currentTime.value = 0
    duration.value = props.media?.duration ?? 0
    nativeSize.value = { width: 0, height: 0 }
    isPlaying.value = false
  }
)

// ---------------------------------------------------------------------------
// Geometry
// ---------------------------------------------------------------------------

const geometry = computed(() => {
  const w = containerSize.value.width
  const h = containerSize.value.height
  const vw = nativeSize.value.width
  const vh = nativeSize.value.height

  if (w <= 0 || h <= 0 || vw <= 0 || vh <= 0) {
    return {
      displayWidth: 0,
      displayHeight: 0,
      overflowX: 0,
      overflowY: 0,
      left: 0,
      top: 0,
      isPannable: false,
      clampedPan: { x: 0, y: 0 }
    }
  }

  const scale = zoom.value === 'actual' ? 1 : Math.min(w / vw, h / vh)
  const displayWidth = vw * scale
  const displayHeight = vh * scale
  const overflowX = Math.max(0, displayWidth - w)
  const overflowY = Math.max(0, displayHeight - h)
  const clampedPan = clampPan(pan.value, overflowX, overflowY)

  return {
    displayWidth,
    displayHeight,
    overflowX,
    overflowY,
    left: (w - displayWidth) / 2 + clampedPan.x,
    top: (h - displayHeight) / 2 + clampedPan.y,
    isPannable: overflowX > 0 || overflowY > 0,
    clampedPan
  }
})

watch(
  () => geometry.value.clampedPan,
  (clamped) => {
    if (pan.value.x !== clamped.x || pan.value.y !== clamped.y) {
      pan.value = clamped
    }
  }
)

// ---------------------------------------------------------------------------
// Controls visibility
// ---------------------------------------------------------------------------

function clearHideTimer(): void {
  if (hideTimer !== null) {
    window.clearTimeout(hideTimer)
    hideTimer = null
  }
}

function scheduleControlsHide(): void {
  clearHideTimer()
  if (controlsPinned.value) return
  hideTimer = window.setTimeout(() => {
    controlsVisible.value = false
  }, 2000)
}

function revealControls(): void {
  controlsVisible.value = true
  scheduleControlsHide()
}

watch(controlsPinned, (pinned) => {
  if (pinned) {
    clearHideTimer()
    controlsVisible.value = true
  } else {
    scheduleControlsHide()
  }
})

// ---------------------------------------------------------------------------
// Video events
// ---------------------------------------------------------------------------

function onLoadedMetadata(): void {
  const video = videoRef.value
  if (!video) return
  nativeSize.value = { width: video.videoWidth || 0, height: video.videoHeight || 0 }
  duration.value = Number.isFinite(video.duration) ? video.duration : (props.media?.duration ?? 0)
}

function onTimeUpdate(): void {
  const video = videoRef.value
  if (video) currentTime.value = video.currentTime
}

function onPlay(): void {
  isPlaying.value = true
}
function onPause(): void {
  isPlaying.value = false
}

function onVolumeChange(): void {
  const video = videoRef.value
  if (!video) return
  volume.value = video.volume
  isMuted.value = video.muted || video.volume <= 0
}

// ---------------------------------------------------------------------------
// Playback controls
// ---------------------------------------------------------------------------

async function togglePlayback(): Promise<void> {
  const video = videoRef.value
  if (!video) return
  if (video.paused) {
    try {
      await video.play()
    } catch {
      // Ignore play interruption
    }
    return
  }
  video.pause()
}

function handleSeek(value: number | number[]): void {
  const v = Array.isArray(value) ? value[0] : value
  if (v === undefined) return
  currentTime.value = v
  const video = videoRef.value
  if (video) video.currentTime = v
}

function handleVolumeSlider(value: number | number[]): void {
  const v = Array.isArray(value) ? value[0] ?? 0 : value
  const video = videoRef.value
  if (!video) return
  const nextVolume = Math.max(0, Math.min(1, v / 100))
  video.volume = nextVolume
  video.muted = nextVolume <= 0
  volume.value = nextVolume
  isMuted.value = video.muted
}

function toggleMute(): void {
  const video = videoRef.value
  if (!video) return
  video.muted = !video.muted
  isMuted.value = video.muted
}

function toggleLoop(): void {
  const video = videoRef.value
  if (!video) return
  video.loop = !video.loop
  isLooping.value = video.loop
}

// ---------------------------------------------------------------------------
// Pan / drag
// ---------------------------------------------------------------------------

function onMouseDown(event: MouseEvent): void {
  if (!geometry.value.isPannable) return
  dragStart.value = { mouseX: event.clientX, mouseY: event.clientY, pan: { ...pan.value } }
  isDragging.value = true
}

function onMouseMove(event: MouseEvent): void {
  revealControls()
  if (!isDragging.value || !dragStart.value) return
  const dx = event.clientX - dragStart.value.mouseX
  const dy = event.clientY - dragStart.value.mouseY
  pan.value = clampPan(
    { x: dragStart.value.pan.x + dx, y: dragStart.value.pan.y + dy },
    geometry.value.overflowX,
    geometry.value.overflowY
  )
}

function endDrag(): void {
  dragStart.value = null
  isDragging.value = false
}

const cursor = computed(() =>
  geometry.value.isPannable ? (isDragging.value ? 'grabbing' : 'grab') : 'default'
)

const volumeDisplay = computed(() => Math.round((isMuted.value ? 0 : volume.value) * 100))
</script>

<template>
  <div
    v-if="!media || !sourceUrl"
    class="flex h-full w-full items-center justify-center rounded-md bg-black/70 text-sm text-muted"
  >
    No selection
  </div>

  <div
    v-else
    ref="containerRef"
    class="relative h-full w-full overflow-hidden rounded-md bg-black"
    @mousemove="revealControls"
    @mouseenter="revealControls"
    @mouseleave="
      () => {
        endDrag()
        if (!controlsPinned) controlsVisible = false
      }
    "
  >
    <!-- Video area (pannable) -->
    <div
      class="absolute inset-0"
      :style="{ cursor }"
      @mousedown="onMouseDown"
      @mousemove="onMouseMove"
      @mouseup="endDrag"
      @mouseleave="endDrag"
    >
      <video
        ref="videoRef"
        :src="sourceUrl"
        class="absolute"
        preload="metadata"
        @loadedmetadata="onLoadedMetadata"
        @durationchange="onLoadedMetadata"
        @timeupdate="onTimeUpdate"
        @play="onPlay"
        @pause="onPause"
        @volumechange="onVolumeChange"
        :style="{
          left: `${geometry.left}px`,
          top: `${geometry.top}px`,
          width: `${geometry.displayWidth}px`,
          height: `${geometry.displayHeight}px`
        }"
      />
    </div>

    <!-- Controls overlay -->
    <div
      class="absolute bottom-0 left-0 right-0 z-20 bg-black/58 px-3 py-2.5 backdrop-blur-sm transition-opacity duration-200"
      :class="controlsVisible ? 'opacity-100' : 'pointer-events-none opacity-0'"
    >
      <div class="flex items-center gap-2.5">
        <!-- Play/Pause -->
        <button
          type="button"
          class="rounded-sm p-1 text-white/90 transition hover:bg-white/15"
          :aria-label="isPlaying ? 'Pause' : 'Play'"
          @click="togglePlayback()"
        >
          <Icon :icon="isPlaying ? 'lucide:pause' : 'lucide:play'" class="size-4" />
        </button>

        <!-- Time display -->
        <div class="min-w-24 text-xs tabular-nums text-white/85">
          {{ formatDuration(currentTime) }} / {{ formatDuration(duration) }}
        </div>

        <!-- Seek slider -->
        <Slider
          :model-value="Math.min(currentTime, duration || 0)"
          :max="Math.max(duration, 0.001)"
          :step="0.01"
          class="mx-1 flex-1"
          aria-label="Seek"
          @update:model-value="handleSeek"
        />

        <!-- Mute -->
        <button
          type="button"
          class="rounded-sm p-1 text-white/90 transition hover:bg-white/15"
          :aria-label="isMuted ? 'Unmute' : 'Mute'"
          @click="toggleMute"
        >
          <Icon :icon="isMuted ? 'lucide:volume-x' : 'lucide:volume-2'" class="size-4" />
        </button>

        <!-- Volume slider -->
        <Slider
          :model-value="volumeDisplay"
          :max="100"
          :step="1"
          class="w-20"
          aria-label="Volume"
          @update:model-value="handleVolumeSlider"
        />

        <!-- Loop -->
        <button
          type="button"
          class="rounded-sm p-1 text-white/90 transition hover:bg-white/15"
          :class="isLooping && 'bg-white/18'"
          aria-label="Loop"
          @click="toggleLoop"
        >
          <Icon icon="lucide:repeat" class="size-4" />
        </button>

        <!-- Pin controls -->
        <button
          type="button"
          class="rounded-sm p-1 text-white/90 transition hover:bg-white/15"
          :class="controlsPinned && 'bg-white/18'"
          :aria-label="controlsPinned ? 'Unpin controls' : 'Pin controls'"
          @click="controlsPinned = !controlsPinned"
        >
          <Icon icon="lucide:pin" class="size-4" />
        </button>
      </div>
    </div>
  </div>
</template>

// src/renderer/components/library/VideoPlayer.tsx
import * as React from 'react'
import { Pause, Pin, Play, Repeat, Volume2, VolumeX } from 'lucide-react'

import { Slider } from '@/components/ui/slider'
import { cn } from '@/lib/utils'
import { formatDuration } from '@/lib/media'
import type { ZoomLevel } from '@/stores/ui-store'
import type { MediaRecord } from '@/types'

interface VideoPlayerProps {
  media: MediaRecord | null
  zoom?: ZoomLevel
}

interface Pan {
  x: number
  y: number
}

function clampPan(pan: Pan, overflowX: number, overflowY: number): Pan {
  const clampedX = overflowX > 0 ? Math.max(-overflowX / 2, Math.min(overflowX / 2, pan.x)) : 0
  const clampedY = overflowY > 0 ? Math.max(-overflowY / 2, Math.min(overflowY / 2, pan.y)) : 0

  return { x: clampedX, y: clampedY }
}

export function VideoPlayer({ media, zoom = 'fit' }: VideoPlayerProps): React.JSX.Element {
  const containerRef = React.useRef<HTMLDivElement | null>(null)
  const videoRef = React.useRef<HTMLVideoElement | null>(null)
  const hideTimerRef = React.useRef<number | null>(null)
  const dragStartRef = React.useRef<{ mouseX: number; mouseY: number; pan: Pan } | null>(null)

  const [containerSize, setContainerSize] = React.useState({ width: 0, height: 0 })
  const [nativeSize, setNativeSize] = React.useState({ width: 0, height: 0 })
  const [pan, setPan] = React.useState<Pan>({ x: 0, y: 0 })
  const [isDragging, setIsDragging] = React.useState(false)

  const [isPlaying, setIsPlaying] = React.useState(false)
  const [currentTime, setCurrentTime] = React.useState(0)
  const [duration, setDuration] = React.useState(media?.duration ?? 0)
  const [volume, setVolume] = React.useState(1)
  const [isMuted, setIsMuted] = React.useState(false)
  const [isLooping, setIsLooping] = React.useState(false)

  const [controlsPinned, setControlsPinned] = React.useState(false)
  const [controlsVisible, setControlsVisible] = React.useState(true)

  const sourceUrl = media?.working_file_path ?? media?.file_path ?? null

  React.useEffect(() => {
    const container = containerRef.current
    if (!container) return

    const observer = new ResizeObserver(() => {
      const rect = container.getBoundingClientRect()
      setContainerSize({ width: rect.width, height: rect.height })
    })

    observer.observe(container)
    return () => observer.disconnect()
  }, [])

  React.useEffect(() => {
    setPan({ x: 0, y: 0 })
  }, [zoom, sourceUrl])

  React.useEffect(() => {
    setCurrentTime(0)
    setDuration(media?.duration ?? 0)
    setNativeSize({ width: 0, height: 0 })
    setIsPlaying(false)
  }, [media?.id, media?.duration])

  const geometry = React.useMemo(() => {
    const width = containerSize.width
    const height = containerSize.height
    const videoWidth = nativeSize.width
    const videoHeight = nativeSize.height

    if (width <= 0 || height <= 0 || videoWidth <= 0 || videoHeight <= 0) {
      return {
        displayWidth: 0,
        displayHeight: 0,
        overflowX: 0,
        overflowY: 0,
        left: 0,
        top: 0,
        isPannable: false,
        clampedPan: { x: 0, y: 0 }
      }
    }

    const scale = zoom === 'actual' ? 1 : Math.min(width / videoWidth, height / videoHeight)
    const displayWidth = videoWidth * scale
    const displayHeight = videoHeight * scale
    const overflowX = Math.max(0, displayWidth - width)
    const overflowY = Math.max(0, displayHeight - height)
    const clampedPan = clampPan(pan, overflowX, overflowY)

    return {
      displayWidth,
      displayHeight,
      overflowX,
      overflowY,
      left: (width - displayWidth) / 2 + clampedPan.x,
      top: (height - displayHeight) / 2 + clampedPan.y,
      isPannable: overflowX > 0 || overflowY > 0,
      clampedPan
    }
  }, [containerSize.height, containerSize.width, nativeSize.height, nativeSize.width, pan, zoom])

  React.useEffect(() => {
    if (pan.x === geometry.clampedPan.x && pan.y === geometry.clampedPan.y) {
      return
    }

    setPan(geometry.clampedPan)
  }, [geometry.clampedPan, pan.x, pan.y])

  const clearHideTimer = React.useCallback(() => {
    if (hideTimerRef.current !== null) {
      window.clearTimeout(hideTimerRef.current)
      hideTimerRef.current = null
    }
  }, [])

  const scheduleControlsHide = React.useCallback(() => {
    clearHideTimer()
    if (controlsPinned) {
      return
    }

    hideTimerRef.current = window.setTimeout(() => {
      setControlsVisible(false)
    }, 2000)
  }, [clearHideTimer, controlsPinned])

  const revealControls = React.useCallback(() => {
    setControlsVisible(true)
    scheduleControlsHide()
  }, [scheduleControlsHide])

  React.useEffect(() => {
    if (controlsPinned) {
      clearHideTimer()
      setControlsVisible(true)
      return
    }

    scheduleControlsHide()
  }, [clearHideTimer, controlsPinned, scheduleControlsHide])

  React.useEffect(() => {
    return () => {
      clearHideTimer()
    }
  }, [clearHideTimer])

  const handleLoadedMetadata = React.useCallback(() => {
    const video = videoRef.current
    if (!video) return

    setNativeSize({
      width: video.videoWidth || 0,
      height: video.videoHeight || 0
    })
    setDuration(Number.isFinite(video.duration) ? video.duration : (media?.duration ?? 0))
  }, [media?.duration])

  const handleTimeUpdate = React.useCallback(() => {
    const video = videoRef.current
    if (!video) return

    setCurrentTime(video.currentTime)
  }, [])

  const handlePlay = React.useCallback(() => setIsPlaying(true), [])
  const handlePause = React.useCallback(() => setIsPlaying(false), [])

  const handleVolumeChange = React.useCallback(() => {
    const video = videoRef.current
    if (!video) return

    setVolume(video.volume)
    setIsMuted(video.muted || video.volume <= 0)
  }, [])

  const togglePlayback = React.useCallback(async () => {
    const video = videoRef.current
    if (!video) return

    if (video.paused) {
      try {
        await video.play()
      } catch {
        // Ignore play interruption (for example on source swap).
      }
      return
    }

    video.pause()
  }, [])

  const handleSeekChange = React.useCallback((value: number[]) => {
    if (!value[0] && value[0] !== 0) return
    setCurrentTime(value[0])
  }, [])

  const handleSeekCommit = React.useCallback((value: number[]) => {
    const video = videoRef.current
    if (!video) return
    if (!value[0] && value[0] !== 0) return

    video.currentTime = value[0]
  }, [])

  const handleVolumeSlider = React.useCallback((value: number[]) => {
    const video = videoRef.current
    if (!video) return

    const nextVolume = Math.max(0, Math.min(1, (value[0] ?? 0) / 100))
    video.volume = nextVolume
    video.muted = nextVolume <= 0
    setVolume(nextVolume)
    setIsMuted(video.muted)
  }, [])

  const toggleMute = React.useCallback(() => {
    const video = videoRef.current
    if (!video) return

    const nextMuted = !video.muted
    video.muted = nextMuted
    setIsMuted(nextMuted)
  }, [])

  const toggleLoop = React.useCallback(() => {
    const video = videoRef.current
    if (!video) return

    const nextLoop = !video.loop
    video.loop = nextLoop
    setIsLooping(nextLoop)
  }, [])

  const onMouseDown = React.useCallback(
    (event: React.MouseEvent) => {
      if (!geometry.isPannable) return

      dragStartRef.current = {
        mouseX: event.clientX,
        mouseY: event.clientY,
        pan
      }
      setIsDragging(true)
    },
    [geometry.isPannable, pan]
  )

  const onMouseMove = React.useCallback(
    (event: React.MouseEvent) => {
      revealControls()

      if (!isDragging || !dragStartRef.current) {
        return
      }

      const deltaX = event.clientX - dragStartRef.current.mouseX
      const deltaY = event.clientY - dragStartRef.current.mouseY
      const nextPan = {
        x: dragStartRef.current.pan.x + deltaX,
        y: dragStartRef.current.pan.y + deltaY
      }

      setPan(clampPan(nextPan, geometry.overflowX, geometry.overflowY))
    },
    [geometry.overflowX, geometry.overflowY, isDragging, revealControls]
  )

  const endDrag = React.useCallback(() => {
    dragStartRef.current = null
    setIsDragging(false)
  }, [])

  const cursor = geometry.isPannable ? (isDragging ? 'grabbing' : 'grab') : 'default'

  const controlsClass = cn(
    'absolute bottom-0 left-0 right-0 z-20 bg-black/58 px-3 py-2.5 backdrop-blur-sm transition-opacity duration-200',
    controlsVisible ? 'opacity-100' : 'pointer-events-none opacity-0'
  )

  if (!media || !sourceUrl) {
    return (
      <div className="flex h-full w-full items-center justify-center rounded-md bg-black/70 text-sm text-muted-foreground">
        No selection
      </div>
    )
  }

  return (
    <div
      ref={containerRef}
      className="relative h-full w-full overflow-hidden rounded-md bg-black"
      onMouseMove={revealControls}
      onMouseEnter={revealControls}
      onMouseLeave={() => {
        endDrag()
        if (!controlsPinned) {
          setControlsVisible(false)
        }
      }}
    >
      <div
        className="absolute inset-0"
        onMouseDown={onMouseDown}
        onMouseMove={onMouseMove}
        onMouseUp={endDrag}
        onMouseLeave={endDrag}
        style={{ cursor }}
      >
        <video
          ref={videoRef}
          src={sourceUrl}
          className="absolute"
          preload="metadata"
          onLoadedMetadata={handleLoadedMetadata}
          onTimeUpdate={handleTimeUpdate}
          onDurationChange={handleLoadedMetadata}
          onPlay={handlePlay}
          onPause={handlePause}
          onVolumeChange={handleVolumeChange}
          style={{
            left: `${geometry.left}px`,
            top: `${geometry.top}px`,
            width: `${geometry.displayWidth}px`,
            height: `${geometry.displayHeight}px`
          }}
        />
      </div>

      <div className={controlsClass}>
        <div className="flex items-center gap-2.5">
          <button
            type="button"
            onClick={() => void togglePlayback()}
            className="rounded-sm p-1 text-white/90 transition hover:bg-white/15"
            aria-label={isPlaying ? 'Pause' : 'Play'}
          >
            {isPlaying ? <Pause className="size-4" /> : <Play className="size-4" />}
          </button>

          <div className="min-w-24 text-xs tabular-nums text-white/85">
            {formatDuration(currentTime)} / {formatDuration(duration)}
          </div>

          <Slider
            value={[Math.min(currentTime, duration || 0)]}
            max={Math.max(duration, 0.001)}
            step={0.01}
            onValueChange={handleSeekChange}
            onValueCommit={handleSeekCommit}
            className="mx-1 flex-1"
            aria-label="Seek"
          />

          <button
            type="button"
            onClick={toggleMute}
            className="rounded-sm p-1 text-white/90 transition hover:bg-white/15"
            aria-label={isMuted ? 'Unmute' : 'Mute'}
          >
            {isMuted ? <VolumeX className="size-4" /> : <Volume2 className="size-4" />}
          </button>

          <Slider
            value={[Math.round((isMuted ? 0 : volume) * 100)]}
            max={100}
            step={1}
            onValueChange={handleVolumeSlider}
            className="w-20"
            aria-label="Volume"
          />

          <button
            type="button"
            onClick={toggleLoop}
            className={cn(
              'rounded-sm p-1 text-white/90 transition hover:bg-white/15',
              isLooping && 'bg-white/18'
            )}
            aria-label="Loop"
          >
            <Repeat className="size-4" />
          </button>

          <button
            type="button"
            onClick={() => setControlsPinned((current) => !current)}
            className={cn(
              'rounded-sm p-1 text-white/90 transition hover:bg-white/15',
              controlsPinned && 'bg-white/18'
            )}
            aria-label={controlsPinned ? 'Unpin controls' : 'Pin controls'}
          >
            <Pin className="size-4" />
          </button>
        </div>
      </div>
    </div>
  )
}
